# CSV einlesen (drinking_fountain.csv & smartphones_scraped.csv)

In [1]:
import os
import pandas as pd

# Arbeitsordner und Dateinamen anzeigen
print("Arbeitsordner:", os.getcwd())
print("Dateien:", os.listdir())

# Drinking Fountains einlesen
df_ap02fountains = pd.read_csv('./drinking_fountains.csv', sep=',', encoding='utf-8')

# Smartphones bereinigt einlesen
df_ap02smartphones = pd.read_csv('./smartphones_bereinigt_MINL.csv', sep=',', encoding='utf-8')

# Smartphones unbereinigt einlesen
df_ap02smartphonesraw = pd.read_csv('./smartphones_scraped.csv', sep=',', encoding='utf-8')

# Erste fünf Zeilen anzeigen
display(df_ap02fountains.head())
display(df_ap02smartphones.head())

Arbeitsordner: /workspaces/DS_HS2026_LNW/DS_HS2026_LNW_I_Examples/AP02/AP02 V4 Data Ingestion & DF Analysis
Dateien: ['smartphones_scraped.csv', 'smartphones_bereinigt_MINL.csv', 'AP02 Spick DF Analysis.ipynb', 'AP02 Spick DI.ipynb', 'drinking_fountains.csv']

     osm_id osm_type        lat       lon                name
0  60030906     node  47.413534  8.541278    Notwasserbrunnen
1  60733338     node  47.402830  8.499940  Tränkbrunnen Höngg
2  60733384     node  47.402164  8.499442                 NaN
3  60734353     node  47.407291  8.550476                 NaN
4  61263856     node  47.405301  8.503774                 NaN

  product_id    brand                 model  price_chf            availability
0   PM-10001   Xiaomi  Redmi Note 14 Pro 5G      299.0        Sofort lieferbar
1   PM-10002  OnePlus            OnePlus 13      899.0  Lieferbar in 2–5 Tagen
2   PM-10003   Google          Pixel 10 Pro     1249.0        Sofort lieferbar
3   PM-10004  Samsung         Galaxy A36 5G      339.0        Sofort lieferbar
4   PM-10005  Samsung        Galaxy Z Fold7        NaN           Vorbestellung

# DataFrames analysieren – Daten untersuchen und verstehen

**Definition:** Ein Pandas-DataFrame (`pd.DataFrame`) ist eine zweidimensionale Datenstruktur mit Zeilen und benannten Spalten (ähnlich einer Tabelle in SQL). Nach dem Einlesen von CSV-, Excel-, JSON-, HTML- oder anderen Datenquellen kann der DataFrame mit verschiedenen Pandas-Methoden untersucht werden

**Ziel:** Struktur, Umfang, Datentypen, Datenqualität, statistische Kennzahlen und auffällige Werte erkennen, bevor die Daten weiterverarbeitet werden

**Wichtig für die Prüfung:**
- **Erst untersuchen, dann verändern:** Zunächst mit `head()`, `info()`, `describe()`, `isna()` und `duplicated()` einen Überblick gewinnen
- **Bei grossen DataFrames:** Nicht alle Zeilen ausgeben, sondern gezielt filtern, sortieren oder mit `head()` begrenzen
- **Numerische Datentypen:** `max()`, `mean()`, `nlargest()` und numerische Vergleiche setzen geeignete Datentypen voraus
- **Fehlende Werte:** Vor statistischen Analysen immer prüfen, ob und wo Werte fehlen
- **Duplikate:** Vor dem Entfernen prüfen, ob identische Datensätze tatsächlich unerwünscht sind

#### 1. DataFrame anzeigen und Struktur untersuchen

| Befehl | Erklärung |
|---|---|
| `display(df)` | DataFrame tabellarisch anzeigen; bei grossen Datenmengen werden Zeilen standardmässig gekürzt |
| `df.head(5)` | Die ersten fünf Datensätze anzeigen |
| `df.tail(5)` | Die letzten fünf Datensätze anzeigen |
| `df.sample(5)` | Fünf zufällige Datensätze anzeigen |
| `df.shape` | Anzahl Zeilen und Spalten als Tupel `(Zeilen, Spalten)` zurückgeben |
| `len(df)` | Anzahl Datensätze (Zeilen) ermitteln |
| `df.columns` | Alle Spaltennamen anzeigen |
| `df.index` | Zeilenindex anzeigen |
| `df.dtypes` | Datentyp jeder Spalte anzeigen |
| `df.info()` | Zusammenfassung mit Spalten, Datentypen, Anzahl nicht fehlender Werte und Speicherverbrauch ausgeben |
| `df.select_dtypes(include='number')` | Nur numerische Spalten auswählen |
| `df.select_dtypes(include='object')` | Nur Spalten mit dem Pandas-Datentyp `object` auswählen; häufig Textspalten |
| `pd.option_context('display.max_rows', None, 'display.max_columns', None)` | **Vollständige Ausgabe:** Damit lassen sich sämtliche \n Zeilen und Spalten anzeigen. Bei sehr grossen DataFrames kann dies jedoch zu langen und langsamen Ausgaben führen |

In [6]:
#Jupyter zeigt das Ergebnis des letzten Ausdrucks einer Zelle automatisch an
#Deshalb funktioniert das ohne display(). Man braucht es nur, wenn man auch ein vorheriges Ergebnis derselben Zelle anzeigen möchte
#display(): für Tabellen und DataFrames → übersichtlich als Tabelle formatiert
#print(): für einzelne Zahlen, Texte und Meldungen → einfache Textausgabe

display(df_ap02fountains.head())                            #Erste 5 Zeilen anzeigen, auch wenn danach weiterer Code folgt

# Dimension (rows, columns)
print('Dimension:', df_ap02smartphones.shape)               #Anzahl Zeilen und Spalten als (Zeilen, Spalten) anzeigen

# Number of rows
print('Number of rows:', df_ap02smartphones.shape[0])       #Anzahl Zeilen (Datensätze) anzeigen

# Number of columns
print('Number of columns:', df_ap02smartphones.shape[1])    #Anzahl Spalten (Merkmale) anzeigen

print(df_ap02smartphones.columns.tolist())                  #Spaltennamen als übersichtliche Liste ausgeben

display(df_ap02smartphones.dtypes)                                 #Datentyp jeder Spalte anzeigen

     osm_id osm_type        lat       lon                name
0  60030906     node  47.413534  8.541278    Notwasserbrunnen
1  60733338     node  47.402830  8.499940  Tränkbrunnen Höngg
2  60733384     node  47.402164  8.499442                 NaN
3  60734353     node  47.407291  8.550476                 NaN
4  61263856     node  47.405301  8.503774                 NaN

Dimension: (47, 5)
Number of rows: 47
Number of columns: 5
['product_id', 'brand', 'model', 'price_chf', 'availability']

product_id          str
brand               str
model               str
price_chf       float64
availability        str
dtype: object

#### 2. Missing Values – Fehlende Werte erkennen

| Befehl | Erklärung |
|---|---|
| `df.isna()` | Prüft jede Zelle auf fehlende Werte; `True` bedeutet fehlend |
| `df.isna().sum()` | Anzahl fehlender Werte pro Spalte |
| `df.isna().sum().sum()` | Gesamtanzahl fehlender Werte im gesamten DataFrame |
| `df.isna().mean() * 100` | Prozentualer Anteil fehlender Werte pro Spalte |
| `df.isna().any(axis=1)` | Prüft für jede Zeile, ob mind. ein Wert fehlt |
| `df[df.isna().any(axis=1)]` | Zeigt alle Datensätze mit mind. einem fehlenden Wert |
| `df.notna().sum()` | Anzahl vorhandener Werte pro Spalte |
| `df.count()` | Anzahl nicht fehlender Werte pro Spalte |
| `df.isna().sum().loc[lambda x: x > 0]` |	Zeigt nur Spalten mit fehlenden Werten und deren Anzahl

**Wichtig:** `isna()` erkennt bspw. `NaN`, `None` und `NaT`. Leere Strings (`''`) oder reine Leerzeichen gelten nicht automatisch als fehlende Werte

**Unterschied:** `count()` zählt nur vorhandene Werte pro Spalte, während `len(df)` sämtliche Zeilen zählt

In [ ]:
display(df_ap02fountains.isna().sum())                              #Anzahl fehlender Werte pro Spalte anzeigen

display(df_ap02smartphones[df_ap02smartphones.isna().any(axis=1)])  #Ganze Zeilen anzeigen, in denen mind. ein Wert fehlt

#### 3. Statistische Kennzahlen untersuchen

| Befehl | Erklärung |
|---|---|
| `df.describe()` | Deskriptive Statistik der numerischen Spalten: Anzahl, Mittelwert, Standardabweichung, Minimum, Quartile und Maximum |
| `df.describe(include='all')` | Statistische Übersicht über alle Spalten, einschliesslich kategorialer Spalten |
| `df['price'].min()` | Kleinsten Wert einer numerischen Spalte ermitteln |
| `df['price'].max()` | Grössten Wert einer numerischen Spalte ermitteln |
| `df['price'].mean()` | Arithmetischen Mittelwert berechnen |
| `df['price'].median()` | Median berechnen |
| `df['price'].sum()` | Alle vorhandenen numerischen Werte aufsummieren |

**Interpretation von `describe()`:**
- **`count`:** Anzahl nicht fehlender Werte (fehlende Werte werden nicht mitgezählt)
- **`mean`:** Arithmetischer Mittelwert (Summe aller Werte geteilt durch deren Anzahl)
- **`std`:** Standardabweichung (wie stark die Werte um den Durchschnitt streuen; grösser bedeutet stärker verstreut)
- **`min` / `max`:** Kleinster bzw. grösster Wert
- **`25%` / `50%` / `75%`:** Erstes Quartil, Median und drittes Quartil (25 %, 50 % bzw. 75 % der Werte liegen auf oder unter dem jeweiligen Wert)
- **`unique`:** Anzahl unterschiedlicher Kategorien (bei geeigneten nicht numerischen Spalten, jede Kategorie wird nur einmal gezählt)
- **`top`:** Häufigste Kategorie
- **`freq`:** Häufigkeit der häufigsten Kategorie

In [ ]:
display(df_ap02smartphones.describe())                                          #Statistische Kennzahlen der numerischen Spalten anzeigen

print(df_ap02smartphones['price_chf'].median())                                 #Median als einfache Zahl ausgeben: 849.0

print(f"Der Median ist {df_ap02smartphones['price_chf'].median()} CHF")         #Median mit erklärendem Text ausgeben

#### 4. Grösste und kleinste Werte finden

| Befehl | Erklärung |
|---|---|
| `df.nlargest(1, 'price')` | Vollständigen Datensatz mit dem höchsten Preis anzeigen |
| `df.nlargest(10, 'price')` | Die zehn Datensätze mit den höchsten Preisen anzeigen |
| `df.nsmallest(10, 'price')` | Die zehn Datensätze mit den niedrigsten Preisen anzeigen |
| `df.sort_values(by='price', ascending=False)` | Gesamten DataFrame nach Preis absteigend sortieren |
| `df.sort_values(by='price', ascending=True)` | Gesamten DataFrame nach Preis aufsteigend sortieren |
| `df.sort_values(by='price', ascending=False).head(1)` | Den teuersten Datensatz durch Sortierung ermitteln |

**Unterschied:**
- **`max()` / `min()`:** Geben nur den grössten bzw. kleinsten Wert zurück
- **`nlargest()` / `nsmallest()`:** Geben vollständige Datensätze mit den grössten bzw. kleinsten Werten zurück
- **`sort_values()`:** Sortiert den gesamten DataFrame nach einer oder mehreren Spalten
- **`head(n)`:** Begrenzt die Ausgabe auf die ersten `n` Datensätze

In [ ]:
display(df_ap02smartphones.nlargest(3, 'price_chf'))                                    #Die 3 teuersten Smartphones anzeigen

print(f"Das billigste Smartphone:\n{df_ap02smartphones.nsmallest(1, 'price_chf')}")     #Das teuerste Smartphone mit erklärendem Text anzeigen

display(df_ap02smartphones.sort_values(by='price_chf', ascending=False))                #Alle Smartphones nach Preis absteigend sortiert anzeigen

display(df_ap02smartphones.sort_values(by='price_chf', ascending=False).head(1))        #Das teuerste Smartphone anzeigen

#### 5. Kategorien und Häufigkeiten untersuchen

| Befehl | Erklärung |
|---|---|
| `df['brand'].unique()` | Alle unterschiedlichen vorhandenen Kategorien inkl. eines allfälligen fehlenden Werts anzeigen |
| `df['brand'].nunique()` | Anzahl unterschiedlicher Kategorien ohne fehlende Werte ermitteln |
| `df['brand'].value_counts()` | Häufigkeit jeder Kategorie ermitteln; standardmässig absteigend sortiert |
| `df['brand'].value_counts(normalize=True)` | Relative Häufigkeit jeder Kategorie berechnen (Anteile zwischen 0 und 1) |
| `df['brand'].value_counts().head(10)` | Die zehn häufigsten Kategorien anzeigen |

**Unterschied:**
- **`unique()`:** Welche unterschiedlichen Werte existieren?
- **`nunique()`:** Wie viele unterschiedliche Werte existieren?
- **`value_counts()`:** Wie häufig kommt jeder Wert vor?

In [ ]:
display(df_ap02smartphones['brand'].unique())                       # Alle unterschiedlichen Marken anzeigen, inklusive allfälliger fehlender Werte

display(df_ap02smartphones['brand'].value_counts())                 # Anzahl Smartphones pro Marke anzeigen, häufigste zuerst

display(df_ap02smartphones['brand'].value_counts(normalize=True))   # Anteil jeder Marke anzeigen: 0.25 entspricht 25 %

display(df_ap02smartphones['brand'].value_counts().head(10))        # Die 10 häufigsten Marken mit ihrer Anzahl anzeigen

#### 6. Duplikate erkennen

| Befehl | Erklärung |
|---|---|
| `df.duplicated()` | Prüft, welche Zeilen Duplikate früherer Zeilen sind |
| `df.duplicated().sum()` | Anzahl vollständig duplizierter Zeilen zählen |
| `df[df.duplicated()]` | Duplizierte Zeilen anzeigen |
| `df.duplicated(subset=['product_id']).sum()` | Duplikate anhand einer bestimmten Spalte prüfen |
| `df[df.duplicated(subset=['price_raw'], keep=False)]` | Alle Zeilen mit mehrfach vorkommendem Preis anzeigen, inklusive erstem Vorkommen |

**Wichtig:** `duplicated()` vergleicht standardmässig alle Spalten. Nur wenn sämtliche Werte einer Zeile mit einer früheren Zeile übereinstimmen, gilt sie als Duplikat. Eine gleiche Marke allein genügt nicht; eine unterschiedliche `product_id` macht die Zeilen bereits verschieden. Das erste Vorkommen gilt als Original (`False`), weitere identische Zeilen als Duplikate (`True`). Mit `subset` lässt sich der Vergleich auf bestimmte Spalten beschränken

In [ ]:
df_ap02smartphonesraw.duplicated()                                              #Alle Spalten vergleichen

In [ ]:
print(df_ap02smartphonesraw.duplicated().sum())                                 #Anzahl vollständig duplizierter Zeilen ausgeben

display(df_ap02smartphonesraw[df_ap02smartphonesraw.duplicated()])              #Vollständig duplizierte Zeilen anzeigen

print(df_ap02smartphonesraw.duplicated(subset=['price_raw']).sum())             #Anzahl mehrfach vorkommender Preise zählen

display(df_ap02smartphonesraw[df_ap02smartphonesraw.duplicated(subset=['price_raw'], keep=False)]) 
                                                                                #Alle Zeilen mit mehrfach vorkommendem Preis anzeigen, inkl. erstem Vorkommen

#### 7. DataFrame gezielt filtern

| Befehl | Erklärung |
|---|---|
| `df[['brand', 'price_chf']]` | Nur ausgewählte Spalten anzeigen |
| `df[df['price_chf'] > 1000]` | Preise über 1000 auswählen |
| `df[df['brand'] == 'Samsung']` | Nur Samsung auswählen |
| `df[df['brand'] != 'Samsung']` | Samsung ausschliessen |
| `df[(df['brand'] == 'Samsung') & (df['price_chf'] > 1000)]` | UND: Samsung mit einem Preis über 1000 auswählen |
| `df[(df['brand'] == 'Samsung') \| (df['brand'] == 'Apple')]` | ODER: Samsung oder Apple auswählen |
| `df[df['brand'].isin(['Samsung', 'Apple'])]` | Marken aus einer Liste auswählen |
| `df[~df['brand'].isin(['Samsung', 'Apple'])]` | Marken aus einer Liste ausschliessen |
| `df[df['price_chf'].between(500, 1000)]` | Preise zwischen 500 und 1000 auswählen, inklusive Grenzen |
| `df[df['model'].str.contains('pro', case=False, na=False)]` | Modelle auswählen, deren Name „pro“ enthält; Gross-/Kleinschreibung ignorieren |
| `df[df['price_chf'].isna()]` | Zeilen mit fehlendem Preis auswählen |
| `df[df['price_chf'].notna()]` | Zeilen mit vorhandenem Preis auswählen |
| `df.loc[df['price_chf'] > 1000, ['brand', 'price_chf']]` | Zeilen filtern und nur ausgewählte Spalten anzeigen |
| `df.iloc[:5, :3]` | Erste fünf Zeilen und erste drei Spalten nach Position auswählen |

**Wichtig:** `==` bedeutet gleich, `!=` ungleich, `>` grösser, `<` kleiner, `>=` grösser oder gleich und `<=` kleiner oder gleich. Mehrere Bedingungen jeweils einklammern und mit `&` (UND) oder `|` (ODER) verbinden; `~` kehrt eine Bedingung um. Die Auswahl verändert den ursprünglichen DataFrame nicht

In [ ]:
display(df_ap02smartphones[['brand', 'price_chf']])                             #Nur Marke und Preis anzeigen

display(df_ap02smartphones[df_ap02smartphones['price_chf'] > 1000])             #Alle Smartphones über 1000 CHF anzeigen

display(df_ap02smartphones[df_ap02smartphones['brand'] == 'Samsung'])           #Nur Smartphones der Marke Samsung anzeigen

display(df_ap02smartphones.loc[df_ap02smartphones['price_chf'] > 1000, ['brand', 'price_chf']])  
                                                                                #Smartphones über 1000 CHF auswählen und nur Marke und Preis anzeigen

In [ ]:
#DATAFRAMES ANALYSIEREN
#Voraussetzung: Daten wurden bereits eingelesen und als Pandas-DataFrame gespeichert
import pandas as pd                                                             #Pandas für die Analyse von DataFrames importieren

df = df_ap02smartphones                                                         #Zu analysierenden DataFrame auswählen


# 1. DATAFRAME ANZEIGEN UND STRUKTUR UNTERSUCHEN
display(df)                                                                     #Gesamten DataFrame tabellarisch anzeigen; grosse Ausgaben werden gekürzt
display(df.head(5))                                                             #Die ersten fünf Datensätze anzeigen
display(df.tail(5))                                                             #Die letzten fünf Datensätze anzeigen
display(df.sample(min(5, len(df)), random_state=42))                            #Bis zu fünf zufällige Datensätze anzeigen
                                                                                #random_state=42: Reproduzierbare Zufallsauswahl sicherstellen

print('Shape:', df.shape)                                                       #Anzahl Zeilen und Spalten als Tupel anzeigen
print('Number of rows:', len(df))                                               #Gesamtanzahl der Datensätze anzeigen
print('Columns:', df.columns.tolist())                                          #Alle Spaltennamen als Liste anzeigen
print('Index:', df.index)                                                       #Zeilenindex des DataFrames anzeigen
print('Data types:\n', df.dtypes)                                               #Datentyp jeder Spalte anzeigen

df.info()                                                                       #Struktur, Datentypen, vorhandene Werte und Speicherverbrauch anzeigen

display(df.select_dtypes(include='number').head())                              #Nur numerische Spalten auswählen
display(df.select_dtypes(include='object').head())                              #Nur Spalten mit dem Datentyp object auswählen


# 2. ALLE ZEILEN UND SPALTEN ANZEIGEN (OPTIONAL)
#with pd.option_context('display.max_rows', None, 'display.max_columns', None): #Temporär sämtliche Zeilen und Spalten freigeben
#    display(df) #Vollständigen DataFrame ohne Kürzung anzeigen
                 #ACHTUNG: Bei grossen DataFrames sehr umfangreiche Ausgabe!


# 3. MISSING VALUES ANALYSIEREN
print('Missing values per column:\n', df.isna().sum())                          #Fehlende Werte pro Spalte zählen
                                                                                #isna(): Fehlende Werte als True markieren
                                                                                #sum(): True-Werte pro Spalte aufsummieren

print('Total missing values:', df.isna().sum().sum())                           #Gesamtanzahl fehlender Werte ermitteln

print('Missing values in %:\n', (df.isna().mean() * 100).round(2))              #Prozentualen Anteil fehlender Werte pro Spalte berechnen
                                                                                #mean(): Anteil der True-Werte berechnen
                                                                                #* 100: In Prozent umrechnen
                                                                                #round(2): Auf zwei Dezimalstellen runden

print('Non-missing values:\n', df.notna().sum())                                #Anzahl vorhandener Werte pro Spalte ermitteln

print('Rows with missing values:', df.isna().any(axis=1).sum())                 #Anzahl Zeilen mit mindestens einem fehlenden Wert ermitteln
                                                                                #any(axis=1): Mindestens ein fehlender Wert innerhalb einer Zeile

display(df[df.isna().any(axis=1)].head(20))                                     #Die ersten 20 Datensätze mit mindestens einem fehlenden Wert anzeigen


# 4. STATISTISCHE KENNZAHLEN ANALYSIEREN
display(df.describe())                                                          #Statistische Kennzahlen der numerischen Spalten anzeigen
                                                                                #count, mean, std, min, 25%, 50%, 75%, max

display(df.describe(include='all'))                                             #Statistische Übersicht über numerische und nicht numerische Spalten anzeigen


# 5. DUPLIKATE ANALYSIEREN
print('Number of duplicates:', df.duplicated().sum())                           #Anzahl vollständig duplizierter Zeilen ermitteln
display(df[df.duplicated()].head(20))                                           #Die ersten 20 vollständig duplizierten Datensätze anzeigen


# 6. EINZIGARTIGE WERTE PRO SPALTE ANALYSIEREN
print('Unique values per column:\n', df.nunique())                              #Anzahl unterschiedlicher Werte pro Spalte ermitteln
                                                                                #nunique(): Fehlende Werte standardmässig nicht mitzählen


# 7. GRÖSSTE UND KLEINSTE WERTE ANALYSIEREN
if 'price' in df.columns and pd.api.types.is_numeric_dtype(df['price']):        #Prüfen, ob die numerische Preisspalte existiert

    print('Maximum price:', df['price'].max())                                  #Höchsten Preis ermitteln
    print('Minimum price:', df['price'].min())                                  #Niedrigsten Preis ermitteln
    print('Mean price:', df['price'].mean())                                    #Durchschnittlichen Preis berechnen
    print('Median price:', df['price'].median())                                #Median des Preises berechnen

    display(df.nlargest(1, 'price'))                                            #Vollständigen Datensatz mit dem höchsten Preis anzeigen
    display(df.nlargest(10, 'price'))                                           #Die zehn teuersten Datensätze anzeigen
    display(df.nsmallest(10, 'price'))                                          #Die zehn günstigsten Datensätze anzeigen
    display(df.sort_values(by='price', ascending=False).head(10))               #Nach Preis absteigend sortieren und die ersten zehn Datensätze anzeigen
                                                                                #ascending=False: Höchste Werte zuerst
    display(df[df['price'] > 1000].head(20))                                    #Die ersten 20 Datensätze mit einem Preis über 1000 anzeigen


# 8. KATEGORIEN UND HÄUFIGKEITEN ANALYSIEREN
if 'brand' in df.columns:                                                       #Prüfen, ob die Kategoriespalte brand existiert

    print('Unique brands:', df['brand'].unique())                               #Alle unterschiedlichen Marken anzeigen
    print('Number of brands:', df['brand'].nunique())                           #Anzahl unterschiedlicher Marken ermitteln
    print('Brand frequencies:\n', df['brand'].value_counts())                   #Häufigkeit jeder Marke ermitteln
    print('Relative frequencies:\n', df['brand'].value_counts(normalize=True))  #Relative Häufigkeit jeder Marke berechnen
    print('Top 10 brands:\n', df['brand'].value_counts().head(10))              #Die zehn häufigsten Marken anzeigen

    display(df[df['brand'] == 'Samsung'].head(20))                              #Die ersten 20 Samsung-Datensätze anzeigen


# 9. DUPLIKATE ANHAND EINER BESTIMMTEN SPALTE PRÜFEN
if 'product_id' in df.columns:                                                  #Prüfen, ob eine Produkt-ID vorhanden ist

    print('Duplicate product IDs:', df.duplicated(subset=['product_id']).sum()) #Anzahl wiederholter Produkt-IDs ermitteln

# DataFrames analysieren – Textsuche und numerische Werte filtern

**Erkenntnis:** Mit Pandas können DataFrames gezielt nach Texten, Zahlen, Wertebereichen und kombinierten Bedingungen durchsucht werden. Dabei werden nur die Datensätze angezeigt, die bestimmte Suchkriterien erfüllen. Dadurch können auch sehr grosse Datensätze effizient analysiert werden

**Zweck:** Auffällige Werte finden, bestimmte Produkte oder Kategorien identifizieren, Preise vergleichen und Datensätze für weitere Analysen auswählen

**Wichtige Regeln für die Prüfung:**
- Textwerte werden in Anführungszeichen geschrieben: `'Samsung'`
- Numerische Werte werden ohne Anführungszeichen geschrieben: `1000`
- Für kombinierte Bedingungen `&`, `|` und `~` verwenden, nicht die Python-Operatoren `and`, `or` und `not`
- Bei kombinierten Pandas-Filtern jede Bedingung einzeln einklammern
- Vor numerischen Vergleichen sicherstellen, dass die Spalte numerische Werte enthält
- Fehlende Werte können Filterergebnisse beeinflussen und sollten separat untersucht werden
- Bei grossen DataFrames Ergebnisse mit `.head(n)` begrenzen


#### 1. Textsuche – Textwerte und Zeichenfolgen finden

| Befehl | Erklärung |
|---|---|
| `df[df['price_raw'] == 'Preis auf Anfrage']` | Alle Datensätze anzeigen, deren Preistext exakt «Preis auf Anfrage» lautet |
| `df[df['price_raw'] != 'Preis auf Anfrage']` | Alle Datensätze anzeigen, deren Preistext nicht exakt «Preis auf Anfrage» lautet |
| `df[df['price_raw'].str.contains('Anfrage', case=False, na=False)]` | Alle Datensätze anzeigen, deren Preistext das Wort «Anfrage» enthält |
| `df[df['price_raw'].str.contains('Preis auf Anfrage', case=False, na=False, regex=False)]` | Einen bestimmten Text unabhängig von der Gross-/Kleinschreibung suchen und wörtlich interpretieren |
| `df[df['brand'].str.startswith('Sam', na=False)]` | Alle Datensätze anzeigen, deren Markenname mit «Sam» beginnt |
| `df[df['brand'].str.endswith('ung', na=False)]` | Alle Datensätze anzeigen, deren Markenname auf «ung» endet |
| `df[df['brand'].isin(['Samsung', 'Apple'])]` | Datensätze anzeigen, deren Marke Samsung oder Apple ist |
| `df[df['brand'].str.contains('Samsung', case=False, na=False)]` | Alle Datensätze anzeigen, deren Markenname «Samsung» enthält |
| `df['brand'].value_counts()` | Häufigkeit der einzelnen Marken ermitteln |
| `df['brand'].unique()` | Alle unterschiedlichen Marken anzeigen |
| `df['brand'].nunique()` | Anzahl unterschiedlicher Marken ermitteln |

**Wichtige Funktionen und Parameter:**
- **`==`:** Exakter Vergleich eines Werts (Gross-/Kleinschreibung beachten)
- **`!=`:** Alle Werte ausser dem angegebenen Wert auswählen
- **`.str.contains('Text')`:** Prüft, ob eine bestimmte Zeichenfolge innerhalb eines Textwerts vorkommt
- **`case=False`:** Ignoriert die Gross-/Kleinschreibung bei `str.contains()`
- **`na=False`:** Behandelt fehlende Werte als Nicht-Treffer
- **`regex=False`:** Interpretiert den Suchtext wörtlich statt als regulären Ausdruck
- **`.str.startswith('Text')`:** Sucht Werte, die mit einem bestimmten Text beginnen
- **`.str.endswith('Text')`:** Sucht Werte, die mit einem bestimmten Text enden
- **`.isin([...])`:** Prüft, ob ein Wert in einer Liste vorgegebener Werte enthalten ist
- **`.astype('string')`:** Konvertiert eine Spalte in den Pandas-String-Datentyp, damit Textoperationen auch bei gemischten Ausgangsdaten möglich sind
- **`.value_counts()`:** Zählt die Häufigkeit einzelner Werte
- **`.unique()`:** Gibt die unterschiedlichen Werte zurück
- **`.nunique()`:** Zählt die unterschiedlichen Werte

**Textsuche über den gesamten DataFrame:**
- Mit `df.astype('string')` lassen sich alle Spalten als Text betrachten
- Mit `.apply()` kann jede Spalte nach einer Zeichenfolge durchsucht werden
- Mit `.any(axis=1)` werden jene Zeilen identifiziert, in denen mindestens eine Spalte den Suchtext enthält

**Wichtig:**
- `==` findet nur exakte Übereinstimmungen, während `str.contains()` auch Teiltexte findet
- `str.contains()` unterstützt reguläre Ausdrücke. Für eine gewöhnliche Textsuche empfiehlt sich `regex=False`
- Bei numerischen oder gemischten Spalten vor Textoperationen gegebenenfalls `.astype('string')` verwenden
- Fehlende Werte sollten bei Textsuchen mit `na=False` berücksichtigt werden
- Die Suche über sämtliche Spalten kann bei grossen DataFrames aufwendig sein

In [ ]:
#Denke daran head(2)) bzw. [:2] rauszulöschen. Habe sie hier nur drin, um den Output zu beschränken

#Exakten Textwert suchen
#Alle Datensätze anzeigen, deren Preistext exakt 'Preis auf Anfrage' lautet
#==: Exakte Übereinstimmung inklusive Gross-/Kleinschreibung
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_raw'] == 'Preis auf Anfrage'])

#Bestimmten Textwert ausschliessen
#Alle Datensätze anzeigen (limitiert auf 5), deren Preistext nicht exakt 'Preis auf Anfrage' lautet
#!=: Ungleich-Vergleich durchführen
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_raw'] != 'Preis auf Anfrage'].head(2))

#Nach einem Text innerhalb einer Spalte suchen
#astype('string'): Spaltenwerte als Text behandeln
#str.contains(): Text innerhalb eines Werts suchen
#case=False: Gross-/Kleinschreibung ignorieren
#na=False: Fehlende Werte als Nicht-Treffer behandeln
#regex=False: Suchtext wörtlich interpretieren
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_raw'].astype('string').str.contains('Preis auf Anfrage', case=False, na=False, regex=False)])

#Nach einem Teilwort suchen
#Alle Datensätze anzeigen, deren Preistext 'Anfrage' enthält
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_raw'].astype('string').str.contains('Anfrage', case=False, na=False, regex=False)])

#Text suchen, der mit einer bestimmten Zeichenfolge beginnt
#Marken suchen, deren Name mit 'Sam' beginnt
#str.startswith(): Anfang einer Zeichenfolge überprüfen
display(df_ap02smartphonesraw[df_ap02smartphonesraw['brand'].astype('string').str.startswith('Sam', na=False)].head(2))

#Text suchen, der mit einer bestimmten Zeichenfolge endet
#Marken suchen, deren Name auf 'ung' endet
#str.endswith(): Ende einer Zeichenfolge überprüfen
display(df_ap02smartphonesraw[df_ap02smartphonesraw['brand'].astype('string').str.endswith('ung', na=False)].head(2))

#Mehrere Textwerte gleichzeitig suchen
#Alle Datensätze der Marken Samsung oder Apple anzeigen
#isin(): Prüfen, ob ein Wert in der angegebenen Liste enthalten ist
display(df_ap02smartphonesraw[df_ap02smartphonesraw['brand'].isin(['Samsung', 'Apple'])].head(2))

#Alle Datensätze der Marke Samsung anzeigen
display(df[df['brand'] == 'Samsung'].head(2))

#Alle unterschiedlichen Textwerte ermitteln
#Alle vorhandenen Marken anzeigen
#unique(): Gibt jeden unterschiedlichen Wert nur einmal zurück
print(df_ap02smartphonesraw['brand'].unique()[:2])                              #unique() liefert ein Array; deshalb [:2] statt .head(2)
#Anzahl unterschiedlicher Textwerte ermitteln
#Anzahl unterschiedlicher Marken ermitteln
#nunique(): Fehlende Werte standardmässig nicht mitzählen
print(df_ap02smartphonesraw['brand'].nunique())

#Häufigkeiten der Textwerte ermitteln
#Anzahl Datensätze pro Marke anzeigen
#value_counts(): Häufigkeiten standardmässig absteigend sortieren
print(df_ap02smartphonesraw['brand'].value_counts())

#Die zehn häufigsten Textwerte (Marken) anzeigen
print(df_ap02smartphonesraw['brand'].value_counts().head(10))       

#Alle Spalten nach einem bestimmten Text durchsuchen
#astype('string'): Sämtliche Spalten als Text behandeln
#apply(): Suchfunktion auf jede Spalte anwenden
#lambda: Funktion für jede einzelne Spalte definieren
#any(axis=1): True, wenn mindestens eine Spalte pro Zeile den Suchtext enthält
#Alle Datensätze anzeigen, in denen der Suchtext irgendwo vorkommt
treffer = df_ap02smartphonesraw.astype('string').apply(
    lambda spalte: spalte.str.contains('Preis auf Anfrage', case=False, na=False, regex=False)
).any(axis=1)
display(df_ap02smartphonesraw[treffer])

#### 2. Numerische Werte – Zahlen und Wertebereiche finden

| Befehl | Erklärung |
|---|---|
| `df[df['price'] == 999]` | Alle Datensätze mit dem exakten Preis 999 anzeigen. |
| `df[df['price'] != 999]` | Alle Datensätze ausser denen mit dem Preis 999 anzeigen. |
| `df[df['price'] > 1000]` | Alle Datensätze mit einem Preis über 1000 anzeigen. |
| `df[df['price'] >= 1000]` | Alle Datensätze mit einem Preis von mindestens 1000 anzeigen. |
| `df[df['price'] < 500]` | Alle Datensätze mit einem Preis unter 500 anzeigen. |
| `df[df['price'] <= 500]` | Alle Datensätze mit einem Preis von höchstens 500 anzeigen. |
| `df[df['price'].between(500, 1000)]` | Alle Datensätze mit Preisen zwischen 500 und 1000 anzeigen, inklusive Grenzwerte. |
| `df[df['price'].isin([499, 799, 999])]` | Alle Datensätze anzeigen, deren Preis einem der angegebenen Werte entspricht. |
| `df[(df['price'] > 500) & (df['price'] < 1000)]` | Preise zwischen 500 und 1000 suchen; beide Bedingungen müssen erfüllt sein. |
| `df[(df['price'] < 500) \| (df['price'] > 1000)]` | Preise unter 500 oder über 1000 suchen; mindestens eine Bedingung muss erfüllt sein. |
| `df[~df['price'].between(500, 1000)]` | Alle Datensätze ausserhalb des angegebenen Preisintervalls anzeigen. |
| `df[df['price'].notna()]` | Datensätze mit vorhandenem Preis anzeigen. |
| `df[df['price'].isna()]` | Datensätze mit fehlendem Preis anzeigen. |
| `df.loc[df['price'] > 1000, ['brand', 'price']]` | Datensätze über 1000 filtern und nur Marke und Preis anzeigen. |

**Vergleichsoperatoren:**
- **`==`:** Gleich
- **`!=`:** Ungleich
- **`>`:** Grösser als
- **`>=`:** Grösser oder gleich
- **`<`:** Kleiner als
- **`<=`:** Kleiner oder gleich
- **`&`:** Logisches UND – beide Bedingungen müssen erfüllt sein.
- **`|`:** Logisches ODER – mindestens eine Bedingung muss erfüllt sein.
- **`~`:** Logisches NICHT – eine boolesche Bedingung umkehren.

**Weitere wichtige Methoden:**
- **`.between(min, max)`:** Prüft, ob ein Wert innerhalb eines Intervalls liegt; standardmässig inklusive beider Grenzen.
- **`.isin([wert1, wert2])`:** Sucht mehrere bestimmte Zahlen gleichzeitig.
- **`.loc[bedingung, spalten]`:** Filtert Zeilen und wählt gleichzeitig bestimmte Spalten aus.
- **`.isna()`:** Erkennt fehlende Werte.
- **`.notna()`:** Erkennt vorhandene Werte

In [ ]:
#Exakten numerischen Wert suchen
#Alle Datensätze mit dem exakten Preis 999 anzeigen
#==: Exakten numerischen Vergleich durchführen
display(df_ap02smartphones[df_ap02smartphones['price_chf'] == 999])

#Bestimmten numerischen Wert ausschliessen
#Alle Datensätze anzeigen, deren Preis nicht 999 beträgt
#!=: Ungleich-Vergleich durchführen
display(df_ap02smartphones[df_ap02smartphones['price_chf'] != 999])

#Grösser als einen bestimmten Wert
#Alle Datensätze mit einem Preis über 1000 anzeigen
#>: Grösser als, ohne Grenzwert
display(df_ap02smartphones[df_ap02smartphones['price_chf'] > 1000])

#Grösser oder gleich einem bestimmten Wert
#Alle Datensätze mit einem Preis von mindestens 1000 anzeigen
#>=: Grösser oder gleich, inklusive Grenzwert
display(df_ap02smartphones[df_ap02smartphones['price_chf'] >= 1000]) 

#Kleiner als einen bestimmten Wert
#Alle Datensätze mit einem Preis unter 500 anzeigen
#<: Kleiner als, ohne Grenzwert
display(df_ap02smartphones[df_ap02smartphones['price_chf'] < 500])

#Kleiner oder gleich einem bestimmten Wert
#Alle Datensätze mit einem Preis von höchstens 500 anzeigen
#<=: Kleiner oder gleich, inklusive Grenzwert
display(df_ap02smartphones[df_ap02smartphones['price_chf'] <= 500]) 

#Numerischen Wertebereich durchsuchen
#Alle Datensätze mit Preisen zwischen 500 und 1000 anzeigen
#between(): Prüfen, ob Werte innerhalb eines Intervalls liegen
#Standardmässig beide Grenzwerte eingeschlossen
display(df_ap02smartphones[df_ap02smartphones['price_chf'].between(500, 1000)]) 

#Mehrere bestimmte Zahlen gleichzeitig suchen
#Alle Datensätze mit einem der angegebenen Preise anzeigen
#isin(): Prüfen, ob ein Wert in einer Liste enthalten ist
display(df_ap02smartphones[df_ap02smartphones['price_chf'].isin([499, 799, 999])])

#Mehrere Bedingungen mit UND kombinieren
#Preise zwischen 500 und 1000 anzeigen, ohne Grenzwerte
#&: Beide Bedingungen müssen erfüllt sein
#(): Jede Bedingung einzeln einklammern
display(df_ap02smartphones[(df_ap02smartphones['price_chf'] > 500) & (df_ap02smartphones['price_chf'] < 1000)])

#Mehrere Bedingungen mit ODER kombinieren
#Preise unter 500 oder über 1000 anzeigen
#|: Mindestens eine Bedingung muss erfüllt sein
display(df_ap02smartphones[(df_ap02smartphones['price_chf'] < 500) | (df_ap02smartphones['price_chf'] > 1000)])

#Eine Bedingung umkehren
#Alle Datensätze ausserhalb des Preisintervalls anzeigen
#~: Boolesche Bedingung umkehren
#ACHTUNG: Fehlende Werte können dabei ebenfalls ausgewählt werden
display(df_ap02smartphones[~df_ap02smartphones['price_chf'].between(500, 1000)]) 

#Nur Datensätze mit vorhandenem Preis anzeigen
#Datensätze mit nicht fehlendem Preis anzeigen
#notna(): Vorhandene Werte erkennen
display(df_ap02smartphones[df_ap02smartphones['price_chf'].notna()]) 

#Nur Datensätze mit fehlendem Preis anzeigen
#Datensätze mit fehlendem Preis anzeigen
#isna(): Fehlende Werte wie NaN erkennen
display(df_ap02smartphones[df_ap02smartphones['price_chf'].isna()]) 

#Numerischen Filter anwenden und bestimmte Spalten auswählen
#Nur Marke und Preis von Smartphones über 1000 anzeigen
#loc[Zeilenbedingung, Spaltenliste]: Zeilen und Spalten gezielt auswählen
display(df_ap02smartphones.loc[df_ap02smartphones['price_chf'] > 1000, ['brand', 'price_chf']])

#### 3. Grösste und kleinste Werte ermitteln

| Befehl | Erklärung |
|---|---|
| `df['price'].max()` | Höchsten Preis als einzelnen Wert zurückgeben |
| `df['price'].min()` | Niedrigsten Preis als einzelnen Wert zurückgeben |
| `df['price'].mean()` | Durchschnittlichen Preis berechnen |
| `df['price'].median()` | Median des Preises berechnen |
| `df.nlargest(1, 'price')` | Vollständigen Datensatz mit dem höchsten Preis anzeigen |
| `df.nlargest(10, 'price')` | Die zehn teuersten Datensätze anzeigen |
| `df.nsmallest(10, 'price')` | Die zehn günstigsten Datensätze anzeigen |
| `df.sort_values(by='price', ascending=False)` | Gesamten DataFrame nach Preis absteigend sortieren |
| `df.sort_values(by='price', ascending=True)` | Gesamten DataFrame nach Preis aufsteigend sortieren |
| `df.sort_values(by='price', ascending=False).head(1)` | Teuersten Datensatz über eine absteigende Sortierung ermitteln |

**Unterschied:**
- **`max()` / `min()`:** Liefern einzelne numerische Werte
- **`nlargest()` / `nsmallest()`:** Liefern vollständige Datensätze mit den grössten bzw. kleinsten Werten
- **`sort_values()`:** Sortiert den DataFrame nach bestimmten Spalten
- **`head(n)`:** Begrenzt die Ausgabe auf die ersten `n` Zeilen

In [ ]:
#Höchsten numerischen Wert ermitteln
#Maximalen Preis als einzelnen Wert zurückgeben
print(df_ap02smartphones['price_chf'].max())

#Niedrigsten numerischen Wert ermitteln
#Minimalen Preis als einzelnen Wert zurückgeben
print(df_ap02smartphones['price_chf'].min())

#Durchschnitt berechnen
#Arithmetischen Mittelwert aller vorhandenen Preise berechnen
print(df_ap02smartphones['price_chf'].mean())

#Median berechnen
#Mittleren Preiswert berechnen
print(df_ap02smartphones['price_chf'].median())

#Teuersten Datensatz anzeigen
#Vollständigen Datensatz mit dem höchsten Preis anzeigen
#nlargest(1): Den grössten Wert inklusive der zugehörigen Zeile zurückgeben
display(df_ap02smartphones.nlargest(1, 'price_chf'))

#Die zehn teuersten Datensätze anzeigen
#Die zehn Smartphones mit den höchsten Preisen anzeigen
display(df_ap02smartphones.nlargest(10, 'price_chf'))

#Die zehn günstigsten Datensätze anzeigen
#Die zehn Smartphones mit den niedrigsten Preisen anzeigen
display(df_ap02smartphones.nsmallest(10, 'price_chf'))

#Nach Preis absteigend sortieren
#Die zehn teuersten Datensätze durch Sortierung anzeigen
#ascending=False: Höchste Werte zuerst
#head(10): Nur die ersten zehn Datensätze anzeigen
display(df_ap02smartphones.sort_values(by='price_chf', ascending=False).head(10))

#Nach Preis aufsteigend sortieren
#Die zehn günstigsten Datensätze durch Sortierung anzeigen
#ascending=True: Niedrigste Werte zuerst
display(df_ap02smartphones.sort_values(by='price_chf', ascending=True).head(10))


#### 4. Textsuche und numerische Bedingungen kombinieren

Bsp.: Alle Samsung-Smartphones mit einem Preis über 1000 suchen

`df[(df['brand'] == 'Samsung') & (df['price'] > 1000)]`

**Interpretation:**
- Die erste Bedingung sucht nach Samsung
- Die zweite Bedingung sucht Preise über 1000
- Mit `&` müssen beide Bedingungen gleichzeitig erfüllt sein
- Jede einzelne Bedingung muss in Klammern stehen

In [ ]:
#Samsung-Smartphones mit einem Preis über 1000 suchen
#Nur Samsung-Smartphones mit einem Preis über 1000 anzeigen
#&: Beide Bedingungen müssen gleichzeitig erfüllt sein
display(df_ap02smartphones[(df_ap02smartphones['brand'] == 'Samsung') & (df_ap02smartphones['price_chf'] > 1000)])

#Samsung- oder Apple-Smartphones mit Preisen zwischen 500 und 1000 suchen
#Nur Samsung- oder Apple-Smartphones innerhalb der angegebenen Preisspanne anzeigen
#isin(): Mehrere Marken berücksichtigen
#between(): Numerischen Wertebereich einschränken
#&: Beide Bedingungen kombinieren
display(df_ap02smartphones[
    (df_ap02smartphones['brand'].isin(['Samsung', 'Apple'])) &
    (df_ap02smartphones['price_chf'].between(500, 1000))
])

#### 5. Numerische Werte, die als Text gespeichert wurden

**Problem:** Beim Einlesen von CSV-, Excel- oder HTML-Daten können Preise als Strings gespeichert werden, bspw. `'999'`, `'1299.50'` oder `'Preis auf Anfrage'`

**Lösung:**
- **`pd.to_numeric(df['price_raw'], errors='coerce')`:** Konvertiert numerische Texte in numerische Werte
- **`errors='coerce'`:** Nicht konvertierbare Werte werden zu `NaN`
- Dadurch können anschliessend numerische Filter wie `>`, `<` oder `between()` angewendet werden

**Achtung:** Werte wie `'CHF 1'299'` oder `'1,299 CHF'` müssen vorher passend bereinigt werden. `pd.to_numeric()` erkennt solche Formate nicht automatisch

In [ ]:
#Textwerte in numerische Werte umwandeln
#Numerische Preisangaben in Zahlen umwandeln
#Vorher CHF, Tausenderapostrophe und .– entfernen: CHF 1'249.– wird zu 1249
#errors='coerce': Nicht konvertierbare Werte werden zu NaN
#Beispiel: '999' wird zu 999
#Beispiel: 'Preis auf Anfrage' wird zu NaN
df_ap02smartphonesraw['price_numeric'] = pd.to_numeric(
    df_ap02smartphonesraw['price_raw']
        .str.replace('CHF', '', regex=False)
        .str.replace("'", '', regex=False)
        .str.replace('.–', '', regex=False)
        .str.strip(),
    errors='coerce'
)

#Nach der Konvertierung numerische Filter anwenden
#Alle Datensätze mit einem konvertierten Preis über 1000 anzeigen
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_numeric'] > 1000])

#Nicht konvertierbare oder fehlende Preisangaben anzeigen
#Alle Datensätze anzeigen, bei denen die Konvertierung keinen Zahlenwert ergeben hat
display(df_ap02smartphonesraw[df_ap02smartphonesraw['price_numeric'].isna()])