# AP02 - Spick Data Preparation (DP)

# UNBEDINGT SCHAUEN DASS ALLE METHODEN AUS FOLIEN V4 DRIN SIND!

### Advanced Data Preparation Methods
#### ▪ Data Cleansing
#### ▪ String Manipulation
#### ▪ Date Formatting
#### ▪ Data Discretization
#### ▪ One-Hot Encoding
#### ▪ Data Scaling
#### ▪ Data Standardization
#### ▪ Data Transformation (Statistics)

## Libraries & Settings

In [1]:
# Libraries
import os
import re
import time
import fnmatch
import numpy as np
import pandas as pd
import seaborn as sns
from datetime import datetime
import matplotlib.pyplot as plt

# Ignore warnings
import warnings
warnings.filterwarnings("ignore")

# Get current working directory
print(os.getcwd())

/workspaces/DS_HS2026_LNW/DS_HS2026_LNW_I_Examples/AP02/AP02 V4 Data Preparation

## Importing Data
#### df_dpspick_apartments, df_dpspick_autoscout und df_dpspick_smartphone

In [2]:
#Falls du Dateien nicht findest (Speicherorte), diesen Code ausführen und den Output anschauen!
import os                               #Zugriff auf Ordnerinformationen
print("Arbeitsordner:", os.getcwd())    #Ordner anzeigen, von dem der relative Dateipfad ausgeht
print("Dateien:", os.listdir())         #Dateinamen im Arbeitsordner anzeigen

Arbeitsordner: /workspaces/DS_HS2026_LNW/DS_HS2026_LNW_I_Examples/AP02/AP02 V4 Data Preparation
Dateien: ['apartments_data_zuerich.csv', 'apartments_data_geocoded.csv', 'AP02 V4.1 DP Aufgaben.ipynb', 'autoscout24_data.csv', 'autoscout24_data_geocoded.csv', 'AP02 V4 DP Spick.ipynb', 'municipality_data.xlsx', 'AP02 V4.2 DP Aufgaben.ipynb', 'AP02 V4.1 DP Lösung.ipynb', 'AP02 V4.2 DP Lösung.ipynb']

In [13]:
# Read the data to a pandas data frame
df_dpspick_apartments = pd.read_csv('./apartments_data_zuerich.csv',            #CSV aus dem Arbeitsordner einlesen und als df speichern
                 sep=',',                                                       #Komma als Trennzeichen verwenden
                 encoding='utf-8')                                              #Datei mit UTF-8-Zeichenkodierung lesen

# Show first records of data frame
df_dpspick_apartments.head()                                                    #Erste fünf Zeilen der Tabelle anzeigen


#Dateien einlesen: car data
# Import data from csv to pandas dataframe named 'df'
df_dpspick_autoscout = pd.read_csv('./autoscout24_data.csv',                    #CSV aus dem Arbeitsordner einlesen und als df speichern
                 sep=";",                                                       #Komma als Trennzeichen verwenden
                 encoding='utf-8')                                              #Datei mit UTF-8-Zeichenkodierung lesen

# Change the column names to lowercase
df_dpspick_autoscout.columns = df_dpspick_autoscout.columns.str.lower()         #Alle Spaltennamen in Kleinbuchstaben umwandeln

# Display the first 5 rows of the dataframe
df_dpspick_autoscout.head()                                                     #Erste fünf Zeilen der Tabelle anzeigen


#Dateien einlesen: smartphone data
# Import data from csv to pandas dataframe named 'df_clean'
df_dpspick_smartphone = pd.read_csv('../AP02 Mock Exam/smartphones_clean.csv')  #CSV aus dem Arbeitsordner einlesen und als df_clean speichern

# Show dimensions and first rows
print('Number of rows and columns:', df_dpspick_smartphone.shape)               #Anzahl Zeilen und Spalten als (Zeilen, Spalten) anzeigen
df_dpspick_smartphone.head()                                                    #Erste fünf Zeilen der Tabelle anzeigen

Number of rows and columns: (142, 9)

,product_id,brand,model,storage_gb,color,screen_inch,battery_mah,price_chf,availability
0,PM-10001,Xiaomi,Redmi Note 14 Pro 5G,256,Midnight Black,6.67,5110,299.0,Sofort lieferbar
1,PM-10002,OnePlus,OnePlus 13,256,Arctic Dawn,6.82,6000,899.0,Lieferbar in 2–5 Tagen
2,PM-10003,Google,Pixel 10 Pro,512,Obsidian,6.30,4870,1249.0,Sofort lieferbar
3,PM-10004,Samsung,Galaxy A36 5G,128,Awesome Lavender,6.70,5000,339.0,Sofort lieferbar
4,PM-10005,Samsung,Galaxy Z Fold7,1024,Jetblack,8.00,4400,NaN,Vorbestellung

### Anzahl Zeilen und Spalten einer Tabelle anzeigen

Zeigt, wie viele Datensätze und Merkmale die Tabelle enthält
- Zeilen = Datensätze, bspw. einzelne Velos
- Spalten = Merkmale, bspw. Marke, Modell und Preis
- df.shape liefert beide Anzahlen als (Zeilen, Spalten)
- df.shape[0] liefert nur die Zeilenanzahl
- df.shape[1] liefert nur die Spaltenanzahl

In [ ]:
print("Dimension:", df_dpspick_apartments.shape)                                #Anzahl Zeilen und Spalten als (Zeilen, Spalten)
print("Anzahl Zeilen:", df_dpspick_apartments.shape[0])                         #Anzahl Datensätze anzeigen  
print("Anzahl Spalten:", df_dpspick_apartments.shape[1])                        #Anzahl Merkmale anzeigen

#0 und 1 bleiben gleich: Sie wählen die Zeilenanzahl bzw. Spaltenanzahl aus
#Gezählt werden alle vorhandenen Zeilen und Spalten, auch bei fehlenden Werten oder Duplikaten

Dimension: (1008, 7)
Anzahl Zeilen: 1008
Anzahl Spalten: 7

### Vorhandene Spaltennamen anzeigen

Zeigt die exakten Namen aller Spalten einer Tabelle als Liste an; damit kannst du prüfen, welche Spalten vorhanden sind und wie sie geschrieben werden

Gross-/Kleinschreibung beachten: `Price_Raw`, `price_raw` und `price` sind unterschiedliche Spaltennamen
Ein `KeyError` kann bedeuten, dass die angegebene Spalte fehlt oder anders geschrieben ist

In [11]:
print(df_dpspick_autoscout.columns.tolist())            #Vorhandene Spalten von df_autoscout anzeigen

display(df_dpspick_autoscout)                           #Gesamten Dataframe anzeigen

['url_short', 'offer_id', 'scrape_dt', 'type', 'price_raw', 'hp_raw', 'init_regist', 'mileage_raw', 'fuel_type', 'transmission', 'dealer_name', 'dealer_plz', 'dealer_city', 'dealer_street_house_nr', 'dealer_telnr', 'init_regist_my', 'init_regist_month', 'init_regist_year', 'init_regist_dt']

,url_short,offer_id,scrape_dt,type,price_raw,hp_raw,init_regist,mileage_raw,fuel_type,transmission,dealer_name,dealer_plz,dealer_city,dealer_street_house_nr,dealer_telnr,init_regist_my,init_regist_month,init_regist_year,init_regist_dt
0,https://www.autoscout24.ch/7324420,7324420,2020_03_17 07:34:45,AUDI A5 Sportback 3.0 TDI quattro S-tronic (Li...,CHF 22'500.–,245 PS,10.2014,75'000 km,Diesel,Automatisiertes Schaltgetriebe,***confidential***,8488,Turbenthal,Mettlenstrasse 3,***confidential***,10.2014,10.0,2014.0,2014-10
1,https://www.autoscout24.ch/7512768,7512768,2020_03_17 07:34:55,MERCEDES-BENZ SLK 200 7G-Tronic (Cabriolet),CHF 23'749.–,184 PS,6.2013,46'655 km,Benzin,Automat sequentiell,***confidential***,3186,Düdingen,Brugerastrasse 60,***confidential***,6.2013,6.0,2013.0,2013-06
2,https://www.autoscout24.ch/7512034,7512034,2020_03_17 07:35:03,MERCEDES-BENZ C 350 Avantgarde 4Matic 7G-Troni...,CHF 18'500.–,306 PS,6.2011,138'955 km,Benzin,Automat sequentiell,***confidential***,1262,Eysins,1262 Eysins,***confidential***,6.2011,6.0,2011.0,2011-06
3,https://www.autoscout24.ch/7512728,7512728,2020_03_17 07:35:06,MERCEDES-BENZ A 45 AMG 4Matic Speedshift 7G-DC...,CHF 36'000.–,360 PS,8.2015,43'000 km,Benzin,Automatisiertes Schaltgetriebe,***confidential***,4314,Zeiningen,Am Stutz 21,***confidential***,8.2015,8.0,2015.0,2015-08
4,https://www.autoscout24.ch/7490242,7490242,2020_03_17 07:35:16,AUDI A5 Sportback 2.0 TFSI Sport quattro S-tro...,CHF 48'500.–,252 PS,9.2018,43'300 km,Benzin,Automatisiertes Schaltgetriebe,***confidential***,3250,Lyss,3250 Lyss,***confidential***,9.2018,9.0,2018.0,2018-09
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3975,https://www.autoscout24.ch/7137137,7137137,2020_03_17 06:03:15,FERRARI F360 Spider (Cabriolet),CHF 58'400.–,400 PS,2.2002,78'000 km,Benzin,Automatisiertes Schaltgetriebe,***confidential***,8852,Altendorf,8852 Altendorf,***confidential***,2.2002,2.0,2002.0,2002-02
3976,https://www.autoscout24.ch/6758841,6758841,2020_03_17 07:15:07,MERCEDES-BENZ SL 500 560 SL (Cabriolet),CHF 15'900.–,232 PS,1.1987,315'000 km,Benzin,Automatik-Getriebe,***confidential***,9444,DIEPOLDSAU,WERKSTRASSE 10 1,***confidential***,1.1987,1.0,1987.0,1987-01
3977,https://www.autoscout24.ch/7461330,7461330,2020_03_17 07:18:31,MERCEDES-BENZ CL 63 AMG 7G-Tronic (Coupé),CHF 42'000.–,525 PS,8.2007,85'000 km,Benzin,Automat sequentiell,***confidential***,8953,Dietikon,8953 Dietikon,***confidential***,8.2007,8.0,2007.0,2007-08
3978,https://www.autoscout24.ch/7005403,7005403,2020_03_17 07:30:54,BMW 328i Cabrio (Cabriolet),CHF 9'980.–,193 PS,8.1995,188'920 km,Benzin,Schaltgetriebe manuell,***confidential***,2543,Lengnau,Mühleweg 8,***confidential***,8.1995,8.0,1995.0,1995-08
3979,https://www.autoscout24.ch/7200843,7200843,2020_03_17 07:30:57,BMW 328i Cabrio Sport (Cabriolet),CHF 13'500.–,193 PS,4.1999,134'000 km,Benzin,Schaltgetriebe manuell,***confidential***,9016,St. Gallen,Achslenstrasse 22,***confidential***,4.1999,4.0,1999.0,1999-04

## Extract information from raw data using regular expressions (regex)
### Voraussetzung: import re

##### Wichtige Stolpersteine

- `r"(\d+)\s*Zimmer"` findet bei `"3,5 Zimmer"` ebenfalls einen Treffer, allerdings nur `"5"`. Die einfache Ganzzahlvariante prüft nicht, ob davor ein Komma oder Punkt steht. Für gemischte Zahlenformate ist `r"(\d+(?:[.,]\d+)?)\s*Zimmer"` geeigneter
- Dasselbe gilt für `r"(\d+)\s*m²"`: Bei `"49,5 m²"` wird nur `"5"` erfasst; für Dezimalzahlen das erweiterte Zahlenmuster verwenden
- `''.join(re.findall(r"\d+", text))` nur verwenden, wenn der Text genau eine zusammengehörige Zahl enthält. Bei `"75'000 km, 245 PS"` würden sonst Kilometer und PS zu `"75000245"` verschmelzen
- Die Muster prüfen nicht automatisch das vollständige Zahlenformat. Das flexible CHF-Muster kann bei `"CHF 1249.999"` bspw. nur `"1249.99"` erfassen

#### Regex-Muster: Varianten und Bedeutung

| Regex-Muster | Bedeutung |
|---|---|
| `r"(\d+)\s*Zimmer"` | sucht eine ganze Zahl vor „Zimmer“, bspw. `"3 Zimmer"` → `"3"` |
| `r"(\d+,\d+)\s*Zimmer"` | sucht eine Dezimalzahl mit Komma vor „Zimmer“, bspw. `"3,5 Zimmer"` → `"3,5"` |
| `r"(\d+,\d+\|\d+)\s*Zimmer"` | sucht eine Dezimalzahl mit Komma ODER eine ganze Zahl vor „Zimmer“, bspw. `"3,5 Zimmer"` → `"3,5"` oder `"3 Zimmer"` → `"3"` |
| `r"(\d+(?:[.,]\d+)?)\s*Zimmer"` | sucht eine ganze Zahl oder Dezimalzahl mit Komma ODER Punkt vor „Zimmer“, bspw. `"3 Zimmer"` → `"3"`, `"3,5 Zimmer"` → `"3,5"` oder `"3.5 Zimmer"` → `"3.5"` |
| `r"(\d+(?:[.,]\d+)?)\s*kg"` | verwendet dasselbe Zahlenmuster für Gewichte vor „kg“, bspw. `"12,8 kg"` → `"12,8"` |
| `r"\d+"` | sucht im Text nach einer oder mehreren direkt aufeinanderfolgenden Ziffern und gibt mit `re.findall()` jede gefundene Ziffernfolge als eigenen Treffer zurück. Andere Zeichen unterbrechen die Folge: Bei `"75'000 km"` entstehen deshalb zwei Treffer `["75", "000"]`, die erst durch `''.join(d1)` zu `"75000"` verbunden werden; dasselbe Muster funktioniert für PS-Angaben wie `"245 PS"` → `["245"]` |
| `r"(\d+)\s*m²"` | sucht eine ganze Zahl vor „m²“ und erfasst nur die Zahl, bspw. `"3 Zimmer, 49 m², CHF 1441"` → `"49"`; zwischen Zahl und Einheit darf beliebig viel Leerraum stehen, auch keiner |
| `r"(\d+(?:[.,]\d+)?)\s*m²"` | erfasst auch Flächen mit Dezimalstellen, bspw. `"49,5 m²"` → `"49,5"` oder `"49.5 m²"` → `"49.5"` |
| `r"(\d+(?:[.,]\d+)?)\s*%"` | erfasst Prozentangaben, bspw. `"12,5 %"` → `"12,5"` oder `"12.5%"` → `"12.5"` |

In [ ]:
#Ganze Zimmerzahl extrahieren und als Ganzzahl speichern
rooms = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+)\s*Zimmer", str(i))                                  #"3 Zimmer" => ["3"]; ANPASSEN: Einheit Zimmer
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    rooms.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['rooms_int'] = pd.Series(
    rooms, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'rooms_int']].head())    


#Zimmerzahl mit Dezimalkomma extrahieren und numerisch speichern
rooms = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+,\d+)\s*Zimmer", str(i))                              #"3,5 Zimmer" => ["3,5"]; ANPASSEN: Einheit Zimmer
    try:
        d2 = d1[0].strip().replace(',', '.')                                  
    except IndexError:
        d2 = None
    rooms.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['rooms_comma'] = pd.Series(
    rooms, index=df_dpspick_apartments.index, dtype="float64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'rooms_comma']].head())  #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Zimmerzahl mit Dezimalkomma ODER ganze Zimmerzahl extrahieren
rooms = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+,\d+|\d+)\s*Zimmer", str(i))                          #"3,5 Zimmer" => ["3,5"]; "3 Zimmer" => ["3"]; ANPASSEN: Einheit
    try:
        d2 = d1[0].strip().replace(',', '.')                                  
    except IndexError:
        d2 = None
    rooms.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['rooms'] = pd.Series(
    rooms, index=df_dpspick_apartments.index, dtype="float64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'rooms']].head())        #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Zimmerzahl mit Komma, Punkt oder ohne Dezimalstellen extrahieren
rooms = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+(?:[.,]\d+)?)\s*Zimmer", str(i))                      #"3.5 Zimmer" => ["3.5"]; "3,5 Zimmer" => ["3,5"]; ANPASSEN: Einheit
    try:
        d2 = d1[0].strip().replace(',', '.')                                    
    except IndexError:
        d2 = None
    rooms.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['rooms'] = pd.Series(
    rooms, index=df_dpspick_apartments.index, dtype="float64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'rooms']].head())        #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Gewichte aus Beispieltexten extrahieren
df_weights = pd.DataFrame({'weight_raw': ['12,8 kg', '5 kg', 'keine Angabe']})  #ANPASSEN: Bei echten Daten den bereits eingelesenen DataFrame verwenden
weights = []
for i in df_weights['weight_raw']:                                              #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+(?:[.,]\d+)?)\s*kg", str(i))                          #"12,8 kg" => ["12,8"]; ANPASSEN: Einheit kg
    try:
        d2 = d1[0].strip().replace(',', '.')                                    
    except IndexError:
        d2 = None
    weights.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_weights['weight_kg'] = pd.Series(
    weights, index=df_weights.index, dtype="float64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_weights[['weight_raw', 'weight_kg']].head())                         #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ziffernfolgen aus Kilometerangaben extrahieren und zu einer Zahl verbinden
mileage = []
for i in df_dpspick_autoscout['mileage_raw']:                                   #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"\d+", str(i))                                             #"75'000 km" => ["75", "000"]
    d2 = ''.join(d1) if d1 else None                                            #["75", "000"] => "75000"; kein Treffer => None
    mileage.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_autoscout['mileage_numeric'] = pd.Series(
    mileage, index=df_dpspick_autoscout.index, dtype="Int64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_autoscout[['mileage_raw', 'mileage_numeric']].head())        #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ganze Fläche vor m² extrahieren und numerisch speichern
area = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+)\s*m²", str(i))                                      #"3 Zimmer, 49 m², CHF 1441" => ["49"]; ANPASSEN: Einheit m²
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    area.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['area_m2'] = pd.Series(
    area, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'area_m2']].head())      #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Fläche mit Komma, Punkt oder ohne Dezimalstellen extrahieren
area = []
for i in df_dpspick_apartments['rooms_area_price_raw']:                        #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+(?:[.,]\d+)?)\s*m²", str(i))                         #"49,5 m²" => ["49,5"]; ANPASSEN: Einheit m²
    try:
        d2 = d1[0].strip().replace(',', '.')                                    #"49,5" => "49.5"
    except IndexError:
        d2 = None
    area.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['area_m2'] = pd.Series(
    area, index=df_dpspick_apartments.index, dtype="float64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['rooms_area_price_raw', 'area_m2']].head())      #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Prozentzahlen aus Beispieltexten extrahieren
df_percentages = pd.DataFrame({'percentage_raw': ['12,5 %', '20%', 'keine Angabe']})  
                                                                                #ANPASSEN: Bei echten Daten den bereits eingelesenen DataFrame verwenden

percentages = []
for i in df_percentages['percentage_raw']:                                      #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"(\d+(?:[.,]\d+)?)\s*%", str(i))                           #"12,5 %" => ["12,5"]; ANPASSEN: Einheit %
    try:
        d2 = d1[0].strip().replace(',', '.')                                    
    except IndexError:
        d2 = None
    percentages.append(d2)

#Extrahierte Werte als neue Spalte speichern
df_percentages['percentage'] = pd.Series(
    percentages, index=df_percentages.index, dtype="float64"
)                                                                               #ANPASSEN: DataFrame, Index und Zielspalte; "12.5" => 12.5, None => NaN

#Rohtext und extrahierte Werte anzeigen
display(df_percentages[['percentage_raw', 'percentage']].head())                #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte

            rooms_area_price_raw  rooms_int
0    3 Zimmer, 49 m², CHF 1441.—          3
1  3,5 Zimmer, 65 m², CHF 1850.—          5
2              19 m², CHF 2686.—       <NA>
3    2 Zimmer, 54 m², CHF 4853.—          2
4    2 Zimmer, 49 m², CHF 4335.—          2

            rooms_area_price_raw  rooms_comma
0    3 Zimmer, 49 m², CHF 1441.—          NaN
1  3,5 Zimmer, 65 m², CHF 1850.—          3.5
2              19 m², CHF 2686.—          NaN
3    2 Zimmer, 54 m², CHF 4853.—          NaN
4    2 Zimmer, 49 m², CHF 4335.—          NaN

            rooms_area_price_raw  rooms
0    3 Zimmer, 49 m², CHF 1441.—    3.0
1  3,5 Zimmer, 65 m², CHF 1850.—    3.5
2              19 m², CHF 2686.—    NaN
3    2 Zimmer, 54 m², CHF 4853.—    2.0
4    2 Zimmer, 49 m², CHF 4335.—    2.0

            rooms_area_price_raw  rooms
0    3 Zimmer, 49 m², CHF 1441.—    3.0
1  3,5 Zimmer, 65 m², CHF 1850.—    3.5
2              19 m², CHF 2686.—    NaN
3    2 Zimmer, 54 m², CHF 4853.—    2.0
4    2 Zimmer, 49 m², CHF 4335.—    2.0

     weight_raw  weight_kg
0       12,8 kg       12.8
1          5 kg        5.0
2  keine Angabe        NaN

  mileage_raw  mileage_numeric
0   75'000 km            75000
1   46'655 km            46655
2  138'955 km           138955
3   43'000 km            43000
4   43'300 km            43300

            rooms_area_price_raw  area_m2
0    3 Zimmer, 49 m², CHF 1441.—       49
1  3,5 Zimmer, 65 m², CHF 1850.—       65
2              19 m², CHF 2686.—       19
3    2 Zimmer, 54 m², CHF 4853.—       54
4    2 Zimmer, 49 m², CHF 4335.—       49

            rooms_area_price_raw  area_m2
0    3 Zimmer, 49 m², CHF 1441.—     49.0
1  3,5 Zimmer, 65 m², CHF 1850.—     65.0
2              19 m², CHF 2686.—     19.0
3    2 Zimmer, 54 m², CHF 4853.—     54.0
4    2 Zimmer, 49 m², CHF 4335.—     49.0

  percentage_raw  percentage
0         12,5 %        12.5
1            20%        20.0
2   keine Angabe         NaN

##### Ganze Beträge ohne Tausendertrennzeichen

| Regex-Muster | Bedeutung |
|---|---|
| `r"CHF\s*(\d+)\.—"` | sucht eine ganze Zahl mit Punkt und langem Gedankenstrich `—`, bspw. `"CHF 1441.—"` → `"1441"` |
| `r"CHF\s*(\d+)\.–"` | sucht eine ganze Zahl mit Punkt und kurzem Gedankenstrich `–`, bspw. `"CHF 1441.–"` → `"1441"` |
| `r"CHF\s*(\d+)\.-"` | sucht eine ganze Zahl mit Punkt und Bindestrich `-`, bspw. `"CHF 1441.-"` → `"1441"` |
| `r"CHF\s*(\d+)\.[—–-]"` | erlaubt alle drei Strichvarianten nach dem Punkt, bspw. `"CHF 1441.—"`, `"CHF 1441.–"` oder `"CHF 1441.-"` → `"1441"`; `[—–-]` bedeutet eines dieser drei Zeichen |

In [17]:
#Ganzen CHF-Betrag mit Punkt und langem Gedankenstrich extrahieren
price = []
for i in df_dpspick_apartments['price_raw']:                                    #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*(\d+)\.—", str(i))                                  #"CHF 1441.—" => ["1441"]; ANPASSEN: Währung und Strichvariante
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['price_em_dash'] = pd.Series(
    price, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['price_raw', 'price_em_dash']].head())           #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ganzen CHF-Betrag mit Punkt und kurzem Gedankenstrich extrahieren
price = []
for i in df_dpspick_apartments['price_raw']:                                    #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*(\d+)\.–", str(i))                                  #"CHF 1441.–" => ["1441"]; ANPASSEN: Währung und Strichvariante
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['price_en_dash'] = pd.Series(
    price, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['price_raw', 'price_en_dash']].head())           #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ganzen CHF-Betrag mit Punkt und Bindestrich extrahieren
price = []
for i in df_dpspick_apartments['price_raw']:                                    #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*(\d+)\.-", str(i))                                  #"CHF 1441.-" => ["1441"]; ANPASSEN: Währung und Strichvariante
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['price_hyphen'] = pd.Series(
    price, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['price_raw', 'price_hyphen']].head())            #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ganzen CHF-Betrag mit einer der drei Strichvarianten extrahieren
price = []
for i in df_dpspick_apartments['price_raw']:                                    #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*(\d+)\.[—–-]", str(i))                              #"CHF 1441.—", "CHF 1441.–" oder "CHF 1441.-" => ["1441"]; ANPASSEN: Währung
    try:
        d2 = d1[0].strip()
    except IndexError:
        d2 = None
    price.append(d2)

#Extrahierte Werte als neue Spalte speichern
df_dpspick_apartments['price_chf'] = pd.Series(
    price, index=df_dpspick_apartments.index, dtype="Int64"
)                                                                               

#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_apartments[['price_raw', 'price_chf']].head())               #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte

    price_raw  price_em_dash
0  CHF 1441.—           1441
1  CHF 1850.—           1850
2  CHF 2686.—           2686
3  CHF 4853.—           4853
4  CHF 4335.—           4335

    price_raw  price_en_dash
0  CHF 1441.—           <NA>
1  CHF 1850.—           <NA>
2  CHF 2686.—           <NA>
3  CHF 4853.—           <NA>
4  CHF 4335.—           <NA>

    price_raw  price_hyphen
0  CHF 1441.—          <NA>
1  CHF 1850.—          <NA>
2  CHF 2686.—          <NA>
3  CHF 4853.—          <NA>
4  CHF 4335.—          <NA>

    price_raw  price_chf
0  CHF 1441.—       1441
1  CHF 1850.—       1850
2  CHF 2686.—       2686
3  CHF 4853.—       4853
4  CHF 4335.—       4335

##### Ganze Beträge mit Tausenderapostrophen

| Regex-Muster | Bedeutung |
|---|---|
| `r"CHF\s*([\d']+)\.–"` | erfasst Ziffern und gerade Apostrophe nach „CHF“ mit der Endung „.–“, bspw. `"CHF 22'500.–"` → `"22'500"`; vor der Umwandlung in eine Zahl mit `.replace("'", "")` die Apostrophe entfernen |
| `r"CHF\s*([\d'’]+)\.[—–-]"` | erlaubt gerade und typografische Apostrophe sowie alle drei Strichvarianten, bspw. `"CHF 22'500.–"` oder `"CHF 22’500.—"` → `"22'500"` bzw. `"22’500"`; vor der Umwandlung mit `.replace("'", "").replace("’", "")` beide Apostropharten entfernen |

Beide Muster funktionieren auch ohne Tausenderapostrophe, bspw. `"CHF 1441.–"` → `"1441"`; sie sind für ganze Beträge gedacht

In [ ]:
#Ganzen CHF-Betrag mit geraden Tausenderapostrophen und der Endung .– extrahieren
price = []
for i in df_dpspick_autoscout['price_raw']:                                     #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*([\d']+)\.–", str(i))                               #"CHF 22'500.–" => ["22'500"]; ANPASSEN: Währung und Strichvariante
    try:
        d2 = d1[0].strip().replace("'", "")                                     #"22'500" => "22500"
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_autoscout['price_chf'] = pd.Series(
    price, index=df_dpspick_autoscout.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_autoscout[['price_raw', 'price_chf']].head())                #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte


#Ganzen CHF-Betrag mit geraden oder typografischen Tausenderapostrophen und allen drei Strichvarianten extrahieren
price = []
for i in df_dpspick_autoscout['price_raw']:                                     #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*([\d'’]+)\.[—–-]", str(i))                          #"CHF 22'500.–" => ["22'500"]; "CHF 22’500.—" => ["22’500"]; ANPASSEN: Währung
    try:
        d2 = d1[0].strip().replace("'", "").replace("’", "")                    #"22'500" oder "22’500" => "22500"
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_autoscout['price_chf'] = pd.Series(
    price, index=df_dpspick_autoscout.index, dtype="Int64"
)                                                                               
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_autoscout[['price_raw', 'price_chf']].head())                #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte

##### Ganze Beträge oder Beträge mit Rappen

| Regex-Muster | Bedeutung |
|---|---|
| `r"CHF\s*([\d'’]+(?:[.,]\d{2})?)"` | erfasst ganze CHF-Beträge oder Beträge mit zwei Rappenstellen, mit oder ohne Tausenderapostrophe, bspw. `"CHF 1'249.90"` → `"1'249.90"`, `"CHF 1249,90"` → `"1249,90"` oder `"CHF 1249"` → `"1249"`; vor der Umwandlung Apostrophe entfernen und ein Dezimalkomma durch einen Punkt ersetzen |

In [ ]:
#Ganzen CHF-Betrag oder Betrag mit Rappen und optionalen Tausenderapostrophen extrahieren
price = []
for i in df_dpspick_autoscout['price_raw']:                                     #ANPASSEN: DataFrame und Rohtextspalte
    d1 = re.findall(r"CHF\s*([\d'’]+(?:[.,]\d{2})?)", str(i))                   #"CHF 1'249.90" => ["1'249.90"]; "CHF 1249,90" => ["1249,90"]; ANPASSEN: Währung
    try:
        d2 = d1[0].strip().replace("'", "").replace("’", "").replace(',', '.')  #"1'249.90" oder "1249,90" => "1249.90"
    except IndexError:
        d2 = None
    price.append(d2)
#Extrahierte Werte als neue Spalte speichern
df_dpspick_autoscout['price_chf'] = pd.Series(
    price, index=df_dpspick_autoscout.index, dtype="float64"
)                                                                            
#Rohtext und extrahierte Werte anzeigen
display(df_dpspick_autoscout[['price_raw', 'price_chf']].head())                #ANPASSEN: DataFrame, Rohtextspalte und Zielspalte

      price_raw  price_chf
0  CHF 22'500.–    22500.0
1  CHF 23'749.–    23749.0
2  CHF 18'500.–    18500.0
3  CHF 36'000.–    36000.0
4  CHF 48'500.–    48500.0

#### Apartments: Extract number of rooms

In [ ]:
# Extract values from 'rooms_area_price_raw' strings
rooms = []                                                                      #Leere Liste für die extrahierten Zimmerzahlen erstellen
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #Rohtexte einzeln durchlaufen; i enthält jeweils den aktuellen Text
    d1 = re.findall(r"(\d+,\d+|\d+)\s*Zimmer", i)                               #Zahl vor Zimmer suchen; z. B. "3,5 Zimmer, 65 m²" → ["3,5"]
    try:                                                                        #Versuchen, den ersten Treffer aus der Liste zu verarbeiten
        d2 = d1[0].strip().replace(',', '.')                                    #Ersten Treffer nehmen, äusseren Leerraum entfernen und Komma durch Punkt ersetzen
    except IndexError:                                                          #Wenn die Trefferliste leer ist, existiert d1[0] nicht
        d2 = None                                                               #Keine Zimmerangabe gefunden: fehlenden Wert verwenden
    rooms.append(d2)                                                            #Ergebnis zur Liste hinzufügen; ein Eintrag pro Tabellenzeile

# Save as new variable in the pandas data frame
df_dpspick_apartments['rooms'] = pd.Series(rooms, dtype="float64")              #Gesammelte Zahlentexte als Dezimalzahlen in neuer Spalte speichern; None wird NaN

# Show first records of data frame
df_dpspick_apartments[['rooms_area_price_raw', 'rooms']].head()                 #Rohtext und extrahierte Zimmerzahl für die ersten fünf Zeilen anzeigen

#ANPASSEN: rooms_area_price_raw an die vorhandene Textspalte, an beiden Stellen
#ANPASSEN: Zimmer im Regex an die gesuchte Bezeichnung
#ANPASSEN: 'rooms' an den gewünschten Zielspaltennamen, an beiden Stellen

#INDEX: Wurde df zuvor gefiltert, bei pd.Series zusätzlich index=df.index angeben
#Also: pd.Series(rooms, index=df.index, dtype="float64")

#### Apartments: Extract living area

In [ ]:
# Extract values from 'rooms_area_price_raw' strings
area = []                                                                       #Leere Liste für die extrahierten Flächen erstellen
for i in df_dpspick_apartments['rooms_area_price_raw']:                         #Rohtexte einzeln durchlaufen; i enthält jeweils den aktuellen Text
    d1 = re.findall(r"(\d+)\s*m²", i)                                           #Ganze Zahl vor m² suchen; "3 Zimmer, 49 m²" ergibt ["49"]
    try:                                                                        #Versuchen, den ersten Treffer zu verarbeiten
        d2 = d1[0].strip()                                                      #Ersten Treffer nehmen und äusseren Leerraum entfernen
    except IndexError:                                                          #Wenn die Trefferliste leer ist, existiert d1[0] nicht
        d2 = None                                                               #Keine Flächenangabe gefunden: fehlenden Wert verwenden
    area.append(d2)                                                             #Ergebnis zur Liste hinzufügen; ein Eintrag pro Tabellenzeile

# Save as new variable in the pandas data frame
df_dpspick_apartments['area'] = pd.Series(area, dtype="Int64")                  #Als neue Ganzzahlspalte speichern; Int64 erlaubt fehlende Werte

# Show first records of data frame
df_dpspick_apartments[['rooms_area_price_raw', 'area']].head()                  #Rohtext und extrahierte Fläche für die ersten fünf Zeilen anzeigen

#ANPASSEN: rooms_area_price_raw an die vorhandene Textspalte, an beiden Stellen
#ANPASSEN: m² im Regex an die gesuchte Einheit oder Bezeichnung
#ANPASSEN: 'area' an den gewünschten Zielspaltennamen, an beiden Stellen
#NICHTS ANPASSEN: Listenname area, sofern er überall gleich bleibt
#GEEIGNET: Nichtnegative ganze Zahlen ohne Tausendertrennzeichen vor der Einheit
#INDEX: Wurde df zuvor gefiltert, pd.Series(area, index=df.index, dtype="Int64") verwenden

            rooms_area_price_raw  area
0    3 Zimmer, 49 m², CHF 1441.—    49
1  3,5 Zimmer, 65 m², CHF 1850.—    65
2              19 m², CHF 2686.—    19
3    2 Zimmer, 54 m², CHF 4853.—    54
4    2 Zimmer, 49 m², CHF 4335.—    49

#### Apartments: Extract rental price

In [ ]:
# Extract values from 'price_raw' strings
price = []                                                                      #Leere Liste für die extrahierten Preise erstellen
for i in df_dpspick_apartments['price_raw']:                                   #Rohtexte einzeln durchlaufen; i enthält jeweils den aktuellen Text
    d1 = re.findall(r"CHF\s*(\d+)\.—", i)                                       #Ganze Zahl zwischen CHF und .— suchen; "CHF 1441.—" ergibt ["1441"]
    try:                                                                        #Versuchen, den ersten Treffer zu verarbeiten
        d2 = d1[0].strip()                                                      #Ersten Treffer nehmen und äusseren Leerraum entfernen
    except IndexError:                                                          #Wenn die Trefferliste leer ist, existiert d1[0] nicht
        d2 = None                                                               #Kein passender Preis gefunden: fehlenden Wert verwenden
    price.append(d2)                                                            #Ergebnis zur Liste hinzufügen; ein Eintrag pro Tabellenzeile

# Save as new variable in the pandas data frame
df_dpspick_apartments['price'] = pd.Series(price, dtype="Int64")                #Als neue Ganzzahlspalte speichern; Int64 erlaubt fehlende Werte

# Show first records of data frame
df_dpspick_apartments[['price_raw', 'price']].head()                            #Rohtext und extrahierten Preis für die ersten fünf Zeilen anzeigen

#ANPASSEN: price_raw an die vorhandene Textspalte – an beiden Stellen
#ANPASSEN: CHF und .— im Regex an Währung und genaue Schreibweise im Rohtext
#ANPASSEN: 'price' an den gewünschten Zielspaltennamen – an beiden Stellen
#GEEIGNET: Ganze CHF-Beträge ohne Tausendertrennzeichen im Format "CHF 1441.—", nicht: "CHF 1'441.—", "CHF 1441.–" und Dezimalbeträge passen nicht zu diesem Muster
#INDEX: Wurde df zuvor gefiltert, pd.Series(price, index=df.index, dtype="Int64") verwenden

    price_raw  price
0  CHF 1441.—   1441
1  CHF 1850.—   1850
2  CHF 2686.—   2686
3  CHF 4853.—   4853
4  CHF 4335.—   4335

### Autoscout: Extract numerical values from mileage_raw

In [23]:
# Extract numerical values (note the 'join' function)
mileage = []                                                                    #Leere Liste für die extrahierten Kilometerstände erstellen
for i in df_dpspick_autoscout['mileage_raw']:                                   #Rohtexte einzeln durchlaufen; i enthält jeweils den aktuellen Text
    d1 = re.findall(r"\d+", i)                                                  #Alle Ziffernfolgen finden; "75'000 km" ergibt ["75", "000"]
    try:                                                                        #Versuchen, die Treffer in eine ganze Zahl umzuwandeln
        d2 = int(''.join(d1))                                                   #Ziffernfolgen ohne Trennzeichen verbinden und umwandeln: "75000" → 75000
    except ValueError:                                                          #Wenn keine Ziffern gefunden wurden, scheitert int("")
        d2 = None                                                               #Fehlenden Wert verwenden
    mileage.append(d2)                                                          #Ergebnis zur Liste hinzufügen; ein Eintrag pro Tabellenzeile

# Save as new variable in the pandas data frame
df_dpspick_autoscout['mileage'] = pd.Series(mileage, dtype="Int64")             #Als neue Ganzzahlspalte speichern; Int64 erlaubt fehlende Werte

# Show first records of data frame
df_dpspick_autoscout[['mileage_raw', 'mileage']].head()                         #Rohtext und extrahierten Kilometerstand für die ersten fünf Zeilen anzeigen

#ANPASSEN: mileage_raw an die vorhandene Textspalte – an beiden Stellen
#ANPASSEN: 'mileage' an den gewünschten Zielspaltennamen – an beiden Stellen
#GEEIGNET: Eine nichtnegative ganze Zahl im Text, auch mit Tausendertrennzeichen
#ACHTUNG: Alle Ziffernfolgen werden verbunden; "12,8 kg" würde fälschlich 128 ergeben
#INDEX: Wurde df zuvor gefiltert, pd.Series(mileage, index=df.index, dtype="Int64") verwenden

  mileage_raw  mileage
0   75'000 km    75000
1   46'655 km    46655
2  138'955 km   138955
3   43'000 km    43000
4   43'300 km    43300

## Get data types
### (raw-format from web scraper) bzw. Get data types of all variables, including the new ones

In [25]:
#Datentypen aller Spalten anzeigen. Zeigt, ob die Werte einer Spalte bspw. als Text, ganze Zahlen oder Dezimalzahlen gespeichert sind
#Prüfe damit bspw., ob Preise noch als Text vorliegen oder bereits zum Rechnen geeignet sind
#„Raw-format from web scraper“ bedeutet hier lediglich: Prüfung der Datentypen vor der Bereinigung
df_dpspick_apartments.dtypes #Datentyp jeder Spalte anzeigen

#NICHTS ANPASSEN: wenn deine Tabelle df heisst; sonst df ersetzen

web-scraper-order            str
web-scraper-start-url        str
rooms_area_price_raw         str
address_raw                  str
price_raw                    str
description_raw              str
text_raw                     str
rooms_int                  Int64
rooms_comma              float64
rooms                    float64
area_m2                  float64
price_em_dash              Int64
price_en_dash              Int64
price_hyphen               Int64
price_chf                  Int64
area                       Int64
price                      Int64
dtype: object

## Count number of rows and columns in the data frame (Datenüberblick)

In [ ]:
# Dimension (rows, columns)
print("Dimension:", df_dpspick_apartments.shape)                                #Anzahl Zeilen und Spalten als (Zeilen, Spalten)

# Number of rows
print("Number of rows:", df_dpspick_apartments.shape[0])                        #Anzahl Datensätze

# Number of columns
print("Number of columns:", df_dpspick_apartments.shape[1])                     #Anzahl Merkmale

print("Column name:", df_dpspick_apartments.columns.tolist())                   #Alle Spaltennamen als Liste anzeigen
print(df_dpspick_apartments.dtypes)                                             #Datentyp jeder Spalte anzeigen
df_dpspick_apartments.info()                                                    #Übersicht mit Spalten, Datentypen und Anzahl vorhandener Werte

#Bei info(): Non-Null Count kleiner als Zeilenanzahl bedeutet fehlende Werte

Dimension: (1008, 17)
Number of rows: 1008
Number of columns: 17
Column name: ['web-scraper-order', 'web-scraper-start-url', 'rooms_area_price_raw', 'address_raw', 'price_raw', 'description_raw', 'text_raw', 'rooms_int', 'rooms_comma', 'rooms', 'area_m2', 'price_em_dash', 'price_en_dash', 'price_hyphen', 'price_chf', 'area', 'price']
web-scraper-order            str
web-scraper-start-url        str
rooms_area_price_raw         str
address_raw                  str
price_raw                    str
description_raw              str
text_raw                     str
rooms_int                  Int64
rooms_comma              float64
rooms                    float64
area_m2                  float64
price_em_dash              Int64
price_en_dash              Int64
price_hyphen               Int64
price_chf                  Int64
area                       Int64
price                      Int64
dtype: object
<class 'pandas.DataFrame'>
RangeIndex: 1008 entries, 0 to 1007
Data columns (total 17 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   web-scraper-order      1008 non-null   str
 1   web-scraper-start-url  1008 non-null   str
 2   rooms_area_price_raw   1008 non-null   str
 3   address_raw            1008 non-null   str
 4   price_raw              1008 non-null   str
 5   description_raw        1008 non-null   str
 6   text_raw               1008 non-null   str
 7   rooms_int              963 non-null    Int64
 8   rooms_comma            746 non-null    float64
 9   rooms                  963 non-null    float64
 10  area_m2                916 non-null    float64
 11  price_em_dash          988 non-null    Int64
 12  price_en_dash          0 non-null      Int64
 13  price_hyphen           0 non-null      Int64
 14  price_chf              988 non-null    Int64
 15  area                   916 non-null    Int64
 16  price                  988 non-null    Int64
dtypes: Int64(7), float64(3), str(7)
memory usage: 140.9 KB

#### Fehlende Werte gezielt untersuchen und entfernen

| Befehl | Erklärung |
|---|---|
| `df.isna().sum()` | Fehlende Werte pro Spalte zählen |
| `df.isna().any(axis=1).sum()` | Zeilen mit mindestens einem fehlenden Wert zählen |
| `df[df.isna().any(axis=1)]` | Ganze Zeilen mit mindestens einem fehlenden Wert anzeigen |
| `df = df.dropna(how='all')` | Nur vollständig leere Zeilen entfernen |
| `df = df.dropna(subset=['rooms', 'price'])` | Zeilen entfernen, wenn Zimmerzahl oder Preis fehlt |
| `df = df.dropna(subset=['rooms', 'price'], how='all')` | Zeilen nur entfernen, wenn sowohl Zimmerzahl als auch Preis fehlen |
| `df = df.dropna(axis=1)` | Spalten mit mindestens einem fehlenden Wert entfernen |
| `df = df.dropna(axis=1, how='all')` | Nur vollständig leere Spalten entfernen |

**Wichtig:** Die Varianten sind Alternativen. Bei `subset` werden nur die angegebenen Spalten geprüft; fehlende Werte in anderen Spalten dürfen verbleiben. `isna()` und `isnull()` sind gleichwertig. Leere Strings und reine Leerzeichen werden nicht automatisch als fehlend erkannt

In [ ]:
#Fehlende Werte pro Spalte zählen
print(df_dpspick_apartments.isna().sum())                                       #ANPASSEN: DataFrame


#Zeilen mit mind. einem fehlenden Wert zählen
print(
    "Zeilen mit fehlenden Werten:",
    df_dpspick_apartments.isna().any(axis=1).sum()
)                                                                               #Eine Zeile wird unabhängig von der Anzahl fehlender Zellen nur einmal gezählt
#Ganze Zeilen mit mind. einem fehlenden Wert anzeigen
display(
    df_dpspick_apartments[df_dpspick_apartments.isna().any(axis=1)]
)                                                                               #ANPASSEN: DataFrame; bei grosser Ausgabe .head(20) ergänzen


#Nur vollständig leere Zeilen entfernen
df_dpspick_apartments = df_dpspick_apartments.dropna(how='all')                 #Zeilen mit einzelnen fehlenden Werten bleiben erhalten
#Verbleibende vollständig leere Zeilen kontrollieren
print(
    "Vollständig leere Zeilen nachher:",
    df_dpspick_apartments.isna().all(axis=1).sum()
) 


#Zeilen entfernen, wenn Zimmerzahl ODER Preis fehlt
print(
    "Betroffene Zeilen vorher:",
    df_dpspick_apartments[['rooms', 'price']].isna().any(axis=1).sum()
)                                                                               #ANPASSEN: DataFrame und zu prüfende Spalten
df_dpspick_apartments = df_dpspick_apartments.dropna(
    subset=['rooms', 'price']
)                                                                               #ANPASSEN: Erforderliche Spalten; mind. ein fehlender Wert genügt zum Entfernen
#Fehlende Werte in den geprüften Spalten kontrollieren
print(
    "Fehlende Werte nachher:",
    df_dpspick_apartments[['rooms', 'price']].isna().sum().sum()
)  #Ergebnis sollte 0 sein; andere Spalten können weiterhin fehlende Werte enthalten
#Verbleibende Zeilen ab 0 neu nummerieren
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)


#Zeilen nur entfernen, wenn Zimmerzahl UND Preis fehlen
df_dpspick_apartments = df_dpspick_apartments.dropna(
    subset=['rooms', 'price'], how='all'
)  #ANPASSEN: Vergleichsspalten; ein vorhandener Wert genügt zum Behalten
#Verbleibende Zeilen mit beiden fehlenden Werten kontrollieren
print(
    "Zeilen ohne Zimmerzahl und Preis nachher:",
    df_dpspick_apartments[['rooms', 'price']].isna().all(axis=1).sum()
)  #Ergebnis sollte 0 sein
#Verbleibende Zeilen ab 0 neu nummerieren
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)


#Spalten mit mind. einem fehlenden Wert entfernen
df_dpspick_apartments = df_dpspick_apartments.dropna(axis=1)                    #ACHTUNG: Kann viele Spalten entfernen; vorher fehlende Werte prüfen


#Nur vollständig leere Spalten entfernen
df_dpspick_apartments = df_dpspick_apartments.dropna(
    axis=1, how='all'
)                                                                               #Spalten mit mind. einem vorhandenen Wert bleiben erhalten

## Count and remove missing values

In [31]:
# Count and remove missing values
print("Missing values before removing: ", df_dpspick_apartments.isnull().sum().sum())
#Fehlende Zellen vor dem Entfernen zählen und Gesamtzahl anzeigen
#isnull(): fehlend = True, entspricht isna(); erstes sum(): Anzahl je Spalte; zweites sum(): Gesamtzahl

df_dpspick_apartments = df_dpspick_apartments.dropna()
#Zeilen mit mind. einem fehlenden Wert entfernen und Ergebnis in df speichern
#dropna(): entfernt standardmässig jede Zeile, die mind, einen fehlenden Wert enthält

print("Missing values after removing: ", df_dpspick_apartments.isnull().sum().sum())        #Gesamtzahl fehlender Werte anzeigen
                                                                                            #isnull().sum(): Fehlende Werte pro Spalte zählen
                                                                                            #isnull().sum().sum(): Fehlende Werte im gesamten DataFrame zählen
#Fehlende Zellen nach dem Entfernen zählen; Ergebnis sollte 0 sein
#isnull(): fehlend = True; erstes sum(): Anzahl je Spalte; zweites sum(): Gesamtzahl

# Reset the index of the dataframe
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)
#Verbleibende Zeilen ab 0 neu nummerieren und alten Index verwerfen
#reset_index(): vergibt einen fortlaufenden Index; drop=True: alten Index nicht als Spalte behalten

#ANPASSEN: Nur bestimmte Spalten prüfen → df = df.dropna(subset=["Spalte1", "Spalte2"])
#Dann können fehlende Werte in anderen Spalten verbleiben; die Gesamtzahl muss nicht 0 sein

Missing values before removing:  0
Missing values after removing:  0

### Duplikate zählen, untersuchen und entfernen

| Befehl | Erklärung |
|---|---|
| `df.duplicated()` | Wiederholte Zeilen mit `True` markieren; erstes Vorkommen erhält `False` |
| `df.duplicated().sum()` | Wiederholte Zeilen ohne erstes Vorkommen zählen |
| `df[df.duplicated()]` | Wiederholte Zeilen ohne erstes Vorkommen anzeigen |
| `df[df.duplicated(keep=False)]` | Alle Zeilen einer Duplikatgruppe inklusive erstem Vorkommen anzeigen |
| `df.duplicated(subset=['brand', 'model']).sum()` | Wiederholungen anhand der Kombination aus Marke und Modell zählen |
| `df[df.duplicated(subset=['brand', 'model'], keep=False)]` | Alle Zeilen mit mehrfach vorkommender Kombination aus Marke und Modell anzeigen |
| `df = df.drop_duplicates()` | Vollständig identische Zeilen entfernen; erstes Vorkommen behalten |
| `df = df.drop_duplicates(subset=['brand', 'model'])` | Duplikate anhand der angegebenen Spalten entfernen; erstes Vorkommen behalten |
| `df = df.drop_duplicates(keep='last')` | Bei identischen Zeilen das letzte Vorkommen behalten |
| `df = df.drop_duplicates(keep=False)` | Alle Zeilen einer Duplikatgruppe entfernen; kein Vorkommen behalten |
| `df.duplicated().sum()` | Nach dem Entfernen die verbleibenden vollständig duplizierten Zeilen zählen |

**Wichtig:** Ohne `subset` werden alle Spalten verglichen. Schon eine unterschiedliche Produkt-ID verhindert ein vollständiges Duplikat. Gleiche Marke und gleiches Modell bedeuten nicht automatisch, dass ein Datensatz entfernt werden soll. Die Vergleichsspalten müssen zur fachlichen Bedeutung passen.

**Kontrolle:** Vor und nach dem Entfernen dieselben Vergleichsspalten verwenden. Falls beim Entfernen `subset` verwendet wurde, auch beim anschliessenden Zählen dasselbe `subset` verwenden.

## Count and remove duplicated values

In [32]:
# Count and remove duplicates
print("Anzahl Duplikate vorher:", df_dpspick_apartments.duplicated().sum())
#Zusätzliche Kopien vollständig gleicher Zeilen zählen
#duplicated(): zusätzliche Kopien = True; sum(): True-Werte zählen; erster Eintrag zählt nicht mit

df_dpspick_apartments = df_dpspick_apartments.drop_duplicates()                 #Duplikate entfernen und Ergebnis in df speichern
                                                                                #drop_duplicates(): vergleicht alle Spalten und behält standardmässig den ersten Eintrag

print("Anzahl Duplikate nachher:", df.duplicated().sum())                       #Verbleibende Duplikate zur Kontrolle zählen; Ergebnis sollte 0 sein

# Reset the index of the dataframe
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)            #Verbleibende Zeilen ab 0 neu nummerieren
                                                                                #reset_index(): neuer fortlaufender Index; drop=True: alten Index nicht als Spalte behalten

#ANPASSEN: Falls nur bestimmte Spalten entscheiden, bei BEIDEN Methoden dieselben Spalten angeben:
#df.duplicated(subset=["Spalte1", "Spalte2"]).sum()
#df = df.drop_duplicates(subset=["Spalte1", "Spalte2"])
#OPTIONAL: keep="last" bei drop_duplicates() behält den letzten statt des ersten Eintrags

Anzahl Duplikate vorher: 0
Anzahl Duplikate nachher: 0

In [ ]:
#Vollständig identische Zeilen ohne erstes Vorkommen anzeigen
display(
    df_dpspick_apartments[df_dpspick_apartments.duplicated()]
)                                                                               #Erstes Vorkommen bleibt ausgeblendet; ANPASSEN: DataFrame


#Alle vollständig identischen Zeilen inkl. erstem Vorkommen anzeigen
display(
    df_dpspick_apartments[df_dpspick_apartments.duplicated(keep=False)]
)                                                                               #Alle Mitglieder einer Duplikatgruppe anzeigen; ANPASSEN: DataFrame


#Duplikate anhand der Kombination aus Adresse und Preis zählen
print(
    "Anzahl Duplikate:",
    df_dpspick_apartments.duplicated(subset=['address_raw', 'price_raw']).sum()
)                                                                               #Andere Spalten dürfen unterschiedlich sein; ANPASSEN: DataFrame und Vergleichsspalten


#Alle Zeilen mit gleicher Kombination aus Adresse und Preis anzeigen
display(
    df_dpspick_apartments[
        df_dpspick_apartments.duplicated(
            subset=['address_raw', 'price_raw'], keep=False
        )
    ]
)                                                                               #Inkl. erstem Vorkommen; ANPASSEN: DataFrame und Vergleichsspalten


#Duplikate anhand bestimmter Spalten entfernen und erstes Vorkommen behalten
print(
    "Anzahl Duplikate vorher:",
    df_dpspick_apartments.duplicated(subset=['address_raw', 'price_raw']).sum()
)

df_dpspick_apartments = df_dpspick_apartments.drop_duplicates(
    subset=['address_raw', 'price_raw'], keep='first'
)                                                                               #ANPASSEN: Bei Zählen und Entfernen dieselben Vergleichsspalten verwenden

print(
    "Anzahl Duplikate nachher:",
    df_dpspick_apartments.duplicated(subset=['address_raw', 'price_raw']).sum()
)                                                                               

#Verbleibende Zeilen ab 0 neu nummerieren
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)


#Duplikate anhand bestimmter Spalten entfernen und letztes Vorkommen behalten
df_dpspick_apartments = df_dpspick_apartments.drop_duplicates(
    subset=['address_raw', 'price_raw'], keep='last'
)                                                                               #Letzte Zeile je Kombination behalten; ANPASSEN: DataFrame und Vergleichsspalten

#Verbleibende Duplikate anhand derselben Spalten kontrollieren
print(
    "Anzahl Duplikate nachher:",
    df_dpspick_apartments.duplicated(subset=['address_raw', 'price_raw']).sum()
)  

#Verbleibende Zeilen ab 0 neu nummerieren
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)


#Alle Zeilen einer Duplikatgruppe anhand bestimmter Spalten entfernen
df_dpspick_apartments = df_dpspick_apartments.drop_duplicates(
    subset=['address_raw', 'price_raw'], keep=False
)                                                                               #Bei mehrfacher Kombination ALLE Vorkommen entfernen; ANPASSEN: DataFrame und Vergleichsspalten

#Verbleibende Duplikate anhand derselben Spalten kontrollieren
print(
    "Anzahl Duplikate nachher:",
    df_dpspick_apartments.duplicated(subset=['address_raw', 'price_raw']).sum()
)

#Verbleibende Zeilen ab 0 neu nummerieren
df_dpspick_apartments = df_dpspick_apartments.reset_index(drop=True)

## Use string manipulation methods to create additional variables

#### Textwerte bereinigen und vereinheitlichen

| Befehl | Erklärung |
|---|---|
| `df['spalte'].str.lower()` | Alle Buchstaben in Kleinbuchstaben umwandeln, bspw. `"Schöne Wohnung"` → `"schöne wohnung"` |
| `df['spalte'].str.upper()` | Alle Buchstaben in Grossbuchstaben umwandeln, bspw. `"Schöne Wohnung"` → `"SCHÖNE WOHNUNG"` |
| `df['spalte'].str.strip()` | Leerraum am Anfang und Ende entfernen, bspw. `"  Schöne Wohnung  "` → `"Schöne Wohnung"` |
| `df['spalte'].str.replace('Wohnung', 'Apartment', regex=False)` | Einen wörtlichen Text ersetzen, bspw. `"Schöne Wohnung"` → `"Schöne Apartment"` |
| `df['spalte'].str.replace(r'\s+', ' ', regex=True).str.strip()` | Mehrere aufeinanderfolgende Leerraumzeichen durch ein Leerzeichen ersetzen und äusseren Leerraum entfernen, bspw. `"  Schöne   Wohnung  "` → `"Schöne Wohnung"` |
| `df['spalte'].replace(r'^\s*$', pd.NA, regex=True)` | Leere Texte oder Texte aus ausschliesslich Leerraum als fehlende Werte speichern, bspw. `""` oder `"   "` → `pd.NA` |

**Wichtig:** `.str` ermöglicht Textmethoden auf einer ganzen Spalte. Bei einem einzelnen Text verwendet man bspw. `text.lower()`. `regex=False` behandelt den Suchtext wörtlich; `regex=True` interpretiert ihn als Regex-Muster. Erst durch eine Zuweisung wie `df['spalte'] = ...` wird das Ergebnis im DataFrame gespeichert

In [ ]:
#Text einer Spalte in Kleinbuchstaben umwandeln
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].str.lower()
)                                                                               #"Schöne Wohnung" => "schöne wohnung"; ANPASSEN: DataFrame und Spalte

#Text einer Spalte in Grossbuchstaben umwandeln
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].str.upper()
)                                                                               #"Schöne Wohnung" => "SCHÖNE WOHNUNG"; ANPASSEN: DataFrame und Spalte

#Leerzeichen am Anfang und Ende entfernen
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].str.strip()
)                                                                               #"  Schöne Wohnung  " => "Schöne Wohnung"; ANPASSEN: DataFrame und Spalte

#Bestimmte Zeichen oder Texte ersetzen
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].str.replace('Wohnung', 'Apartment', regex=False)
)                                                                               #"Schöne Wohnung" => "Schöne Apartment"; ANPASSEN: Spalte, Suchtext und Ersatztext

#Mehrere aufeinanderfolgende Leerraumzeichen durch ein Leerzeichen ersetzen
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].str.replace(r'\s+', ' ', regex=True).str.strip()
)                                                                               #"  Schöne   Wohnung  " => "Schöne Wohnung"; ANPASSEN: DataFrame und Spalte

#Leere Texte und Texte aus ausschliesslich Leerraum als fehlende Werte speichern
df_dpspick_apartments['description_raw'] = (
    df_dpspick_apartments['description_raw'].replace(r'^\s*$', pd.NA, regex=True)
)                                                                               #"" oder "   " => fehlender Wert; ANPASSEN: DataFrame und Spalte

### Change strings in 'Spalte' and 'Spalte' to uppercase 

##### Textspalte in Grossbuchstaben umwandeln und optional Leerraum entfernen

Vereinheitlicht die Schreibweise einer Textspalte und speichert das Ergebnis in derselben Spalte

- Variante 1: Nur in Grossbuchstaben umwandeln
- Variante 2: Zusätzlich Leerraum am Anfang und Ende entfernen
- ANPASSEN: Spaltennamen; für weitere Textspalten den jeweiligen Block wiederholen
- Leerzeichen innerhalb des Textes bleiben erhalten

In [ ]:
#Eine der beiden Varianten nehmen, 'type' überall auf Spaltennamen ändern
# Variante 1: Nur Grossbuchstaben
df_dpspick_autoscout['type'] = df_dpspick_autoscout['type'].str.upper()         #Texte in Grossbuchstaben umwandeln und zurückspeichern
                                                                                #.str: Textmethoden anwenden; upper(): Buchstaben grossschreiben
print(df_dpspick_autoscout['type'].head())                                      #Erste fünf Werte zur Kontrolle anzeigen

# Variante 2: Grossbuchstaben und äusseren Leerraum entfernen
df_dpspick_autoscout['type'] = df_dpspick_autoscout['type'].str.upper().str.strip()     
                                                                                #Schreibweise vereinheitlichen und äusseren Leerraum entfernen
                                                                                #upper(): Grossbuchstaben; strip(): Leerraum am Anfang und Ende entfernen
print(df_dpspick_autoscout['type'].head())                                      #Erste fünf Werte zur Kontrolle anzeigen

#ANPASSEN: Spalte, "model' bzw. 'brand' überall im jeweiligen Block an die gewünschte Spalte
#OPTIONAL: .str.lower() statt .str.upper() für Kleinbuchstaben

0    AUDI A5 SPORTBACK 3.0 TDI QUATTRO S-TRONIC (LI...
1          MERCEDES-BENZ SLK 200 7G-TRONIC (CABRIOLET)
2    MERCEDES-BENZ C 350 AVANTGARDE 4MATIC 7G-TRONI...
3    MERCEDES-BENZ A 45 AMG 4MATIC SPEEDSHIFT 7G-DC...
4    AUDI A5 SPORTBACK 2.0 TFSI SPORT QUATTRO S-TRO...
Name: type, dtype: str
0    AUDI A5 SPORTBACK 3.0 TDI QUATTRO S-TRONIC (LI...
1          MERCEDES-BENZ SLK 200 7G-TRONIC (CABRIOLET)
2    MERCEDES-BENZ C 350 AVANTGARDE 4MATIC 7G-TRONI...
3    MERCEDES-BENZ A 45 AMG 4MATIC SPEEDSHIFT 7G-DC...
4    AUDI A5 SPORTBACK 2.0 TFSI SPORT QUATTRO S-TRO...
Name: type, dtype: str

### Calculate length of strings in 'Spalte' and 'Spalte'

Textlängen berechnen und als Histogramm darstellen

Zählt für jeden Text die Zeichen inklusive Leerzeichen und Satzzeichen und speichert die Anzahl in einer neuen Spalte

Das Histogramm zeigt auf der x-Achse die Textlänge und auf der y-Achse die Anzahl Texte je Längenintervall

- Variante 1: Eine Textspalte mit Histogramm und geglätteter Verteilungskurve
- Variante 2: Mehrere Textspalten mit jeweils eigenem Histogramm
- ANPASSEN: Tabellenname, Ausgangsspalten und Namen der neuen Längenspalten

- apply(len) setzt voraus, dass jeder Wert eine Länge besitzt, bspw. ein Text ist
- .str.len() lässt fehlende Texte fehlend; Histogramme berücksichtigen diese fehlenden Werte nicht

In [ ]:
#Eine Spalte:
import matplotlib.pyplot as plt                                 #Diagrammfunktionen laden
import seaborn as sns                                           #Statistische Diagrammfunktionen laden

df_autoscout['type_len'] = df_autoscout['type'].apply(len)      #Zeichenanzahl in einer neuen Spalte speichern
                                                                #apply(len): len() auf jeden Text anwenden
display(df_autoscout[['type', 'type_len']].head())              #Ausgangstext und Länge für die ersten fünf Zeilen anzeigen

plt.figure(figsize=(7, 4))                                      #Neue Abbildung mit 7 × 4 Zoll erstellen
sns.histplot(df_autoscout['type_len'], bins=25, kde=True)       #Histogramm mit 25 Intervallen zeichnen
                                                                #kde=True: geglättete Verteilungskurve ergänzen
plt.title('Verteilung der Textlängen')                          #Diagrammtitel setzen
plt.xlabel('Zeichenanzahl')                                     #x-Achse beschriften
plt.ylabel('Anzahl Texte')                                      #y-Achse beschriften
plt.show()                                                      #Diagramm anzeigen

#ANPASSEN: df_autoscout überall an deinen Tabellennamen
#ANPASSEN: type an die vorhandene Textspalte; type_len an die neue Längenspalte
#OPTIONAL: bins, figsize und Beschriftungen ändern; kde=False für keine Kurve
#BEI FEHLENDEN TEXTEN: .str.len() statt .apply(len) verwenden

In [ ]:
#Mehrere Spalten
import matplotlib.pyplot as plt                                                     #Diagrammfunktionen laden

df_apartments['description_raw_len'] = df_apartments['description_raw'].str.len()   #Beschreibungslängen speichern
df_apartments['text_raw_len'] = df_apartments['text_raw'].str.len()                 #Textlängen speichern
                                                                                    #.str.len(): Zeichen zählen; fehlende Texte bleiben fehlend

ax = df_apartments[['description_raw_len', 'text_raw_len']].hist(
    bins=25,                                                                        #Pro Längenspalte ein Histogramm mit 25 Intervallen erstellen
    figsize=(7, 3),                                                                 #Gesamtgrösse der Abbildung in Zoll
    color='steelblue'                                                               #Balkenfarbe festlegen
)

for axis in ax.flatten():                                                           #Achsenanordnung abflachen und jede Diagrammachse durchlaufen
    axis.set_ylim(bottom=0)                                                         #y-Achse bei 0 beginnen lassen; obere Grenze automatisch bestimmen

plt.show()                                                                          #Histogramme anzeigen

#ANPASSEN: df_apartments überall an deinen Tabellennamen
#ANPASSEN: description_raw und text_raw an die vorhandenen Textspalten
#ANPASSEN: description_raw_len und text_raw_len überall an die neuen Längenspalten
#OPTIONAL: bins, figsize und color ändern
#BEI VORGEGEBENER Y-GRENZE: z. B. axis.set_ylim(0, 300) verwenden

### Create binary (0/1) Variable
Text nach Suchbegriffen durchsuchen, als 0/1 markieren und Treffer zählen

Prüft jede Zeile auf mind. einen Suchbegriff und speichert eine 1 bei einem Treffer, sonst eine 0; anschliessend werden die Treffer gezählt und angezeigt

- Suchbegriffe mit | verbinden, das bedeutet ODER. Diesen String der Variable pattern zuweisen
- Ausgangsspalte: vorhandene Textspalte, die durchsucht wird
- Zielspalte: neue Spalte für die 0/1-Markierung
- Die Suche beachtet Gross-/Kleinschreibung; für eine Suche unabhängig davon case=False ergänzen
- Es werden auch Wortteile gefunden

In [ ]:
# Create a search pattern
pattern = 'RENOVIERT|SANIERT|NEUBAU'                                            #Suchbegriffe festlegen; | bedeutet ODER – ein passender Begriff genügt

# Create a binary (0/1) variable
df_apartments['Neuer Spaltennamen'] = df_apartments['description_raw'].str.contains(pat=pattern, na=False).astype(int)   
                                                                                #Text jeder Zeile prüfen und Ergebnis in match speichern
                                                                                #str.contains(): gesuchter Begriff enthalten → True, sonst False
                                                                                #astype(int): True → 1, False → 0; na=False: fehlender Text → kein Treffer
# Count matching rows
print("Anzahl Treffer:", df_apartments['Neuer Spaltennamen'].sum())                          #Einsen addieren: Jede passende Zeile zählt einmal

# Show matching rows
df_apartments[['description_raw', 'Neuer Spaltennamen']].loc[df_apartments['Neuer Spaltennamen'] == 1]         
                                                                                #Ausgangstext und Markierung nur für Treffer anzeigen
                                                                                #[[...]]: Spalten auswählen; .loc[...]: Zeilen mit match == 1 behalten

#ANPASSEN: Suchbegriffe in pattern
#ANPASSEN: description_raw an deine Spalte (die alte Spalte!)
#ANPASSEN: Neuer Spaltenname an den gewünschten Zielspaltennamen
#ANPASSEN: df überall, falls deine Tabelle anders heisst
#OPTIONAL: Weitere Spalten in der Anzeige ergänzen, bspw. df[['description_raw', 'rooms', 'area', 'price', 'match']].loc[df['match'] == 1]
#OPTIONAL: Gross-/Kleinschreibung ignorieren → str.contains(pat=pattern, case=False, na=False)

### Create Variable
Neue Spalte berechnen: Zwei Zahlenspalten verrechnen und Ergebnis runden

Berechnet für jede Zeile einen neuen Wert aus zwei vorhandenen Zahlenspalten und speichert ihn in einer zusätzlichen Spalte

Bsp.: Preis durch PS-Zahl teilen → Preis pro PS

- ANPASSEN: Ausgangsspalten, Zielspalte und Anzahl Nachkommastellen
- Rechenzeichen: / Division, * Multiplikation, + Addition, - Subtraktion
- Beide Ausgangsspalten müssen numerisch sein; bei einer Division darf der Nenner nicht 0 sein
- Fehlende Ausgangswerte ergeben einen fehlenden Ergebniswert

#### Einschub: Voraussetzung - Numerische Spalten vor der Berechnung erstellen

Für den Preis pro PS müssen die Spalten `price` und `hp` bereits als Zahlen in derselben Tabelle vorhanden sein
Die Rohdaten enthalten zunächst nur `Price_Raw` und `HP_Raw` mit Texten wie `"CHF 22'500.–"` und `"245 PS"`

1. Spaltennamen kleinschreiben: `df_autoscout.columns = df_autoscout.columns.str.lower()` macht bspw. aus `Price_Raw` den Namen `price_raw`; die Inhalte bleiben unverändert

2. Preis- und PS-Regex-Bausteine ausführen: Diese extrahieren die Zahlen aus `price_raw` und `hp_raw` und speichern sie als neue numerische Spalten `price` und `hp`

3. In beiden Bausteinen überall `df_autoscout` statt `df` verwenden, damit die neuen Spalten in der richtigen Tabelle entstehen

4. Anschliessend den Preis durch die PS-Zahl teilen: `df_autoscout['price_per_hp'] = round(df_autoscout['price'] / df_autoscout['hp'], 2)`

ANPASSEN: Tabellenname und Spaltennamen an deine Aufgabe
Die Kleinschreibung der Spaltennamen allein wandelt keine Texte in Zahlen um

In [ ]:
import re                                                                       #Regex-Funktionen laden
import pandas as pd                                                             #pandas für Tabellen laden

df_autoscout.columns = df_autoscout.columns.str.lower()                         #Spaltennamen kleinschreiben: Price_Raw → price_raw

# Numerische Preisspalte erstellen
price = []                                                                      #Leere Liste für die Preise erstellen
for i in df_autoscout['price_raw']:                                             #Jeden Preistext durchlaufen
    d1 = re.findall(r"CHF\s*([\d'’]+)\.[—–-]", i)                               #Betrag zwischen CHF und Preisendung erfassen
    try:
        d2 = d1[0].strip().replace("'", "").replace("’", "")                    #Ersten Treffer nehmen und Tausenderapostrophe entfernen
    except IndexError:                                                          #Kein passender Preis gefunden
        d2 = None                                                               #Fehlenden Wert verwenden
    price.append(d2)                                                            #Ergebnis zur Liste hinzufügen

df_autoscout['price'] = pd.Series(price, index=df_autoscout.index, dtype="Int64") #Neue numerische Preisspalte speichern; fehlende Werte erlauben

# Numerische PS-Spalte erstellen
hp = []                                                                         #Leere Liste für die PS-Werte erstellen
for i in df_autoscout['hp_raw']:                                                #Jede PS-Angabe durchlaufen
    d1 = re.findall(r"\d+", i)                                                  #Ziffernfolgen finden; "245 PS" → ["245"]
    try:
        d2 = int(''.join(d1))                                                   #Ziffernfolgen verbinden und in eine ganze Zahl umwandeln
    except ValueError:                                                          #Keine umwandelbare Zahl gefunden
        d2 = None                                                               #Fehlenden Wert verwenden
    hp.append(d2)                                                               #Ergebnis zur Liste hinzufügen

df_autoscout['hp'] = pd.Series(hp, index=df_autoscout.index, dtype="Int64")     #Neue numerische PS-Spalte speichern; fehlende Werte erlauben

# Umwandlung kontrollieren
display(df_autoscout[['price_raw', 'price', 'hp_raw', 'hp']].head())            #Rohtexte und extrahierte Zahlen vergleichen
print(df_autoscout[['price', 'hp']].dtypes)                                     #Prüfen, ob beide neuen Spalten numerisch sind

In [ ]:
# Create the new variable
df_autoscout['price_per_hp'] = round(df_autoscout['price'] / df_autoscout['hp'], 2)   
                                                        #Preis durch PS-Zahl teilen und Ergebnis als neue Spalte speichern
                                                        #round(..., 2): auf zwei Nachkommastellen runden

# Show values
df_autoscout[['price', 'hp', 'price_per_hp']].head()    #Ausgangswerte und Ergebnis für die ersten fünf Zeilen anzeigen
                                                        #[[...]]: Spalten auswählen; head(): erste fünf Zeilen

#ANPASSEN: 'price' und 'hp' an die vorhandenen Zahlenspalten, in Berechnung und Anzeige
#ANPASSEN: 'price_per_hp' an den gewünschten neuen Spaltennamen, links vom = und in der Anzeige
#ANPASSEN: / an die Rechenoperation; 2 an die Anzahl Nachkommastellen
#ANPASSEN: df überall, falls deine Tabelle anders heisst
#OPTIONAL: .head() weglassen, um alle Zeilen anzufordern; weitere Anzeigespalten in [[...]] ergänzen

### Include current datetime as time stamp
Aktuelles Datum und Uhrzeit als Zeitstempel speichern

Speichert den Zeitpunkt der Ausführung als Text in einer neuen Spalte; alle Zeilen erhalten denselben Zeitstempel

Bsp.: „2026-10-16 01:03:53“ dokumentiert, wann der Code ausgeführt wurde
Bei erneutem Ausführen wird der bisherige Zeitstempel überschrieben

- ANPASSEN: Tabellenname, Zielspaltenname und bei Bedarf Datumsformat
- %Y: vierstelliges Jahr; %m: Monat; %d: Tag
- %H: Stunde; %M: Minute; %S: Sekunde

In [ ]:
from datetime import datetime                                                   #Werkzeug für Datum und Uhrzeit laden

df_apartments['timestamp'] = datetime.now().strftime('%Y-%m-%d %H:%M:%S')       #Aktuellen Zeitpunkt als Text in jeder Zeile speichern
                                                                                #now(): aktueller Zeitpunkt; strftime(): gewünschtes Textformat erzeugen
df_apartments['timestamp'].head()                                               #Zeitstempel der ersten fünf Zeilen anzeigen

#ANPASSEN: df überall an den Namen deiner Tabelle
#ANPASSEN: timestamp an den gewünschten neuen Spaltennamen – an beiden Stellen
#OPTIONAL: '%Y-%m-%d' für nur Datum oder '%d.%m.%Y %H:%M' für Tag.Monat.Jahr Stunde:Minute
#NICHTS ANPASSEN: übriger Code für einen Zeitstempel als Text

# Discretization of Numerical Data

Folien
- Data Discretization (also called “Data Binning”) is a technique that involves dividing a continuous variable into a finite number of intervals or “bins”
- These bins are then treated as categorical variables. Data binning helps to reduce the effects of minor observation errors and helps in managing noise in data, especially when the data is too granular or detailed

- Bei der Diskretisierung werden numerische Werte in geordnete Kategorien eingeteilt, bspw. das Alter 5 in „0–10“, 24 und 29 in „über 20 bis 30“ und 72 in „über 70 bis 80“. Das vereinfacht Vergleiche, verliert aber Details, weil unterschiedliche Werte wie 24 und 29 derselben Klasse zugeordnet werden
- Teilt eine stetige Variable in eine endliche Zahl von Intervallen oder Klassen, auf Englisch bins. Diese Klassen werden dann als kategoriale Variable behandelt
- Das Bsp. verwendet die pandas-Funktion cut. Ein Dataframe enthält die Alterswerte 5, 12, 17, 24, 29, 35, 45, 52, 60 und 72. Die Klassengrenzen liegen bei 0, 10, 20 und so weiter bis 80, mit den Beschriftungen 0 bis 10, 11 bis 20 und so weiter bis 71 bis 80. Die Ausgabe zeigt jedes Alter mit seiner Altersklasse, z.B. 5 in 0 bis 10, 24 in 21 bis 30 und 72 in 71 bis 80

#### Numerische Werte in Klassen einteilen: cut und qcut

Ordnet Zahlen geordneten Kategorien zu, bspw. Preise den Klassen „günstig“, „mittel“ und „teuer“, und speichert die Klasse in einer neuen Spalte

- pd.cut(..., bins=3): Drei gleich breite Zahlenintervalle; die Anzahl Datensätze je Klasse kann unterschiedlich sein
- pd.qcut(..., q=3): Drei Klassen mit ungefähr gleich vielen Datensätzen; die Zahlenintervalle können unterschiedlich breit sein
- Nur eine der beiden Varianten ausführen
- Die Anzahl Beschriftungen muss zur Anzahl Klassen passen
- Fehlende Zahlen erhalten keine Klasse und werden im Balkendiagramm nicht mitgezählt
- Achtung bei qcut: Viele gleiche Werte können identische Klassengrenzen erzeugen und einen Fehler auslösen; dann Anzahl Klassen oder Einteilung prüfen

In [ ]:
#An der Prüfung eine der beiden Varianten nehmen. Für "Create a 1x2 grid" siehe V4 Ü3.2
# Variante 1: Gleich breite Zahlenintervalle
df_autoscout['price_category'] = pd.cut(df_autoscout['price_per_hp'],
                              bins=3,                                           #Wertebereich in drei gleich breite Intervalle teilen
                              labels=['günstig', 'mittel', 'teuer'])            #Klassen von niedrigen zu hohen Werten beschriften
#Hier wird eine neue Spalte "price_category" im DF erstellt

# Variante 2: Ungefähr gleich viele Datensätze je Klasse
df_autoscout['price_category'] = pd.qcut(df_autoscout['price_per_hp'],
                               q=3,                                             #Quantilgrenzen für drei ungefähr gleich grosse Gruppen bestimmen
                               labels=['günstig', 'mittel', 'teuer'])           #Klassen von niedrigen zu hohen Werten beschriften

df_autoscout[['price_per_hp', 'price_category']].head()                         #Zahlenwert und zugeordnete Klasse für die ersten fünf Zeilen anzeigen

#NUR EINE VARIANTE AUSFÜHREN: Beide schreiben in dieselbe Zielspalte
#ANPASSEN: df überall an deinen Tabellennamen, z. B. df_autoscout
#ANPASSEN: price_per_hp an die vorhandene numerische Spalte
#ANPASSEN: price_category an den gewünschten neuen Spaltennamen
#ANPASSEN: bins bzw. q an die Klassenanzahl; labels an passende Beschriftungen

# One-Hot Encoding
- Technique that converts categorical variables into a format that can be provided to machine learning algorithms. Specifically, it transforms categorical data, which can have multiple categories, into vectors with binary values
- One-Hot-Encoding wandelt eine kategoriale Spalte in mehrere 0/1-Spalten um – beispielsweise wird „Farbe“ zu „Rot“, „Blau“ und „Grün“, wobei jede Zeile bei ihrer Farbe eine 1 und bei den anderen eine 0 erhält
- Bsp.: Eine Spalte Color mit den Werten Red, Green, Blue, Green und Red. Nach dem Kodieren gibt es drei Spalten Color_Red, Color_Green und Color_Blue. In jeder Zeile steht eine 1 in der Spalte der passenden Farbe und sonst 0. Die erste Zeile, Red, wird also zu 1, 0, 0

- Erstellt für jede Kategorie eine eigene Spalte: Gehört eine Zeile zu dieser Kategorie, erhält sie dort eine 1, sonst eine 0
- Bsp.: Aus der Preisklasse „günstig“ entstehen die Spalten „price_category_günstig“, „price_category_mittel“ und „price_category_teuer“ mit den Werten 1, 0 und 0
- Die ursprüngliche Kategoriespalte wird ersetzt; alle anderen Spalten bleiben erhalten
- Voraussetzung: Die Kategoriespalte wurde bereits erstellt, bspw. mit cut oder qcut

In [ ]:
#VORAUSSETZUNG: Zuerst den cut()- oder qcut()-Block (Dicretization) ausführen; er erstellt die Kategoriespalte
#ANPASSEN: Tabellenname und Kategoriespalte an den vorherigen Block – Spaltenname links vom = übernehmen
#BEISPIEL: df_autoscout['price_category'] = pd.qcut(...) → columns=['price_category'], Anzeige mit like='price_category_'

# One-Hot-Encoding
df_autoscout = pd.get_dummies(df_autoscout, #Ergebnis in df_autoscout speichern
                               columns=['price_category'], #Zuvor erstellte Kategoriespalte in Dummy-Spalten umwandeln
                               drop_first=False, #Alle Kategorien behalten
                               dtype=int) #Direkt 0/1 speichern

# Show dummy variables
df_autoscout.filter(like='price_category_').head() #Neue Dummy-Spalten der ersten fünf Zeilen anzeigen

#ANPASSEN: df_autoscout überall an den Namen deiner Tabelle
#ANPASSEN: price_category an die Kategoriespalte aus dem vorherigen cut()- oder qcut()-Block
#ANPASSEN: price_category_ in der Anzeige an denselben Spaltennamen plus Unterstrich
#NICHTS ANPASSEN: dtype=int für 0/1; drop_first=False, wenn alle Kategorien behalten werden sollen
#ACHTUNG: One-Hot-Encoding ersetzt die Kategoriespalte; vor erneutem Ausführen zuerst den cut()- oder qcut()-Block ausführen

# Scaling (Data Scaling)

- Data scaling is a preprocessing step in machine learning and data analysis that involves adjusting the values of numerical data to a common scale, without distorting differences in the ranges of values
- Its primary purpose is to bring all the features into a comparable range, which can significantly improve the performance of machine learning algorithms, especially those that are sensitive to the magnitude of the data like linear & logistic regression and k-nearest neighbors
- Data Scaling  bringt numerische Merkmale auf eine vergleichbare Grössenordnung, damit grosse Zahlenwerte ein Modell nicht allein wegen ihrer Skala stärker beeinflussen
- Bsp. Kilometerstände von 0-200’000 km und Leistungen von 0-500 PS werden jeweils auf den Bereich 0–1 skaliert, sodass 100’000 km und 250 PS beide den Wert 0.5 erhalten

### Min-Max Scaling

### Min-Max-Skalierung: Zahlenwerte auf den Bereich 0 bis 1 bringen
Ist ein Skalierungsverfahren, bei dem von jedem Wert das Minimum abgezogen und das Ergebnis durch die Spannweite (Maximum − Minimum) geteilt wird, sodass alle Werte zwischen 0 und 1 liegen, ohne die Form der Verteilung zu verändern.

- Zieht von jedem Wert das Minimum ab und teilt durch die Spannweite: (Wert − Minimum) / (Maximum − Minimum)

- Bsp.: Bei Kilometerständen zwischen 20’000 und 120’000 km wird 20’000 zu 0, 70’000 zu 0.5 und 120’000 zu 1

- Die ursprüngliche Zahlenspalte bleibt erhalten; die skalierten Werte werden in einer neuen Spalte gespeichert

- Die Verteilungsform bleibt gleich, nur die Skala verändert sich

- Voraussetzung: Die Ausgangsspalte ist numerisch und enthält mindestens zwei unterschiedliche Werte, sonst ist der Nenner 0

#### By hand
Bei **By hand** wird die Skalierung mithilfe einer mathematischen Formel selbst berechnet, während **scikit-learn** die Berechnung mit vorgefertigten Methoden automatisiert. `fit()` bestimmt die benötigten Parameter (z. B. Minimum und Maximum), und `transform()` skaliert die Werte damit. **Beide Verfahren liefern praktisch identische Ergebnisse**, was mit `np.allclose()` überprüft werden kann. Der Vorteil von scikit-learn ist, dass die ermittelten Skalierungsparameter gespeichert und auf neue Daten angewendet werden können.

In [ ]:
# Min-Max scaling
df_autoscout['mileage_scaled_minmax'] = ((df_autoscout['mileage'] - df_autoscout['mileage'].min())                    #Minimum von jedem Wert abziehen
                               / (df_autoscout['mileage'].max() - df_autoscout['mileage'].min()))           #Durch die Spannweite teilen; Ergebnis zwischen 0 und 1

# Compare original and scaled values
ax = df_autoscout[['mileage', 'mileage_scaled_minmax']].hist(
    bins=25,                                                                            #Pro Spalte ein Histogramm mit 25 Intervallen erstellen
    figsize=(7, 3),                                                                     #Gesamtgrösse der Abbildung in Zoll
    color='steelblue')                                                                  #Balkenfarbe festlegen

for axis, label in zip(ax.flatten(), ['Kilometerstand', 'Kilometerstand skaliert']):    #Achsen und Beschriftungen paarweise durchlaufen
                                                                                        #flatten(): Achsenanordnung abflachen; zip(): paarweise verbinden
    axis.set_ylim(bottom=0)                                                             #y-Achse bei 0 beginnen lassen; obere Grenze automatisch bestimmen
    axis.set_xlabel(label)                                                              #Jeweils passende x-Achsenbeschriftung setzen
    axis.set_ylabel('Anzahl Datensätze')                                                #y-Achse beschriften

plt.tight_layout()                                                                      #Abstände zwischen den Diagrammen anpassen
plt.show()                                                                              #Beide Histogramme anzeigen

#ANPASSEN: df überall an deinen Tabellennamen, z. B. df_autoscout oder df_apartments
#ANPASSEN: mileage überall an die vorhandene numerische Ausgangsspalte
#ANPASSEN: mileage_scaled_minmax überall an den gewünschten neuen Spaltennamen
#ANPASSEN: Die beiden Beschriftungen in der zip()-Liste an dein Merkmal
#OPTIONAL: bins, figsize und color ändern
#BEI VORGEGEBENER Y-GRENZE: axis.set_ylim(0, 500) statt axis.set_ylim(bottom=0)

#### Min-Max Scaling (scikit-learn)
- **Zweck:** Numerische Werte mithilfe von `MinMaxScaler()` auf den Bereich **0 bis 1** skalieren, damit unterschiedlich grosse Zahlenwerte vergleichbar werden.
- **Funktionsweise:** `MinMaxScaler()` verwendet dieselbe Formel wie die manuelle Min-Max-Skalierung: `(Wert − Minimum) / (Maximum − Minimum)`. Das Minimum wird zu 0, das Maximum zu 1.
- **Voraussetzung:** Die zu skalierende Spalte muss numerische Werte enthalten. Für den Vergleich mit `np.allclose()` muss die manuelle Skalierung bereits durchgeführt worden sein.
- **Kontrolle:** `np.allclose()` vergleicht die manuell berechneten und die mit scikit-learn skalierten Werte. Das Ergebnis `True` bestätigt, dass beide Verfahren innerhalb kleiner numerischer Toleranzen übereinstimmen.

In [ ]:
# Min-Max scaling (scikit-learn version)
from sklearn.preprocessing import MinMaxScaler                          #MinMaxScaler importieren: numerische Werte standardmässig auf 0 bis 1 skalieren

# Fit the scaler and transform the variable
# (note the double brackets: scikit-learn expects a 2D input)
scaler = MinMaxScaler() #Scaler-Objekt für die Min-Max-Skalierung erstellen
df_autoscout['mileage_scaled_minmax_sklearn'] = scaler.fit_transform(   #Skalierte Werte in neuer Spalte speichern
    df_autoscout[['mileage']]).ravel()                                  #fit_transform(): Minimum und Maximum bestimmen und Werte auf 0 bis 1 skalieren
                                                                        #[['mileage']]: Spalte als 2D-DataFrame übergeben (von sklearn erwartet)
                                                                        #ravel(): 2D-Ergebnis in ein eindimensionales Array für die neue Spalte umwandeln

# Check that the by-hand and scikit-learn versions give the same result
print(np.allclose(df_autoscout['mileage_scaled_minmax'],                #Manuelle und sklearn-Skalierung miteinander vergleichen
                  df_autoscout['mileage_scaled_minmax_sklearn']))       #allclose(): Werte innerhalb kleiner numerischer Toleranzen vergleichen

#ANPASSEN: df_autoscout überall an den verwendeten DataFrame anpassen (z.B. df_apartments)
#ANPASSEN: mileage überall durch die zu skalierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_minmax_sklearn an den gewünschten neuen Spaltennamen anpassen
#ANPASSEN: mileage_scaled_minmax an den Namen der zuvor manuell skalierten Spalte anpassen
#NICHTS ANPASSEN: MinMaxScaler(), fit_transform(), ravel() und np.allclose() bleiben unverändert
#VORAUSSETZUNG: Die manuelle Skalierung muss bereits durchgeführt worden sein, damit np.allclose() funktioniert

### Max-Absolute Scaling (manuell)

Ist ein Skalierungsverfahren, bei dem jeder Wert durch den grössten Absolutwert des Merkmals geteilt wird, sodass alle Werte zwischen −1 und 1 liegen, ohne den Nullpunkt oder die Form der Verteilung zu verändern.
- **Zweck:** Numerische Werte durch den grössten Absolutwert der Spalte dividieren, um sie auf den Bereich **−1 bis 1** zu skalieren (bei ausschliesslich positiven Werten: 0 bis 1).
- **Formel:** `Wert / max(abs(alle Werte))` – der betragsmässig grösste Wert wird zu −1 oder 1; der Wert 0 bleibt unverändert.
- **Unterschied zu Min-Max:** Bei Max-Absolute wird kein Minimum abgezogen. Deshalb bleibt der Nullpunkt erhalten, während bei Min-Max der kleinste Wert zu 0 wird.
- **Erkenntnis:** Die Skalierung verändert die Grössenordnung, aber nicht die Verteilungsform oder die relativen Abstände. Die Histogramme zeigen dieselbe Verteilung, jedoch mit unterschiedlichen x-Achsenwerten.

In [ ]:
# Max-Absolute scaling of the variable 'mileage' (by hand)
df_autoscout['mileage_scaled_max_abs'] = df_autoscout['mileage'] / df_autoscout['mileage'].abs().max() #Jeden Kilometerstand durch den grössten Absolutwert dividieren
                                                                                    #abs(): Absolutwerte bilden; max(): grössten Absolutwert bestimmen
                                                                                    #Ergebnis: Werte zwischen -1 und 1 (bei positiven Kilometerständen 0 bis 1)

# Histogram of the variable 'mileage' and 'mileage_scaled_max_abs'
ax = df_autoscout[['mileage', 'mileage_scaled_max_abs']].hist(bins=25,              #Originale und skalierte Kilometerstände als zwei Histogramme darstellen
                                                             figsize=(7, 3),        #figsize: Abbildungsgrösse in Zoll (Breite × Höhe)
                                                             color='steelblue')     #bins=25: 25 Intervalle; color: Balkenfarbe
                                                                                    #hist(): Häufigkeitsverteilung darstellen; ax speichert die Diagrammachsen

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'Max_Abs_Scaled(Mileage)']):       #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                                    #flatten(): Achsenanordnung in 1D umwandeln; zip(): Elemente paarweise verbinden
    axis.set_ylim(0, 500)                                                           #set_ylim(): y-Achse auf 0 bis 500 begrenzen
    axis.set_xlabel(label)                                                          #set_xlabel(): x-Achse beschriften
    axis.set_ylabel('Frequency')                                                    #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                                          #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall an den verwendeten DataFrame anpassen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu skalierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_max_abs an den gewünschten neuen Spaltennamen anpassen
#ANPASSEN: ['Mileage', 'Max_Abs_Scaled(Mileage)'] an die gewünschten x-Achsenbeschriftungen anpassen
#ANPASSEN: bins=25, figsize=(7, 3), color='steelblue' und set_ylim(0, 500) bei Bedarf anpassen
#NICHTS ANPASSEN: abs(), max(), hist(), flatten(), zip(), set_xlabel(), set_ylabel() und plt.show() bleiben unverändert

#### Max-Absolute Scaling (scikit-learn)

- **Zweck:** Numerische Werte mit `MaxAbsScaler()` automatisch durch den grössten Absolutwert skalieren (Bereich −1 bis 1).
- **Funktionsweise:** `fit_transform()` bestimmt den grössten Absolutwert der Spalte und dividiert sämtliche Werte dadurch. Im Gegensatz zu Min-Max wird kein Minimum abgezogen, weshalb 0 unverändert bleibt.
- **Voraussetzung:** Die Ausgangsspalte muss numerisch sein. Für den Vergleich mit `np.allclose()` muss die manuelle Max-Absolute-Skalierung bereits durchgeführt worden sein.
- **Kontrolle:** `np.allclose()` überprüft, ob die manuelle Berechnung und `MaxAbsScaler()` innerhalb kleiner numerischer Toleranzen übereinstimmen. Das Ergebnis `True` bestätigt, dass beide Verfahren praktisch identische Werte liefern.

In [ ]:
# Max-Absolute scaling of the variable 'mileage' (scikit-learn version)
from sklearn.preprocessing import MaxAbsScaler                            #MaxAbsScaler importieren: Werte durch den grössten Absolutwert skalieren

# Fit the scaler and transform the variable
# (note the double brackets: scikit-learn expects a 2D input)
scaler = MaxAbsScaler() #Scaler-Objekt für die Max-Absolute-Skalierung erstellen
df_autoscout['mileage_scaled_max_abs_sklearn'] = scaler.fit_transform(    #Skalierte Kilometerstände in neuer Spalte speichern
    df_autoscout[['mileage']]).ravel()                                    #fit_transform(): Grössten Absolutwert bestimmen und Werte dadurch dividieren
                                                                          #[['mileage']]: Spalte als 2D-DataFrame übergeben (von sklearn erwartet)
                                                                          #ravel(): 2D-Ergebnis in ein eindimensionales Array für die neue Spalte umwandeln

# Check that the by-hand and scikit-learn versions give the same result
print(np.allclose(df_autoscout['mileage_scaled_max_abs'],                 #Manuelle und sklearn-Skalierung miteinander vergleichen
                  df_autoscout['mileage_scaled_max_abs_sklearn']))        #allclose(): Werte innerhalb kleiner numerischer Toleranzen vergleichen
                                                                          #True: Beide Verfahren liefern praktisch identische Werte

#ANPASSEN: df_autoscout überall an den verwendeten DataFrame anpassen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu skalierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_max_abs_sklearn an den gewünschten neuen Spaltennamen anpassen
#ANPASSEN: mileage_scaled_max_abs an den Namen der zuvor manuell skalierten Spalte anpassen
#NICHTS ANPASSEN: MaxAbsScaler(), fit_transform(), ravel() und np.allclose() bleiben unverändert
#VORAUSSETZUNG: Die manuell skalierte Spalte muss bereits existieren, damit np.allclose() funktioniert

### Robust Scaling

**Zweck:** Numerische Werte mithilfe des Medians und des Interquartilsabstands (IQR) skalieren. Besonders geeignet für Daten mit **Ausreissern**, da Median und IQR weniger empfindlich gegenüber extremen Werten sind.
- **Formel:** `(Wert − Median) / (Q3 − Q1)` – vom ursprünglichen Wert den Median abziehen und durch den Interquartilsabstand teilen.
- **Methoden:** `median()` bestimmt den mittleren Wert (50. Perzentil); `quantile(0.25)` bestimmt das untere Quartil (Q1) und `quantile(0.75)` das obere Quartil (Q3). Die Differenz `Q3 − Q1` ergibt den IQR und beschreibt die Streuung der mittleren 50 % der Daten.
- **Erkenntnis:** Der Median wird zu 0; Werte darunter werden negativ, Werte darüber positiv. Es gibt keinen festen Wertebereich wie bei Min-Max Scaling. Die Verteilungsform bleibt erhalten, die x-Achse wird verschoben und skaliert.
- **Unterschied zu Min-Max und Max-Absolute:** Robust Scaling verwendet Median und IQR statt Minimum oder Maximum. Dadurch beeinflussen Ausreisser die Skalierung weniger stark, bleiben aber weiterhin im Datensatz enthalten.

#### Robus Scaling (manuell)

In [ ]:
# Robust scaling of the variable 'mileage' (by hand)
df_autoscout['mileage_scaled_robust'] = (df_autoscout['mileage'] - df_autoscout['mileage'].median()) / \
    (df_autoscout['mileage'].quantile(0.75)                         #quantile(0.75): 75. Perzentil (Q3) bestimmen
     - df_autoscout['mileage'].quantile(0.25))                      #quantile(0.25): 25. Perzentil (Q1) bestimmen
                                                                    #median(): mittleren Wert bestimmen (50. Perzentil)
                                                                    #Formel: (Wert - Median) / (Q3 - Q1); Q3 - Q1 = IQR
                                                                    #Ergebnis: Median wird 0; Ausreisser beeinflussen die Skalierung weniger

# Histogram of the variable 'mileage' and 'mileage_scaled_robust'
ax = df_autoscout[['mileage', 'mileage_scaled_robust']].hist(bins=25,           #Originale und skalierte Werte als zwei Histogramme darstellen
                                                            figsize=(7, 3),     #figsize: Abbildungsgrösse (Breite × Höhe in Zoll)
                                                            color='steelblue')  #hist(): Histogramme erstellen; bins=25: Anzahl Intervalle
                                                                                #color: Balkenfarbe; ax speichert die Diagrammachsen

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'Scaled_Robust(Mileage)']):    #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                                #flatten(): Achsenanordnung in 1D umwandeln
                                                                                #zip(): Achsen und Beschriftungen paarweise verbinden
    axis.set_ylim(0, 500)                                                       #set_ylim(): y-Achse auf 0 bis 500 begrenzen
    axis.set_xlabel(label)                                                      #set_xlabel(): x-Achse beschriften
    axis.set_ylabel('Frequency')                                                #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                                      #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu skalierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_robust an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: ['Mileage', 'Scaled_Robust(Mileage)'] an die jeweiligen Achsenbeschriftungen anpassen
#ANPASSEN: bins=25, figsize=(7, 3), color='steelblue' und set_ylim(0, 500) bei Bedarf anpassen
#NICHTS ANPASSEN: median(), quantile(0.75), quantile(0.25), hist(), flatten(), zip() und plt.show()
#VORAUSSETZUNG: Numerische Spalte mit IQR > 0; pandas und matplotlib.pyplot als plt müssen importiert sein

#### Robust Scaling (scikit-learn)

- **Zweck:** Numerische Werte mit `RobustScaler()` automatisch anhand des Medians und des Interquartilsabstands (IQR) skalieren, um den Einfluss von Ausreissern zu reduzieren.
- **Funktionsweise:** `fit_transform()` bestimmt den Median und den IQR (`Q3 − Q1`) und skaliert die Werte mit der Formel `(Wert − Median) / IQR`.
- **Erkenntnis:** Der Median wird zu 0. Werte darunter werden negativ, Werte darüber positiv. Anders als bei Min-Max Scaling gibt es keinen festen Wertebereich.
- **Kontrolle:** `np.allclose()` vergleicht die manuelle Berechnung mit der scikit-learn-Version. `True` bestätigt, dass beide Verfahren innerhalb kleiner numerischer Toleranzen übereinstimmen.
- **Voraussetzung:** Für den Vergleich muss die manuell skalierte Spalte bereits existieren.

In [ ]:
# Robust scaling of the variable 'mileage' (scikit-learn version)
from sklearn.preprocessing import RobustScaler                          #RobustScaler importieren: Werte anhand von Median und IQR skalieren

# Fit the scaler and transform the variable
# (note the double brackets: scikit-learn expects a 2D input)
scaler = RobustScaler() #Scaler-Objekt für die robuste Skalierung erstellen
df_autoscout['mileage_scaled_robust_sklearn'] = scaler.fit_transform(   #Robust skalierte Kilometerstände in neuer Spalte speichern
    df_autoscout[['mileage']]).ravel()                                  #fit_transform(): Median und IQR bestimmen und Werte damit skalieren
                                                                        #[['mileage']]: Spalte als 2D-DataFrame übergeben (von sklearn erwartet)
                                                                        #ravel(): 2D-Ergebnis in ein eindimensionales Array für die neue Spalte umwandeln

# Check that the by-hand and scikit-learn versions give the same result
print(np.allclose(df_autoscout['mileage_scaled_robust'],                #Manuelle und sklearn-Skalierung miteinander vergleichen
                  df_autoscout['mileage_scaled_robust_sklearn']))       #allclose(): Werte innerhalb kleiner numerischer Toleranzen vergleichen
                                                                        #True: Beide Verfahren liefern praktisch identische Ergebnisse

#ANPASSEN: df_autoscout überall an den verwendeten DataFrame anpassen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu skalierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_robust_sklearn an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: mileage_scaled_robust an den Namen der zuvor manuell skalierten Spalte anpassen
#NICHTS ANPASSEN: RobustScaler(), fit_transform(), ravel() und np.allclose() bleiben unverändert
#VORAUSSETZUNG: Die manuelle Robust-Skalierung muss bereits ausgeführt worden sein, damit np.allclose() funktioniert

### Data Standardization (Z-Score Normalization)

- **Definition:** Standardisierung ist ein Skalierungsverfahren, bei dem numerische Werte so umgerechnet werden, dass sie einen **Mittelwert von 0 und eine Standardabweichung von 1** aufweisen.
- **Zweck:** Numerische Merkmale mit unterschiedlichen Grössenordnungen vergleichbar machen, damit grosse Zahlenwerte ein Modell nicht allein aufgrund ihrer Skala stärker beeinflussen. Durch die Standardisierung wird zudem erkennbar, wie viele Standardabweichungen ein Wert über oder unter dem Mittelwert liegt.
- **Formel:** `(Wert − Mittelwert) / Standardabweichung` – von jedem Wert wird der Mittelwert abgezogen und das Ergebnis durch die Standardabweichung geteilt.
- **Mittelwert (μ):** Durchschnitt aller Werte eines Merkmals; wird durch die Standardisierung auf 0 verschoben.
- **Standardabweichung (σ):** Mass für die Streuung der Werte um den Mittelwert; wird durch die Standardisierung auf 1 gebracht.
- **Erkenntnis:** Werte über dem Mittelwert werden positiv, Werte darunter negativ. Die Verteilungsform bleibt unverändert und die Daten werden **nicht automatisch normalverteilt**. Im Gegensatz zu Min-Max Scaling gibt es keinen festen Wertebereich. In scikit-learn wird dafür `StandardScaler()` verwendet.

#### Data Standardization / Z-Score Normalization (manuell)

- **Definition:** Standardisierung ist ein Skalierungsverfahren, bei dem numerische Werte so umgerechnet werden, dass sie einen Mittelwert von 0 und eine Standardabweichung von 1 aufweisen.
- **Zweck:** Merkmale unterschiedlicher Grössenordnungen vergleichbar machen, damit grosse Zahlenwerte ein Modell nicht allein aufgrund ihrer Skala stärker beeinflussen. Ein Z-Score zeigt zudem, wie viele Standardabweichungen ein Wert vom Mittelwert entfernt liegt.
- **Formel:** `(Wert − Mittelwert) / Standardabweichung` – von jedem Wert den Mittelwert abziehen und durch die Standardabweichung dividieren.
- **Methoden:** `mean()` berechnet den arithmetischen Mittelwert; `std()` bestimmt die Standardabweichung und damit die Streuung der Werte um den Mittelwert.
- **Erkenntnis:** Der Mittelwert wird zu 0 und die Standardabweichung zu 1. Werte über dem Mittelwert werden positiv, darunter negativ. Es gibt keinen festen Wertebereich. Die Verteilungsform bleibt unverändert und die Daten werden nicht automatisch normalverteilt.

In [ ]:
# Z-score Normalization of the variable 'mileage' (by hand)
df_autoscout['mileage_scaled_z'] = ((df_autoscout['mileage'] - df_autoscout['mileage'].mean())  #Von jedem Kilometerstand den Mittelwert abziehen
                                   / df_autoscout['mileage'].std())                             #Durch die Standardabweichung dividieren
                                                                                                #mean(): arithmetischen Mittelwert berechnen
                                                                                                #std(): Standardabweichung bestimmen (standardmässig Stichprobe, ddof=1)
                                                                                                #Ergebnis: Mittelwert ≈ 0 und Standardabweichung ≈ 1
                                                                                                #Positive Werte liegen über, negative unter dem Mittelwert

# Histogram of the variable 'mileage' and 'mileage_scaled_z'
ax = df_autoscout[['mileage', 'mileage_scaled_z']].hist(bins=25,                #Originale und standardisierte Kilometerstände als zwei Histogramme darstellen
                                                        figsize=(7, 3),         #figsize: Abbildungsgrösse in Zoll (Breite × Höhe)
                                                        color='steelblue')      #hist(): Histogramme erstellen; bins=25: Anzahl Intervalle
                                                                                #color: Balkenfarbe; ax speichert die Diagrammachsen
                                                                                #Erkenntnis: Verteilungsform bleibt gleich, x-Achse wird verschoben und skaliert

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'Scaled_Z(Mileage)']):         #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                                #flatten(): Achsenanordnung in 1D umwandeln
                                                                                #zip(): Achsen und Beschriftungen paarweise verbinden
    axis.set_ylim(0, 500)                                                       #set_ylim(): y-Achse auf 0 bis 500 begrenzen
    axis.set_xlabel(label)                                                      #set_xlabel(): x-Achse beschriften
    axis.set_ylabel('Frequency')                                                #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                                      #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu standardisierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_z überall an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: ['Mileage', 'Scaled_Z(Mileage)'] an die jeweiligen Achsenbeschriftungen anpassen
#ANPASSEN: bins=25, figsize=(7, 3), color='steelblue' und set_ylim(0, 500) bei Bedarf anpassen
#NICHTS ANPASSEN: mean(), std(), hist(), flatten(), zip(), set_xlabel(), set_ylabel() und plt.show()
#VORAUSSETZUNG: Numerische Spalte mit mindestens zwei gültigen, unterschiedlichen Werten; pandas und matplotlib.pyplot als plt importiert

### Data Standardization / Z-Score Normalization (scikit-learn)

- **Zweck:** Numerische Werte mit `StandardScaler()` automatisch standardisieren, sodass sie einen Mittelwert von 0 und eine Standardabweichung von 1 aufweisen.
- **Funktionsweise:** `fit_transform()` bestimmt den Mittelwert und die Standardabweichung und berechnet für jeden Wert den Z-Score: `(Wert − Mittelwert) / Standardabweichung`.
- **Wichtiger Unterschied:** `pandas.std()` verwendet standardmässig `ddof=1` (Division durch `n−1` bei der Varianzberechnung), während `StandardScaler()` `ddof=0` verwendet (Division durch `n`). Deshalb unterscheiden sich die Ergebnisse leicht.
- **Kontrolle:** `np.allclose()` prüft, ob zwei Berechnungen innerhalb kleiner numerischer Toleranzen übereinstimmen. Der erste Vergleich liefert normalerweise `False`, da unterschiedliche Standardabweichungen verwendet werden. Mit `std(ddof=0)` liefert der zweite Vergleich `True`.
- **Erkenntnis:** `ddof=0` sorgt dafür, dass die manuelle Berechnung dieselbe Standardabweichung wie scikit-learn verwendet. Die Ergebnisse stimmen dadurch praktisch überein.

In [ ]:
# Z-score Normalization of the variable 'mileage' (scikit-learn version)
from sklearn.preprocessing import StandardScaler                    #StandardScaler importieren: Werte auf Mittelwert 0 und Standardabweichung 1 standardisieren

# Fit the scaler and transform the variable
# (note the double brackets: scikit-learn expects a 2D input)
scaler = StandardScaler() #Scaler-Objekt für die Z-Score-Standardisierung erstellen
df_autoscout['mileage_scaled_z_sklearn'] = scaler.fit_transform(    #Standardisierte Kilometerstände in neuer Spalte speichern
    df_autoscout[['mileage']]).ravel()                              #fit_transform(): Mittelwert und Standardabweichung bestimmen und Werte standardisieren
                                                                    #[['mileage']]: Spalte als 2D-DataFrame übergeben (von sklearn erwartet)
                                                                    #ravel(): 2D-Ergebnis in ein eindimensionales Array für die neue Spalte umwandeln

# Note: pandas .std() divides by n-1, StandardScaler divides by n,
# so the results differ slightly
print(np.allclose(df_autoscout['mileage_scaled_z'],                 #Manuelle und sklearn-Standardisierung vergleichen
                  df_autoscout['mileage_scaled_z_sklearn']))        #allclose(): Werte innerhalb kleiner numerischer Toleranzen vergleichen
                                                                    #Erwartet False: pandas.std() verwendet ddof=1, StandardScaler ddof=0
                                                                    #Erkenntnis: Unterschiedliche Standardabweichungen führen zu leicht anderen Ergebnissen

# Check against the by-hand formula with the standard deviation
# divided by n (ddof=0)
z_ddof0 = (df_autoscout['mileage'] - df_autoscout['mileage'].mean()) / df_autoscout['mileage'].std(ddof=0) #Z-Score manuell mit derselben Standardabweichung wie sklearn berechnen
                                                                                                           #mean(): arithmetischen Mittelwert berechnen
                                                                                                           #std(ddof=0): Standardabweichung mit Division durch n statt n-1 berechnen
                                                                                                           #ddof: Freiheitsgradkorrektur; pandas verwendet standardmässig ddof=1

print(np.allclose(z_ddof0, df_autoscout['mileage_scaled_z_sklearn']))       #Manuelle Berechnung mit ddof=0 und sklearn vergleichen
                                                                            #Erwartet True: Beide verwenden dieselbe Berechnung

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu standardisierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_scaled_z_sklearn an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: mileage_scaled_z an den Namen der zuvor manuell standardisierten Spalte anpassen
#NICHTS ANPASSEN: StandardScaler(), fit_transform(), ravel(), mean(), std(ddof=0) und np.allclose()
#VORAUSSETZUNG: Die manuell standardisierte Spalte muss bereits existieren, damit der erste Vergleich funktioniert

# Transformation
In statistics, Data Transformation involves applying mathematical functions to data to meet the assumptions of statistical models, improve interpretability, or enhance the robustness of analysis

### Data Transformation: Logarithmic Transformation

- **Definition:** Die Logarithmus-Transformation ist ein Verfahren, bei dem numerische Werte mithilfe einer Logarithmusfunktion umgerechnet werden, um ihre Verteilung zu verändern.
- **Zweck:** Stark rechtsschiefe Verteilungen reduzieren, grosse Werte komprimieren und nichtlineare Zusammenhänge abschwächen, damit statistische Modelle die Daten besser verarbeiten können.
- **Formel:** `Y' = log(Y)` – jeder ursprüngliche Wert wird durch seinen natürlichen Logarithmus (Basis e) ersetzt.
- **Methode:** `np.log()` berechnet den natürlichen Logarithmus für jeden Wert einer numerischen Spalte. Die Ergebnisse werden in einer neuen Spalte gespeichert.
- **Voraussetzung:** Die Ausgangswerte müssen grösser als 0 sein. Bei `np.log(0)` entsteht `-inf` (negativ unendlich), bei negativen Werten `NaN`.
- **Erkenntnis:** Grosse Werte werden stärker komprimiert als kleine, wodurch eine rechtsschiefe Verteilung symmetrischer werden kann. Im Gegensatz zum Scaling verändert die Logarithmus-Transformation die Form der Verteilung. Eine Normalverteilung wird nicht garantiert.
- **Auswirkung auf Modelle:** Ein exponentieller Zusammenhang kann durch Logarithmieren der Zielvariable annähernd linear werden. Dadurch können systematische Muster in den Residuen (Abweichungen zwischen beobachteten und vorhergesagten Werten) reduziert werden.

In [ ]:
# Log-Transformation of the variable 'mileage'
df_autoscout['mileage_log'] = np.log(df_autoscout['mileage'])       #Kilometerstände logarithmieren und in neuer Spalte speichern
                                                                    #np.log(): natürlichen Logarithmus (Basis e) für jeden Wert berechnen
                                                                    #Voraussetzung: Werte > 0; bei 0 entsteht -inf, bei negativen Werten NaN

# Histogram of the variable 'mileage' and 'mileage_log'
ax = df_autoscout[['mileage', 'mileage_log']].hist(bins=25,                 #Originale und logarithmierte Kilometerstände als zwei Histogramme darstellen
                                                  figsize=(7, 3),           #figsize: Abbildungsgrösse in Zoll (Breite × Höhe)
                                                  color='steelblue')        #hist(): Histogramme erstellen; bins=25: Anzahl Intervalle
                                                                            #color: Balkenfarbe; ax speichert die Diagrammachsen
                                                                            #Erkenntnis: Logarithmierung kann Rechtsschiefe reduzieren und Verteilungsform verändern

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'Log(Mileage)']):          #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                            #flatten(): Achsenanordnung in 1D umwandeln; zip(): Elemente paarweise verbinden
    axis.set_ylim(bottom=0)                                                 #set_ylim(): y-Achse bei 0 beginnen lassen; Maximum automatisch bestimmen
    axis.set_xlabel(label)                                                  #set_xlabel(): x-Achse mit der jeweiligen Beschriftung versehen
    axis.set_ylabel('Frequency')                                            #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                                  #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu transformierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_log überall an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: ['Mileage', 'Log(Mileage)'] an die jeweiligen Achsenbeschriftungen anpassen
#OPTIONAL: bins=25, figsize=(7, 3) und color='steelblue' bei Bedarf ändern
#BEI VORGEGEBENER Y-GRENZE: axis.set_ylim(0, 1200) statt axis.set_ylim(bottom=0)
#NICHTS ANPASSEN: np.log(), hist(), flatten(), zip(), set_xlabel(), set_ylabel() und plt.show()
#VORAUSSETZUNG: Numerische Spalte mit ausschliesslich positiven Werten; numpy als np und matplotlib.pyplot als plt importiert

### Data Transformation: Square Root Transformation (SQRT)

- **Definition:** Die Quadratwurzel-Transformation (SQRT) ist ein Verfahren, bei dem numerische Werte durch ihre Quadratwurzel ersetzt werden, um die Verteilung der Daten zu verändern.
- **Zweck:** Grosse Werte komprimieren, rechtsschiefe Verteilungen reduzieren und den Einfluss hoher Werte bzw. Ausreisser abschwächen.
- **Formel:** `Y' = √Y` – jeder ursprüngliche Wert wird durch seine Quadratwurzel ersetzt (z. B. √100 = 10).
- **Methode:** `np.sqrt()` berechnet die Quadratwurzel jedes Werts einer numerischen Spalte. Die Ergebnisse werden in einer neuen Spalte gespeichert.
- **Voraussetzung:** Die Ausgangswerte müssen ≥ 0 sein. Nullwerte sind erlaubt (`√0 = 0`); negative Werte ergeben `NaN`.
- **Erkenntnis:** Grosse Werte werden stärker komprimiert als kleine, wodurch eine rechtsschiefe Verteilung symmetrischer werden kann. Die Verteilungsform kann sich verändern, eine Normalverteilung wird jedoch nicht garantiert.
- **Unterschied zur Logarithmus-Transformation:** SQRT ist bei grossen Werten weniger stark komprimierend als `np.log()` und kann im Gegensatz dazu auch Nullwerte verarbeiten.

In [ ]:
# SQRT-Transformation of the variable 'mileage'
df_autoscout['mileage_sqrt'] = np.sqrt(df_autoscout['mileage'])     #Quadratwurzel jedes Kilometerstands berechnen und in neuer Spalte speichern
                                                                    #np.sqrt(): Quadratwurzel jedes Werts berechnen (z. B. √100 = 10)
                                                                    #Voraussetzung: Werte >= 0; negative Werte ergeben NaN
                                                                    #Erkenntnis: Grosse Werte werden komprimiert; Rechtsschiefe kann abnehmen

# Histogram of the variable 'mileage' and 'mileage_sqrt'
ax = df_autoscout[['mileage', 'mileage_sqrt']].hist(bins=25,            #Originale und wurzeltransformierte Kilometerstände als zwei Histogramme darstellen
                                                   figsize=(7, 3),      #figsize: Abbildungsgrösse in Zoll (Breite × Höhe)
                                                   color='steelblue')   #hist(): Histogramme erstellen; bins=25: Anzahl Intervalle
                                                                        #color: Balkenfarbe; ax speichert die Diagrammachsen
                                                                        #Erkenntnis: SQRT kann die Verteilungsform verändern und Rechtsschiefe reduzieren

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'SQRT(Mileage)']):     #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                        #flatten(): Achsenanordnung in 1D umwandeln
                                                                        #zip(): Achsen und Beschriftungen paarweise verbinden
    axis.set_ylim(bottom=0)                                             #set_ylim(): y-Achse bei 0 beginnen lassen; obere Grenze automatisch bestimmen
    axis.set_xlabel(label)                                              #set_xlabel(): x-Achse mit der jeweiligen Beschriftung versehen
    axis.set_ylabel('Frequency')                                        #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                              #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu transformierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_sqrt überall an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: ['Mileage', 'SQRT(Mileage)'] an die jeweiligen Achsenbeschriftungen anpassen
#OPTIONAL: bins=25, figsize=(7, 3) und color='steelblue' bei Bedarf ändern
#BEI VORGEGEBENER Y-GRENZE: axis.set_ylim(0, 500) statt axis.set_ylim(bottom=0)
#NICHTS ANPASSEN: np.sqrt(), hist(), flatten(), zip(), set_xlabel(), set_ylabel() und plt.show()
#VORAUSSETZUNG: Numerische Spalte mit nichtnegativen Werten; numpy als np und matplotlib.pyplot als plt importiert

### Data Transformation: Box-Cox Transformation

- **Definition:** Die Box-Cox-Transformation ist ein Verfahren zur Umrechnung numerischer Werte, bei dem die geeignete Transformation anhand eines Parameters Lambda (λ) automatisch bestimmt wird.
- **Zweck:** Schiefe Verteilungen reduzieren, grosse Werte transformieren und die Daten einer Normalverteilung annähern.
- **Formel:** `Y' = (Y^λ − 1) / λ` für `λ ≠ 0`; bei `λ = 0` gilt `Y' = log(Y)`.
- **Methode:** `boxcox()` aus `scipy.stats` schätzt automatisch den optimalen Parameter λ und transformiert die Werte. Ziel der Schätzung ist eine möglichst gute Annäherung an eine Normalverteilung.
- **Parameter λ (Lambda):**
  - `λ = 0`: Logarithmus-Transformation (`log(Y)`).
  - `λ = 0.5`: Mit der Quadratwurzel-Transformation verwandt (`2 × (√Y − 1)`).
  - `λ = 1`: Entspricht `Y − 1` (Verschiebung ohne Veränderung der Verteilungsform).
- **Rückgabewerte:** `boxcox()` liefert die transformierten Werte und das geschätzte Lambda. Mit `_` kann Lambda ignoriert werden.
- **Voraussetzung:** Alle Ausgangswerte müssen strikt positiv sein (`Y > 0`). Nullwerte und negative Werte sind nicht erlaubt.
- **Erkenntnis:** Im Gegensatz zu `np.log()` und `np.sqrt()` wird die Transformation anhand der Daten automatisch angepasst. Dadurch kann Box-Cox eine schiefe Verteilung besser an eine Normalverteilung annähern; eine Normalverteilung wird jedoch nicht garantiert.

In [ ]:
# Import the boxcox function from scipy
from scipy.stats import boxcox                                          #boxcox() importieren: Box-Cox-Transformation zur Annäherung an eine Normalverteilung

# Box-Cox Transformation of the variable 'mileage'
df_autoscout['mileage_boxcox'], _ = boxcox(df_autoscout['mileage'])     #Kilometerstände transformieren und in neuer Spalte speichern
                                                                        #boxcox(): Lambda (λ) automatisch schätzen und Werte transformieren
                                                                        #Rückgabe: transformierte Werte und geschätztes Lambda
                                                                        #_: Lambda ignorieren, da nur die transformierten Werte benötigt werden
                                                                        #Voraussetzung: Alle Werte > 0; keine Nullwerte oder negativen Werte
                                                                        #Erkenntnis: λ=0 entspricht log(x); λ=0.5 ist mit √x verwandt; λ=1 entspricht x−1

# Histogram of the variable 'mileage' and 'mileage_boxcox'
ax = df_autoscout[['mileage', 'mileage_boxcox']].hist(bins=25,          #Originale und Box-Cox-transformierte Kilometerstände als zwei Histogramme darstellen
                                                     figsize=(7, 3),    #figsize: Abbildungsgrösse in Zoll (Breite × Höhe)
                                                     color='steelblue') #hist(): Histogramme erstellen; bins=25: Anzahl Intervalle
                                                                        #color: Balkenfarbe; ax speichert die Diagrammachsen
                                                                        #Erkenntnis: Box-Cox kann Schiefe reduzieren und Verteilungen symmetrischer machen
                                                                        #Eine Normalverteilung wird nicht garantiert

# Set the y-axis range for each subplot and add labels
for axis, label in zip(ax.flatten(), ['Mileage', 'Box-Cox(Mileage)']):  #Diagrammachsen und Beschriftungen paarweise durchlaufen
                                                                        #flatten(): Achsenanordnung in 1D umwandeln
                                                                        #zip(): Achsen und Beschriftungen paarweise verbinden
    axis.set_ylim(bottom=0)                                             #set_ylim(): y-Achse bei 0 beginnen lassen; obere Grenze automatisch bestimmen
    axis.set_xlabel(label)                                              #set_xlabel(): x-Achse mit der jeweiligen Beschriftung versehen
    axis.set_ylabel('Frequency')                                        #set_ylabel(): y-Achse beschriften (Anzahl Fahrzeuge je Intervall)

# Display the plot
plt.show()                                                              #Beide Histogramme anzeigen

#ANPASSEN: df_autoscout überall durch den verwendeten DataFrame ersetzen (z. B. df_apartments)
#ANPASSEN: mileage überall durch die zu transformierende numerische Spalte ersetzen (z. B. area)
#ANPASSEN: mileage_boxcox überall an den gewünschten Namen der neuen Spalte anpassen
#ANPASSEN: ['Mileage', 'Box-Cox(Mileage)'] an die jeweiligen Achsenbeschriftungen anpassen
#OPTIONAL: bins=25, figsize=(7, 3) und color='steelblue' bei Bedarf ändern
#BEI VORGEGEBENER Y-GRENZE: axis.set_ylim(0, 500) statt axis.set_ylim(bottom=0)
#NICHTS ANPASSEN: boxcox(), hist(), flatten(), zip(), set_xlabel(), set_ylabel() und plt.show()
#VORAUSSETZUNG: Numerische Spalte mit ausschliesslich positiven Werten; scipy und matplotlib.pyplot als plt verfügbar

## Combining & Organizing Data

### Reading Geocoded Data (CSV)

- **Definition:** Geocodierte Daten sind Datensätze mit geografischen Informationen, insbesondere Breitengrad (`lat`) und Längengrad (`lon`), die eine räumliche Zuordnung ermöglichen.
- **Zweck:** Geografische Informationen aus einer CSV-Datei einlesen, um sie anschliessend mit anderen Datensätzen kombinieren oder räumlich auswerten zu können.
- **Methode:** `pd.read_csv()` liest eine CSV-Datei ein und erstellt daraus einen pandas-DataFrame.
- **Wichtige Parameter:**
  - `sep=';'`: Semikolon als Spaltentrennzeichen verwenden.
  - `encoding='utf-8'`: Zeichenkodierung festlegen, damit Umlaute und Sonderzeichen korrekt eingelesen werden.
  - `./`: Aktuelles Arbeitsverzeichnis; kein zusätzlicher Unterordner erforderlich.
- **Wichtige Variablen:**
  - `offer_id`: Eindeutige Kennnummer eines Fahrzeugangebots.
  - `lat`: Geografischer Breitengrad (Nord-Süd-Position).
  - `lon`: Geografischer Längengrad (Ost-West-Position).
  - `bfs_number`: Offizielle Gemeindenummer des Bundesamts für Statistik.
  - `bfs_name`: Offizieller Gemeindename.
- **Erkenntnis:** Geocodierte Daten ermöglichen die geografische Zuordnung von Datensätzen. Über gemeinsame Identifikatoren (z. B. `offer_id`) können sie später mit anderen Daten kombiniert werden.

In [ ]:
# Meaning of variables
# offer_id: unique identifier of the offer on autoscout24.ch
# lat: geographical latitude
# lon: geographical longitude
# bfs_number: official municipality id
# bfs_name: official municipality name
#offer_id: eindeutige Kennnummer eines Fahrzeugangebots (möglicher Schlüssel zum Kombinieren von Daten)
#lat: geografischer Breitengrad (Nord-Süd-Position)
#lon: geografischer Längengrad (Ost-West-Position)
#bfs_number: offizielle Gemeindenummer des Bundesamts für Statistik (BFS)
#bfs_name: offizieller Gemeindename gemäss BFS

# Geocoded data (i.e. data with latitude and longitude)
df_geo = pd.read_csv('./autoscout24_data_geocoded.csv', #Geocodierte Fahrzeugdaten aus der CSV-Datei in einen neuen DataFrame einlesen
                     sep=';',                           #sep: Semikolon als Spaltentrennzeichen verwenden
                     encoding='utf-8')                  #encoding: UTF-8-Zeichenkodierung für Umlaute und Sonderzeichen verwenden
                                                        #pd.read_csv(): CSV-Datei einlesen und als pandas-DataFrame zurückgeben
                                                        #./: Datei liegt im aktuellen Arbeitsverzeichnis (kein Unterordner)

# Show data
df_geo.head() #head(): Standardmässig die ersten 5 Zeilen zur Kontrolle anzeigen

#ANPASSEN: './autoscout24_data_geocoded.csv' durch den tatsächlichen Dateinamen bzw. Dateipfad ersetzen
#ANPASSEN: sep=';' an das verwendete Trennzeichen anpassen (z. B. sep=',')
#ANPASSEN: encoding='utf-8' nur ändern, falls die Datei eine andere Zeichenkodierung verwendet
#OPTIONAL: df_geo durch einen anderen DataFrame-Namen ersetzen
#NICHTS ANPASSEN: pd.read_csv() und .head()
#VORAUSSETZUNG: import pandas as pd; CSV-Datei muss im angegebenen Verzeichnis existieren

### Combining Data: pd.merge()

- **Definition:** `pd.merge()` kombiniert zwei DataFrames anhand einer gemeinsamen Schlüsselspalte (Key), indem Datensätze mit übereinstimmenden Schlüsselwerten zusammengeführt werden
- **Zweck:** Informationen aus verschiedenen Datenquellen verbinden, bspw. Fahrzeugdaten mit geografischen Informationen (Breitengrad, Längengrad und Gemeinde)
- **Methode:** `df1.merge(df2, on='schlüsselspalte')` verbindet zwei DataFrames über die angegebene Schlüsselspalte.
- **Wichtige Parameter:**
  - `on='offer_id'`: Gemeinsame Schlüsselspalte, über welche die Datensätze verbunden werden. Sie muss in beiden DataFrames existieren
  - `how='inner'`: Nur Datensätze übernehmen, deren Schlüssel in beiden DataFrames vorkommt (Standard)
  - `how='left'`: Alle Zeilen des linken DataFrames behalten; fehlende Werte aus dem rechten DataFrame werden mit `NaN` ergänzt
  - `how='right'`: Alle Zeilen des rechten DataFrames behalten; fehlende Werte aus dem linken DataFrame werden mit `NaN` ergänzt
  - `how='outer'`: Alle Schlüsselwerte aus beiden DataFrames übernehmen; fehlende Informationen werden mit `NaN` ergänzt
- **Spaltenauswahl:** `df_geo[['offer_id', 'lat', 'lon', 'bfs_number', 'bfs_name']]` wählt gezielt die Spalten aus, die beim Zusammenführen übernommen werden sollen
- **Ergebnis:** Ein neuer DataFrame (`df2`), der die ursprünglichen Fahrzeugdaten und zusätzlich die geografischen Informationen enthält
- **Wichtig:** Fehlende Übereinstimmungen werden bei einem Inner Join ausgeschlossen. Doppelte Schlüsselwerte können dazu führen, dass sich die Anzahl der Zeilen erhöht
- **Erkenntnis:** `pd.merge()` entspricht dem JOIN-Prinzip aus SQL und ermöglicht die gezielte Anreicherung von Datensätzen über gemeinsame Schlüssel

In [ ]:
# Merge geo-information to the car data (the key is 'offer_id')
df2 = df_autoscout.merge(df_geo[['offer_id',  #Nur benötigte Spalten des zweiten DataFrames auswählen
                                'lat',        #Geografischer Breitengrad
                                'lon',        #Geografischer Längengrad
                                'bfs_number', #Offizielle Gemeindenummer
                                'bfs_name']], #Offizieller Gemeindename
                         on="offer_id")       #merge(): Beide DataFrames anhand der gemeinsamen Schlüsselspalte verbinden
                                              #on: Schlüsselspalte muss in beiden DataFrames vorhanden sein
                                              #Standard: how='inner' (nur übereinstimmende Schlüsselwerte übernehmen)
                                              #Erkenntnis: Fahrzeugdaten werden um geografische Informationen ergänzt

# Show data
df2[['offer_id',     #Eindeutige Angebotsnummer
     'type',         #Fahrzeugtyp bzw. Modell
     'price',        #Fahrzeugpreis
     'hp',           #Motorleistung in PS
     'price_per_hp', #Berechneter Preis pro PS
     'mileage',      #Kilometerstand
     'fuel_type',    #Treibstoffart
     'lat',          #Geografischer Breitengrad
     'lon',          #Geografischer Längengrad
     'bfs_number',   #Gemeindenummer
     'bfs_name']].head() #Gewünschte Spalten auswählen und die ersten 5 Zeilen anzeigen

#ANPASSEN: df_autoscout durch den ersten DataFrame ersetzen (Hauptdaten)
#ANPASSEN: df_geo durch den zweiten DataFrame ersetzen (zusätzliche Informationen)
#ANPASSEN: 'offer_id' durch die gemeinsame Schlüsselspalte ersetzen (z. B. 'web-scraper-order')
#ANPASSEN: ['offer_id', 'lat', 'lon', 'bfs_number', 'bfs_name'] an die benötigten Spalten des zweiten DataFrames anpassen
#ANPASSEN: Die Spaltenliste bei df2[['...']].head() an die tatsächlich vorhandenen und gewünschten Spalten anpassen
#OPTIONAL: how='left', how='right' oder how='outer' ergänzen, um die Join-Art zu ändern
#NICHTS ANPASSEN: .merge(), on= und .head() als Methoden bzw. Parameter
#VORAUSSETZUNG: Beide DataFrames müssen bereits existieren und die gemeinsame Schlüsselspalte enthalten

### Sorting Data: sort_values()

- **Definition:** `sort_values()` sortiert die Zeilen eines DataFrames anhand einer oder mehrerer Spalten.
- **Zweck:** Datensätze nach bestimmten Kriterien ordnen, beispielsweise Fahrzeuge nach Preis und Kilometerstand.
- **Methode:** `df.sort_values(by=['price', 'mileage'], ascending=False)`
- **Wichtige Parameter:**
  - `by=['price', 'mileage']`: Zuerst nach `price` sortieren; bei gleichem Preis nach `mileage`.
  - `ascending=True`: Aufsteigend sortieren (kleinste Werte zuerst; Standard).
  - `ascending=False`: Absteigend sortieren (grösste Werte zuerst).
  - `ascending=[False, True]`: Preis absteigend und Kilometerstand aufsteigend sortieren.
- **Ergebnis:** Ein sortierter DataFrame. Durch `df3 = df3.sort_values(...)` wird das Ergebnis wieder in `df3` gespeichert.
- **Erkenntnis:** Die Reihenfolge der Spalten in `by` bestimmt die Sortierpriorität. Weitere Spalten werden nur bei gleichen Werten der vorherigen Sortierspalten berücksichtigt.

In [ ]:
# Sorting data by 'price' and 'mileage' with highest price above
# (ascending=False)
df_autoscout = df_autoscout.sort_values(
    by=['price', 'mileage'],                                               #Nach Preis und Kilometerstand sortieren
    ascending=False                                                        #Beide Spalten absteigend: grösste Werte zuerst
)

# Show data
df_autoscout[['offer_id', 'type', 'price', 'mileage', 'hp']].head()        #Sortierte Daten anzeigen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: ['price', 'mileage'] durch die gewünschten Sortierspalten ersetzen
#ANPASSEN: ascending=True (aufsteigend) oder False (absteigend)
#OPTIONAL: ascending=[False, True] für unterschiedliche Sortierrichtungen
#NICHTS ANPASSEN: .sort_values(), by= und .head()

### Reshaping Data: stack() & unstack()

- **Definition:** Reshaping bezeichnet die Umstrukturierung eines DataFrames, ohne die eigentlichen Datenwerte zu verändern. Dabei werden Daten zwischen Spalten und Zeilen bzw. Indexebenen verschoben.
- **Zweck:** Daten von einer breiten (Wide Format) in eine gestapelte, längere Darstellung (Long Format) umwandeln und bei Bedarf wieder zurückführen.
- **stack():**
  - Verschiebt Spaltennamen in eine zusätzliche Indexebene und stapelt die zugehörigen Werte untereinander.
  - Aus einem DataFrame wird bei einfachen Spalten typischerweise eine Series mit einem MultiIndex (mehrstufiger Index).
  - Beispiel: 5 Zeilen × 4 Spalten → normalerweise 20 Werte untereinander.
- **unstack():**
  - Verschiebt eine Indexebene zurück in die Spalten.
  - Macht die Umstrukturierung durch `stack()` wieder rückgängig.
  - Bsp.: 20 gestapelte Werte → wieder 5 Zeilen × 4 Spalten.
- **MultiIndex:** Mehrstufiger Index, bei dem ein Wert zw. über den ursprünglichen Zeilenindex und den ursprünglichen Spaltennamen identifiziert wird.
- **Wichtige Erkenntnisse:**
  - `stack()` → Spalten werden zu einer zusätzlichen Indexebene.
  - `unstack()` → Eine Indexebene wird wieder zu Spalten.
  - Die Datenwerte werden nicht berechnet oder skaliert, sondern lediglich umstrukturiert.
  - Achtung: Fehlende Werte (`NaN`) können abhängig von der pandas-Version zw. den verwendeten Parametern beim Stacken entfallen.

In [ ]:
# Create a subset of the data (first 5 rows)
df_sub = df_autoscout[['type', 'mileage', 'price', 'hp']][:5]   #Teilmenge erstellen: 4 ausgewählte Spalten und die ersten 5 Zeilen
                                                                #[['...']]: Gewünschte Spalten auswählen
                                                                #[:5]: Erste 5 Zeilen auswählen (Positionen 0 bis 4)
print('Original shape')                                         #Überschrift für die ursprüngliche Tabellenstruktur ausgeben
print(df_sub, '\n')                                             #Originalen DataFrame anzeigen; '\n' erzeugt einen zusätzlichen Zeilenumbruch

# Reshape the data using .stack()
df_sub_stacked = df_sub.stack()                                 #stack(): Spalten in eine zusätzliche Indexebene verschieben (DataFrame → Series)
                                                                #Ergebnis: Zweistufiger MultiIndex aus ursprünglichem Zeilenindex und Spaltennamen
                                                                #Bei 5 Zeilen und 4 Spalten entstehen normalerweise 20 Werte untereinander
                                                                #Erkenntnis: Daten werden umstrukturiert, nicht inhaltlich verändert
print('Stacked')                                                #Überschrift für die gestapelte Darstellung ausgeben
print(df_sub_stacked, '\n')                                     #Gestapelte Werte mit MultiIndex anzeigen

# Reshape the data back using .unstack()
print('Unstacked (= back to original shape)')                   #Überschrift für die Rückumwandlung ausgeben
print(df_sub_stacked.unstack())                                 #unstack(): Innere Indexebene zurück in Spalten umwandeln (Series → DataFrame)
                                                                #Ergebnis: Ursprüngliche Tabellenstruktur mit 5 Zeilen und 4 Spalten
                                                                #Erkenntnis: stack() und unstack() ermöglichen die Umstrukturierung in beide Richtungen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: ['type', 'mileage', 'price', 'hp'] durch die gewünschten Spalten ersetzen
#ANPASSEN: [:5] an die gewünschte Anzahl Zeilen anpassen (z. B. [:10] für 10 Zeilen)
#NICHTS ANPASSEN: .stack(), .unstack() und die print()-Befehle
#VORAUSSETZUNG: DataFrame und ausgewählte Spalten müssen existieren
#ACHTUNG: Bei fehlenden Werten (NaN) kann das Verhalten von stack() je nach pandas-Version variieren

### Reshaping Data: melt()

- **Definition:** `pd.melt()` wandelt einen DataFrame vom breiten Format (Wide Format) ins lange Format (Long Format) um, indem mehrere Spalten untereinander angeordnet werden.
- **Zweck:** Daten umstrukturieren, damit sie beispielsweise einfacher analysiert, gruppiert oder visualisiert werden können.
- **Methode:** `pd.melt(df_sub, id_vars=['mileage'], value_vars=['price', 'hp'])`
- **Wichtige Parameter:**
  - `id_vars=['mileage']`: Spalten, die unverändert als Identifikationsvariablen erhalten bleiben. Ihre Werte werden für die neuen Zeilen wiederholt.
  - `value_vars=['price', 'hp']`: Spalten, die in Zeilen umgewandelt werden.
  - `var_name='variable'`: Name der neuen Spalte mit den ursprünglichen Spaltennamen (Standard: `variable`).
  - `value_name='value'`: Name der neuen Spalte mit den zugehörigen Werten (Standard: `value`).
- **Ergebnis:** Ein neuer DataFrame mit drei Spalten:
  - `mileage`: Ursprünglicher Kilometerstand (wird wiederholt).
  - `variable`: Ursprünglicher Spaltenname (`price` oder `hp`).
  - `value`: Zugehöriger Wert (Fahrzeugpreis oder Motorleistung).
- **Bsp.:** 5 Zeilen mit `mileage`, `price` und `hp` werden zu 10 Zeilen mit `mileage`, `variable` und `value`.
- **Unterschied zu stack():**
  - `stack()` verschiebt Spaltennamen in eine zusätzliche Indexebene und erzeugt bei einfachen Spalten typischerweise eine Series mit MultiIndex.
  - `melt()` wandelt Spalten in die normalen DataFrame-Spalten `variable` und `value` um. Die Identifikationsspalten bleiben erhalten.
- **Erkenntnis:** `melt()` verändert die Datenstruktur, nicht die eigentlichen Werte. Es findet keine Aggregation statt.

In [ ]:
# Create a subset of the data (first 5 rows)
df_sub = df_autoscout[['mileage', 'price', 'hp']][:5]       #Teilmenge erstellen: 3 ausgewählte Spalten und die ersten 5 Zeilen
                                                            #[['...']]: Gewünschte Spalten auswählen
                                                            #[:5]: Erste 5 Zeilen auswählen (Positionen 0 bis 4)

print('Original shape')                                     #Überschrift für die ursprüngliche Tabellenstruktur ausgeben
print(df_sub, '\n')                                         #Originalen DataFrame anzeigen; '\n' erzeugt einen zusätzlichen Zeilenumbruch

# Reshape the data using .melt()
print('Reshaped using .melt()')                                             #Überschrift für die umstrukturierte Darstellung ausgeben
print(pd.melt(df_sub, id_vars=['mileage'], value_vars=['price', 'hp']))     #melt(): DataFrame vom breiten ins lange Format umwandeln
                                                                            #id_vars=['mileage']: Diese Spalte beibehalten und Werte wiederholen
                                                                            #value_vars=['price', 'hp']: Diese Spalten untereinander anordnen
                                                                            #Ergebnis: Spalten 'mileage', 'variable' und 'value'
                                                                            #'variable': Enthält die ursprünglichen Spaltennamen 'price' und 'hp'
                                                                            #'value': Enthält die zugehörigen Preise bzw. PS-Werte
                                                                            #5 Zeilen × 2 value_vars = 10 Ergebniszeilen
                                                                            #Erkenntnis: Die Struktur verändert sich, die Daten werden nicht aggregiert
                                                                            #Unterschied zu stack(): melt() liefert einen DataFrame mit normalen Spalten

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: ['mileage', 'price', 'hp'] durch die gewünschten Ausgangsspalten ersetzen
#ANPASSEN: [:5] durch die gewünschte Anzahl Zeilen ersetzen (z. B. [:10])
#ANPASSEN: id_vars=['mileage'] durch die Spalten ersetzen, die erhalten bleiben sollen
#ANPASSEN: value_vars=['price', 'hp'] durch die Spalten ersetzen, die untereinander angeordnet werden sollen
#OPTIONAL: var_name='Merkmal', value_name='Wert' ergänzen, um die Ergebnisspalten umzubenennen
#NICHTS ANPASSEN: pd.melt() und die print()-Befehle
#VORAUSSETZUNG: import pandas as pd; df_autoscout und die ausgewählten Spalten müssen existieren

### Reshaping & Aggregating Data: pivot_table()

- **Definition:** `pd.pivot_table()` erstellt eine Pivot-Tabelle, indem Datensätze anhand bestimmter Merkmale gruppiert und numerische Werte mit einer Aggregationsfunktion zusammengefasst werden.
- **Zweck:** Kennzahlen verschiedener Gruppen vergleichen, beispielsweise den durchschnittlichen Fahrzeugpreis, Kilometerstand und die Motorleistung je Treibstoffart.
- **Methode:** `pd.pivot_table(df, index=['fuel_type'], values=['price', 'price_per_hp', 'hp', 'mileage'], aggfunc='mean')`
- **Wichtige Parameter:**
  - `index=['fuel_type']`: Gruppierungsspalte; jede Treibstoffart erhält eine eigene Zeile.
  - `values=['price', 'price_per_hp', 'hp', 'mileage']`: Numerische Spalten, deren Werte zusammengefasst werden.
  - `aggfunc='mean'`: Berechnet den Mittelwert pro Gruppe (Standard).
  - `aggfunc='sum'`: Berechnet die Summe pro Gruppe.
  - `aggfunc='count'`: Zählt die nicht fehlenden Werte pro Gruppe.
  - `aggfunc={'price': 'mean', 'hp': 'max'}`: Unterschiedliche Aggregationsfunktionen für einzelne Spalten festlegen.
  - `columns=['spalte']`: Optional eine zweite Gruppierungsvariable verwenden, deren Ausprägungen zu Spalten werden.
- **Rundung und Formatierung:**
  - `.round(2)`: Numerische Werte auf zwei Dezimalstellen runden.
  - `.map(lambda x: f"{x:.2f}" if isinstance(x, (int, float)) else x)`: Zahlen mit genau zwei Nachkommastellen inklusive nachgestellter Nullen darstellen.
  - **Achtung:** Durch die Formatierung mit `f"{x:.2f}"` werden Zahlen in Text umgewandelt. Für weitere Berechnungen besser die numerische Pivot-Tabelle beibehalten.
- **Ergebnis:** Eine Tabelle mit einer Zeile je Treibstoffart und den aggregierten Kennzahlen in separaten Spalten.
- **Unterschied zu melt() und stack():**
  - `melt()`: Mehrere Spalten untereinander anordnen, ohne Werte zu aggregieren.
  - `stack()`: Spalten in eine zusätzliche Indexebene verschieben, ohne Werte zu aggregieren.
  - `pivot_table()`: Werte gruppieren und mittels Aggregationsfunktionen zusammenfassen.
- **Erkenntnis:** Pivot-Tabellen ermöglichen den Vergleich von Kennzahlen zwischen Gruppen. Im Gegensatz zu einfachen Umstrukturierungen werden mehrere Datensätze zu aggregierten Ergebnissen verdichtet.

In [ ]:
# Create a pivot table with the mean values per fuel type
pivot_table = pd.pivot_table(                                               #pivot_table(): Daten nach Gruppen zusammenfassen und Kennzahlen aggregieren
    df_autoscout[['mileage', 'price', 'price_per_hp', 'hp', 'fuel_type']],  #Benötigte Spalten auswählen
    index=['fuel_type'],                                                    #index: Gruppierungsspalte; eine Zeile pro Treibstoffart
    values=['price',                                                        #price: Fahrzeugpreis auswerten
            'price_per_hp',                                                 #price_per_hp: Preis pro PS auswerten
            'hp',                                                           #hp: Motorleistung in PS auswerten
            'mileage'],                                                     #mileage: Kilometerstand auswerten
    aggfunc='mean').round(2)                                                #aggfunc='mean': Mittelwert je Gruppe berechnen; round(2): Auf 2 Dezimalstellen runden
                                                                            #Erkenntnis: Alle Fahrzeuge derselben Treibstoffart werden zu einer Zeile zusammengefasst
                                                                            #NaN-Werte werden bei der Mittelwertberechnung ignoriert

# Format the values to 2 decimal places with trailing zeros
pivot_table = pivot_table.map(                                              #map(): Funktion auf jeden einzelnen Tabellenwert anwenden
    lambda x: f"{x:.2f}" if isinstance(x, (int, float)) else x)             #lambda x: Jeden Wert einzeln verarbeiten
                                                                            #isinstance(): Prüfen, ob der Wert eine Ganzzahl oder Dezimalzahl ist
                                                                            #f"{x:.2f}": Genau 2 Nachkommastellen anzeigen (z. B. 15000.00)
                                                                            #else x: Andere Werte unverändert übernehmen
                                                                            #ACHTUNG: Formatierte Zahlen werden zu Text (str)
                                                                            #Voraussetzung: pandas >= 2.1 für DataFrame.map()

# Display the pivot table
pivot_table                                                                 #Pivot-Tabelle mit durchschnittlichen Kennzahlen je Treibstoffart anzeigen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: Spaltenliste df_autoscout[['...']] an die benötigten Spalten anpassen
#ANPASSEN: index=['fuel_type'] durch die gewünschte Gruppierungsspalte ersetzen
#ANPASSEN: values=['price', 'price_per_hp', 'hp', 'mileage'] durch die auszuwertenden numerischen Spalten ersetzen
#ANPASSEN: aggfunc='mean' bei Bedarf durch 'sum', 'count', 'min' oder 'max' ersetzen
#OPTIONAL: aggfunc={'price': 'mean', 'hp': 'max'} für unterschiedliche Funktionen pro Spalte
#OPTIONAL: columns=['spalte'] für eine zusätzliche Gruppierung nach Spalten
#OPTIONAL: .round(2) für eine andere Anzahl Dezimalstellen anpassen
#OPTIONAL: Den .map()-Block weglassen, wenn die Ergebnisse numerisch bleiben sollen
#NICHTS ANPASSEN: pd.pivot_table(), index=, values= und aggfunc= als Funktion bzw. Parameter
#VORAUSSETZUNG: import pandas as pd; df_autoscout und alle verwendeten Spalten müssen existieren

# Ergänzung
## Ab hier alle Methoden aus V4 Folien Part 2, die nicht behandelt wurden anhand Beispielaufgaben

# Ergänzung – Fehlende Methoden aus V4 Part II

## 1. Data Cleansing: Missing Values – Imputation

- **Definition:** Imputation bezeichnet das Schätzen und Ersetzen fehlender Werte (`NaN`) durch geeignete Ersatzwerte, anstatt die betroffenen Datensätze vollständig zu löschen.
- **Zweck:** Möglichst viele Datensätze erhalten und fehlende Informationen so behandeln, dass statistische Analysen weiterhin möglich sind.
- **Methoden:**
  - `.isna().sum()`: Anzahl fehlender Werte pro Spalte bestimmen.
  - `.fillna(wert)`: Fehlende Werte durch einen festgelegten Wert ersetzen.
  - `.fillna(df['spalte'].mean())`: Fehlende numerische Werte durch den Mittelwert ersetzen.
  - `.fillna(df['spalte'].median())`: Fehlende numerische Werte durch den Median ersetzen; bei Ausreissern häufig robuster.
  - `.fillna(df['spalte'].mode()[0])`: Fehlende Werte durch den häufigsten Wert ersetzen, beispielsweise bei Kategorien.
  - `.dropna()`: Zeilen mit fehlenden Werten entfernen (bereits im Spick vorhanden).
- **Bsp.:** Enthält eine Spalte die Werte `5`, `NaN` und `17`, wird der fehlende Wert bei Mittelwert-Imputation durch `11` ersetzt.
- **Unterschied Imputation vs. Removal:**
  - Imputation ersetzt fehlende Werte und erhält die Datensätze.
  - Removal entfernt Datensätze mit fehlenden Werten und reduziert dadurch die Datenmenge.
- **Erkenntnis:** Imputation erhält Beobachtungen, kann aber die Verteilung und Zusammenhänge zwischen Variablen verändern. Die geeignete Methode hängt von der Datenstruktur und dem Mechanismus fehlender Werte ab.

In [ ]:
# Imputation of missing values using the mean
df_imp = df_apartments[['area', 'price']].copy()                                #Teilmenge kopieren, damit die ursprünglichen Daten unverändert bleiben
                                                                                #copy(): Eigenständigen DataFrame zur Bearbeitung erstellen

# Count missing values before imputation
print('Missing values before imputation:')
print(df_imp.isna().sum())                                                      #isna(): Fehlende Werte erkennen; sum(): Anzahl je Spalte zählen

# Replace missing values with the mean
df_imp['area'] = pd.to_numeric(df_imp['area'], errors='coerce').astype(float)   #Fläche in numerische Werte umwandeln
                                                                                #errors='coerce': Ungültige Zahlen als NaN behandeln
                                                                                #astype(float): Auch Dezimalwerte bei der Imputation erlauben
df_imp['area'] = df_imp['area'].fillna(df_imp['area'].mean())                   #Fehlende Flächen durch den Durchschnitt aller vorhandenen Flächen ersetzen
                                                                                #mean(): Mittelwert ohne NaN berechnen
                                                                                #fillna(): Fehlende Werte durch diesen Mittelwert ersetzen

# Count missing values after imputation
print('Missing values after imputation:')
print(df_imp.isna().sum())                                                      #Kontrollieren, wie viele fehlende Werte noch vorhanden sind

# Show data
df_imp.head() #Erste fünf Zeilen der bearbeiteten Tabelle anzeigen

#ANPASSEN: df_apartments durch den verwendeten DataFrame ersetzen
#ANPASSEN: ['area', 'price'] durch die gewünschten Spalten ersetzen
#ANPASSEN: 'area' durch die numerische Spalte ersetzen, deren fehlende Werte ergänzt werden sollen
#OPTIONAL: .median() statt .mean() verwenden, wenn Ausreisser den Mittelwert stark beeinflussen
#OPTIONAL: df_imp['area'].fillna(0) verwenden, wenn 0 ein fachlich sinnvoller Ersatzwert ist
#NICHTS ANPASSEN: .copy(), .isna(), .sum(), .fillna() und .head()
#VORAUSSETZUNG: import pandas as pd; die ausgewählten Spalten müssen existieren
#ACHTUNG: Wenn die ursprünglichen Daten bereits mit dropna() bereinigt wurden, gibt es möglicherweise keine fehlenden Werte mehr
#ACHTUNG: Wenn alle Werte der Spalte fehlen, ist auch der Mittelwert NaN; die Imputation benötigt dann eine andere Strategie

## 2. Data Cleansing: MCAR, MAR und MNAR

- **Definition:** MCAR, MAR und MNAR beschreiben unterschiedliche Mechanismen, warum Werte in einem Datensatz fehlen. Die Unterscheidung ist wichtig, weil ein falscher Umgang mit fehlenden Werten statistische Ergebnisse verzerren kann

- **MCAR – Missing Completely At Random:**
  - Werte fehlen vollständig zufällig
  - Das Fehlen hängt weder vom fehlenden Wert selbst noch von anderen Variablen ab
  - Bsp.: Ein zufälliger technischer Fehler führt dazu, dass einzelne Messwerte verloren gehen
  - Das Entfernen solcher Datensätze verursacht unter geeigneten Voraussetzungen keine systematische Verzerrung, reduziert aber die Datenmenge

- **MAR – Missing At Random:**
  - Das Fehlen hängt von anderen beobachteten Variablen ab, nicht zusätzlich vom fehlenden Wert selbst, wenn diese Variablen berücksichtigt werden
  - Bsp.: Ältere Personen beantworten eine bestimmte Umfragefrage seltener als jüngere Personen
  - Einfaches Entfernen kann zu verzerrten Ergebnissen führen; beobachtete Einflussfaktoren sollten berücksichtigt werden

- **MNAR – Missing Not At Random:**
  - Das Fehlen hängt vom fehlenden Wert selbst ab und möglicherweise zusätzlich von anderen Variablen
  - Bsp.: Personen mit sehr tiefem Einkommen geben ihr Einkommen seltener an
  - Besonders problematisch, da selbst anhand der beobachteten Daten die fehlenden Werte schwer zuverlässig geschätzt werden können

- **Erkenntnis:** MCAR bedeutet vollständig zufälliges Fehlen, MAR bedeutet von beobachteten Variablen abhängiges Fehlen und MNAR bedeutet vom fehlenden Wert selbst abhängiges Fehlen. Der Mechanismus lässt sich nicht allein durch das Zählen von NaN-Werten sicher bestimmen

In [ ]:
# Examine missing values in the apartment data
df_missing = df_apartments[['rooms', 'area', 'price']].copy()                   #Relevante Merkmale in einen separaten DataFrame kopieren

# Count missing values per variable
print('Missing values per variable:')
print(df_missing.isna().sum())                                                  #Anzahl fehlender Werte pro Spalte anzeigen

# Calculate percentage of missing values
print('Percentage of missing values:')
print((df_missing.isna().mean() * 100).round(2))                                #isna(): Fehlend=True; mean(): Anteil; *100: Prozent; round(2): Runden

# Examine whether missing prices vary by number of rooms
missing_by_rooms = df_missing.groupby('rooms')['price'].apply(
    lambda x: x.isna().mean() * 100
)                                                                               #Fehlenden Preisanteil pro Zimmerkategorie berechnen
                                                                                #groupby('rooms'): Wohnungen nach Zimmerzahl gruppieren
                                                                                #apply(lambda ...): Für jede Gruppe separat den Anteil fehlender Preise berechnen

print('Missing prices by number of rooms (%):')
print(missing_by_rooms.round(2))                                                #Prozentanteile auf zwei Nachkommastellen runden

#ANPASSEN: df_apartments und die Spalten ['rooms', 'area', 'price'] an deine Daten anpassen
#ANPASSEN: 'rooms' an die vermutete Einflussvariable und 'price' an die Spalte mit fehlenden Werten anpassen
#NICHTS ANPASSEN: .isna(), .mean(), .groupby(), .apply() und .round()
#VORAUSSETZUNG: DataFrame und die verwendeten Spalten müssen existieren
#ACHTUNG: Unterschiedliche Fehlenden-Anteile pro Gruppe können auf einen Zusammenhang hindeuten, beweisen aber weder MAR noch MNAR

## 3. Data Cleansing: Outliers & Measurement Errors

- **Outlier (Ausreisser):** Beobachtung, die deutlich von den übrigen Werten eines Datensatzes abweicht.
- **Measurement Error (Messfehler):** Fehlerhaft erfasster oder gemessener Wert, beispielsweise durch Sensorfehler, Tippfehler oder falsche Einheiten.
- **Unterschied:** Ein Ausreisser kann ein echter Extremwert oder ein Messfehler sein. Nicht jeder Ausreisser ist automatisch falsch.
- **Beispiele aus der Vorlesung:**
  - Eine Person über 105 Jahre ist ein ungewöhnlicher, aber grundsätzlich möglicher Wert.
  - Eine zwölfjährige verwitwete Person ist auffällig und könnte auf einen Erfassungsfehler hinweisen.
- **Mögliche Verfahren zur Ausreissererkennung:**
  - Boxplots zur grafischen Identifikation extremer Werte.
  - Quartile und Interquartilsabstand (IQR) zur Identifikation statistisch auffälliger Werte.
  - Prüfung anhand fachlicher Regeln und Plausibilitätsgrenzen.
- **IQR-Methode:** Werte unter `Q1 − 1.5 × IQR` oder über `Q3 + 1.5 × IQR` werden als potenzielle Ausreisser markiert.
- **Erkenntnis:** Ausreisser können statistische Analysen stark beeinflussen. Sie sollten zuerst untersucht und nur bei begründeten Fehlern entfernt oder korrigiert werden.

In [ ]:
# Detect potential outliers using the interquartile range (IQR)
df_outliers = df_autoscout[['offer_id', 'price', 'mileage']].copy()             #Benötigte Fahrzeugdaten kopieren
                                                                                #Originaldaten unverändert lassen

# Calculate quartiles and IQR
prices = pd.to_numeric(df_outliers['price'], errors='coerce')                   #Fahrzeugpreise in numerische Werte umwandeln

q1 = prices.quantile(0.25)                                                      #Q1: 25. Perzentil berechnen
q3 = prices.quantile(0.75)                                                      #Q3: 75. Perzentil berechnen
iqr = q3 - q1                                                                   #IQR: Abstand zwischen oberem und unterem Quartil

# Define outlier boundaries
lower_bound = q1 - 1.5 * iqr                                                    #Untere Grenze für potenzielle Ausreisser
upper_bound = q3 + 1.5 * iqr                                                    #Obere Grenze für potenzielle Ausreisser

# Identify potential outliers
outlier_mask = ((prices < lower_bound) | (prices > upper_bound)).fillna(False)  #Werte ausserhalb der Grenzen markieren
                                                                                #| bedeutet ODER; ein erfülltes Kriterium genügt
                                                                                #fillna(False): Fehlende Preise nicht als Ausreisser markieren

df_outliers_found = df_outliers.loc[outlier_mask]                               #Nur markierte Datensätze auswählen

# Show results
print('Anzahl potenzieller Ausreisser:', len(df_outliers_found))                #Anzahl auffälliger Fahrzeuge ausgeben
df_outliers_found.head()                                                        #Erste fünf auffällige Datensätze anzeigen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: 'price' überall durch die numerische Spalte ersetzen, die geprüft werden soll
#ANPASSEN: ['offer_id', 'price', 'mileage'] an die gewünschten Anzeigespalten anpassen
#OPTIONAL: Faktor 1.5 für die Grenzen anpassen, sofern die Aufgabe andere Grenzwerte vorgibt
#NICHTS ANPASSEN: .quantile(0.25), .quantile(0.75), .loc[] und len()
#VORAUSSETZUNG: Die betrachtete Spalte enthält numerische Werte
#ERKENNTNIS: Statistische Ausreisser sind nicht automatisch Messfehler und werden hier nicht gelöscht

### Outliers – Ausreisser und bestimmte Werte ausschliessen

**Zweck:** Erkannte Ausreisser oder bestimmte Datensätze gezielt aus einer Analyse ausschliessen. Der ursprüngliche DataFrame bleibt dabei unverändert.

| Methode | Erklärung |
|---|---|
| `df.loc[~outlier_mask]` | Alle zuvor mittels IQR erkannten Ausreisser ausschliessen. |
| `df.drop(index=prices.idxmax())` | Datensatz mit dem höchsten Preis ausschliessen. |
| `df[prices != 12990]` | Alle Datensätze mit dem Preis 12990 ausschliessen. |
| `df[~prices.isin([12990, 9999])]` | Mehrere bestimmte Preise gleichzeitig ausschliessen. |
| `df[~prices.between(10000, 15000)]` | Alle Preise zwischen 10000 und 15000 ausschliessen, inklusive Grenzen. |
| `df[prices <= 10000]` | Nur Preise bis einschliesslich 10000 behalten. |
| `df[df['offer_id'] != 'A123']` | Einen Datensatz anhand einer bestimmten ID ausschliessen. |
| `df[~df['offer_id'].isin(['A123', 'A456'])]` | Mehrere Datensätze anhand ihrer IDs ausschliessen. |

**Wichtige Methoden:**
- **`idxmax()`:** Ermittelt den Index des ersten höchsten Werts.
- **`drop(index=...)`:** Entfernt eine Zeile anhand ihres Index.
- **`!=`:** Schliesst alle Datensätze mit einem bestimmten Wert aus.
- **`isin([...])`:** Prüft, ob ein Wert in einer Liste enthalten ist.
- **`between(min, max)`:** Prüft, ob ein Wert innerhalb eines Intervalls liegt.
- **`~`:** Kehrt eine Bedingung um (NICHT).
- **`copy()`:** Erstellt eine unabhängige Kopie des gefilterten DataFrames.

**Wichtig:**
- `idxmax()` + `drop()` entfernt nur eine Zeile, auch bei mehreren identischen Maximalwerten.
- `!=` und `~isin()` entfernen alle Datensätze mit den angegebenen Werten.
- Die IQR-Methode erkennt potenzielle Ausreisser automatisch; Wertfilter schliessen gezielt definierte Werte aus.
- Fehlende Werte (NaN) und deren Behandlung beim Filtern beachten.
- **Ausreisser sind nicht automatisch Datenfehler!** Ein Ausschluss muss fachlich begründet sein.

**Erkenntnis:** Ausreisser können anhand statistischer Grenzen, einzelner Werte, Wertebereiche oder eindeutiger IDs aus einer Analyse ausgeschlossen werden.

In [ ]:
# OUTLIERS – AUSREISSER UND BESTIMMTE WERTE AUSSCHLIESSEN
# 1. Alle mittels IQR erkannten Ausreisser ausschliessen
df_ohne_iqr = df_outliers.loc[~outlier_mask].copy()                             #Alle nicht als Ausreisser markierten Datensätze behalten
                                                                                #~: Boolesche Maske umkehren
                                                                                #outlier_mask: Bereits berechnete IQR-Ausreissermaske
# 2. Datensatz mit dem höchsten Wert ausschliessen
df_ohne_max = df_outliers.drop(index=prices.idxmax())                           #Zeile mit dem höchsten Preis entfernen
                                                                                #idxmax(): Index des höchsten Werts ermitteln
                                                                                #drop(index=...): Entsprechende Zeile entfernen
# 3. Bestimmten Wert ausschliessen
df_ohne_wert = df_outliers.loc[prices != 12990].copy()                          #Alle Datensätze mit Preis 12990 ausschliessen

# 4. Mehrere bestimmte Werte ausschliessen
df_ohne_mehrere = df_outliers.loc[~prices.isin([12990, 9999])].copy()           #Preise 12990 und 9999 ausschliessen
                                                                                #isin(): Prüfen, ob ein Preis in der Liste enthalten ist
# 5. Gesamten Wertebereich ausschliessen
df_ohne_bereich = df_outliers.loc[~prices.between(10000, 15000)].copy()         #Alle Preise zwischen 10000 und 15000 ausschliessen
                                                                                #between(): Intervall inklusive Grenzen prüfen
# 6. Nur Werte unter einem Grenzwert behalten
df_unter_grenze = df_outliers.loc[prices <= 10000].copy()                       #Nur Preise bis einschliesslich 10000 behalten

# 7. Bestimmten Datensatz anhand seiner ID ausschliessen
df_ohne_id = df_outliers[df_outliers['offer_id'] != 'A123'].copy()              #Datensatz mit der angegebenen ID ausschliessen

# 8. Mehrere Datensätze anhand ihrer IDs ausschliessen
df_ohne_ids = df_outliers[~df_outliers['offer_id'].isin(['A123', 'A456'])].copy() #Mehrere IDs gleichzeitig ausschliessen

# 9. Ergebnisse vergleichen
print('Original:', len(df_outliers))                                            #Anzahl ursprünglicher Datensätze
print('Ohne IQR-Ausreisser:', len(df_ohne_iqr))                                 #Anzahl nach IQR-Bereinigung
print('Ohne Maximum:', len(df_ohne_max))                                        #Anzahl nach Ausschluss des Maximums

#ANPASSEN: df_outliers an den verwendeten DataFrame anpassen
#ANPASSEN: prices an die zuvor definierte numerische Spalte anpassen
#ANPASSEN: 12990, 9999, 10000 und 15000 an die gewünschten Werte anpassen
#ANPASSEN: 'offer_id' und die Beispiel-IDs an die vorhandenen Daten anpassen
#VORAUSSETZUNG: df_outliers, prices und outlier_mask wurden im vorherigen IQR-Code erstellt
#ACHTUNG: idxmax() benötigt mindestens einen gültigen numerischen Wert
#ACHTUNG: Fehlende Werte können je nach Filter ein- oder ausgeschlossen werden
#ACHTUNG: Ausreisser nur mit fachlicher Begründung dauerhaft entfernen
#ERKENNTNIS: ~outlier_mask entfernt erkannte Ausreisser; !=, isin() und between() schliessen gezielt Werte aus

## 4. String Manipulation: Additional String Methods

- **Definition:** String-Manipulation bezeichnet das Bearbeiten, Bereinigen und Analysieren von Zeichenketten (Texten).
- **Zweck:** Schreibweisen vereinheitlichen, störende Zeichen entfernen, Textteile extrahieren, Suchmuster erkennen und Zeichenketten für Analysen aufbereiten.
- **Methoden zur Gross-/Kleinschreibung:**
  - `.str.lower()`: Gesamten Text in Kleinbuchstaben umwandeln.
  - `.str.upper()`: Gesamten Text in Grossbuchstaben umwandeln.
  - `.str.capitalize()`: Ersten Buchstaben grossschreiben und nachfolgende Buchstaben kleinschreiben.
- **Methoden zur Bereinigung von Leerraum:**
  - `.str.lstrip()`: Leerraum am Anfang eines Textes entfernen.
  - `.str.rstrip()`: Leerraum am Ende eines Textes entfernen.
  - `.str.strip()`: Leerraum am Anfang und Ende entfernen.
- **Methoden zur Verarbeitung von Textmustern:**
  - `.str.contains('SUV')`: Prüfen, ob ein Text ein bestimmtes Muster enthält; Ergebnis `True` oder `False`.
  - `.str.replace('alt', 'neu')`: Einen Textbestandteil durch einen anderen ersetzen.
  - `.str.split(' ')`: Text anhand eines Trennzeichens in mehrere Teile aufteilen.
  - `.str.count('a')`: Anzahl Vorkommen eines Musters pro Zeichenkette zählen.
  - `.str.len()`: Anzahl Zeichen inklusive Leerzeichen bestimmen.
- **Subset Strings:** Mit `.loc[]` und `.str.contains()` können ausschliesslich Datensätze ausgewählt werden, die ein bestimmtes Muster enthalten.
- **Wichtige Parameter:**
  - `regex=False`: Bei `.str.replace()` einen wörtlichen Text statt eines regulären Ausdrucks ersetzen.
  - `case=False`: Bei `.str.contains()` Gross-/Kleinschreibung ignorieren.
  - `na=False`: Fehlende Texte bei `.str.contains()` als `False` behandeln.
  - `n=1`: Bei `.str.split()` höchstens einmal aufteilen.
- **Erkenntnis:** String-Methoden verarbeiten die Werte einer Textspalte elementweise. Sie verändern bestehende Daten nur dann dauerhaft, wenn das Ergebnis wieder in einer Spalte gespeichert wird.

In [ ]:
# Create a subset of text data
df_str = df_autoscout[['type']].head(5).copy()                              #Erste fünf Fahrzeugbezeichnungen auswählen und kopieren
                                                                            #copy(): Ursprüngliche Fahrzeugdaten unverändert lassen

# Manage letter case
df_str['lower'] = df_str['type'].str.lower()                                #Alle Buchstaben in Kleinbuchstaben umwandeln
df_str['upper'] = df_str['type'].str.upper()                                #Alle Buchstaben in Grossbuchstaben umwandeln
df_str['capitalized'] = df_str['type'].str.capitalize()                     #Nur ersten Buchstaben gross-, Rest kleinschreiben

# Manage white space
df_str['left_stripped'] = df_str['type'].str.lstrip()                       #Leerraum nur am Textanfang entfernen
df_str['right_stripped'] = df_str['type'].str.rstrip()                      #Leerraum nur am Textende entfernen
df_str['stripped'] = df_str['type'].str.strip()                             #Leerraum am Anfang und Ende entfernen

# Replace text
df_str['replaced'] = df_str['type'].str.replace(
    'SUV', 'SPORT UTILITY VEHICLE', regex=False)                            #Zeichenfolge SUV durch einen anderen Text ersetzen
                                                                            #regex=False: Nach exaktem Text suchen, nicht nach Regex-Muster

# Split strings
df_str['split'] = df_str['type'].str.split(' ', n=1)                        #Text beim ersten Leerzeichen in maximal zwei Teile aufteilen
                                                                            #str.split(): Gibt pro Zeile eine Liste mit den Textteilen zurück

# Count patterns
df_str['count_digits'] = df_str['type'].str.count(r'\d')                    #Anzahl Ziffern pro Fahrzeugbezeichnung zählen
                                                                            #\d: Regex-Muster für eine einzelne Ziffer

# Subset strings based on a pattern
df_matches = df_str.loc[
    df_str['type'].str.contains('SUV', case=False, na=False)
]                                                                           #Nur Fahrzeugbezeichnungen behalten, die SUV enthalten
                                                                            #case=False: Gross-/Kleinschreibung ignorieren; na=False: Fehlende Werte ausschliessen

# Show results
display(df_str)                                                             #Alle neu erzeugten Textspalten anzeigen
display(df_matches)                                                         #Nur Fahrzeugbezeichnungen mit passendem Suchmuster anzeigen

#ANPASSEN: df_autoscout und 'type' durch den verwendeten DataFrame und die Textspalte ersetzen
#ANPASSEN: 'SUV' und 'SPORT UTILITY VEHICLE' durch den gesuchten und den neuen Text ersetzen
#ANPASSEN: Das Muster r'\d' bei str.count() an die gewünschte Suche anpassen
#ANPASSEN: ' ' bei str.split() an das verwendete Trennzeichen anpassen
#OPTIONAL: n=1 bei str.split() ändern oder entfernen, um weitere Textteile zu erzeugen
#NICHTS ANPASSEN: .str.lower(), .str.upper(), .str.capitalize(), .str.strip(), .str.replace(), .str.split() und .str.count()
#VORAUSSETZUNG: Die ausgewählte Spalte enthält Textwerte
#ACHTUNG: capitalize() verändert auch Grossbuchstaben innerhalb eines Textes, z. B. BMW wird zu Bmw

## 5. Date Formatting: datetime and pandas

- **Definition:** Date Formatting bezeichnet die Umwandlung und Darstellung von Datums- und Zeitangaben in ein gewünschtes Format.
- **Zweck:** Datumswerte korrekt interpretieren, vereinheitlichen, sortieren und für zeitbasierte Analysen aufbereiten.
- **Time Series (Zeitreihe):** Folge von Datenpunkten, die in zeitlicher Reihenfolge erfasst, dargestellt oder analysiert werden.
- **Methoden:**
  - `datetime.now()`: Aktuelles Datum und aktuelle Uhrzeit ermitteln.
  - `.strftime('%Y-%m-%d')`: Ein Datum als Text in einem bestimmten Format ausgeben.
  - `pd.to_datetime()`: Vorhandene Textwerte in echte pandas-Datumswerte umwandeln.
  - `.dt.year`: Jahr aus einer Datumsspalte extrahieren.
  - `.dt.month`: Monat aus einer Datumsspalte extrahieren.
  - `.dt.day`: Tag aus einer Datumsspalte extrahieren.
  - `.dt.strftime()`: Alle Werte einer Datumsspalte formatiert als Text ausgeben.
- **Wichtige Formatcodes:**
  - `%Y`: Jahr mit vier Ziffern, beispielsweise 2026.
  - `%m`: Monat mit zwei Ziffern, beispielsweise 10.
  - `%d`: Tag mit zwei Ziffern, beispielsweise 17.
  - `%H`: Stunde im 24-Stunden-Format.
  - `%M`: Minute.
  - `%S`: Sekunde.
- **Beispiel:** `2026-10-17 13:45:20` kann mit `strftime('%d.%m.%Y')` als `17.10.2026` dargestellt werden.
- **Unterschied:** `pd.to_datetime()` erzeugt echte Datumswerte, während `strftime()` daraus formatierte Zeichenketten erzeugt.
- **Erkenntnis:** Für Berechnungen, Sortierungen und Zeitreihenanalysen sollten Datumswerte möglichst als `datetime` gespeichert bleiben. Formatierte Strings dienen vor allem der Darstellung.

In [ ]:
# Convert existing timestamp strings to datetime
df_dates = df_apartments[['timestamp']].copy()                                  #Bereits vorhandene Zeitstempelspalte auswählen
                                                                                #copy(): Ursprüngliche Daten unverändert lassen

# Convert text to datetime
df_dates['timestamp_parsed'] = pd.to_datetime(
    df_dates['timestamp'],
    format='%Y-%m-%d %H:%M:%S',
    errors='coerce')                                                            #Textwerte in echte Datumsobjekte umwandeln
                                                                                #format: Erwartetes Eingabeformat angeben
                                                                                #errors='coerce': Ungültige Datumsangaben als NaT speichern (fehlender Datumswert)

# Extract date components
df_dates['year'] = df_dates['timestamp_parsed'].dt.year                         #Jahr aus Datum extrahieren
df_dates['month'] = df_dates['timestamp_parsed'].dt.month                       #Monat extrahieren
df_dates['day'] = df_dates['timestamp_parsed'].dt.day                           #Tag extrahieren

# Format datetime as string
df_dates['date_formatted'] = df_dates['timestamp_parsed'].dt.strftime('%d.%m.%Y') #Datum als Text im Format TT.MM.JJJJ darstellen

# Show data
df_dates.head()                                                                 #Original, konvertiertes Datum und extrahierte Bestandteile vergleichen

#ANPASSEN: df_apartments an den verwendeten DataFrame anpassen
#ANPASSEN: 'timestamp' an die vorhandene Datumsspalte anpassen
#ANPASSEN: format='%Y-%m-%d %H:%M:%S' an das tatsächliche Eingabeformat anpassen
#ANPASSEN: '%d.%m.%Y' an das gewünschte Ausgabeformat anpassen
#NICHTS ANPASSEN: pd.to_datetime(), .dt.year, .dt.month, .dt.day und .dt.strftime()
#VORAUSSETZUNG: import pandas as pd; die ursprüngliche Datumsspalte muss existieren
#ERKENNTNIS: Echte Datumswerte ermöglichen zeitbasierte Berechnungen; strftime() erzeugt Text

## 6. Data Discretization: KBinsDiscretizer (scikit-learn)

- **Definition:** `KBinsDiscretizer()` ist eine scikit-learn-Methode, die kontinuierliche numerische Werte automatisch in eine festgelegte Anzahl von Intervallen (Bins) einteilt.
- **Zweck:** Numerische Daten in Kategorien umwandeln, um Rauschen zu reduzieren, Merkmale zu vereinfachen und neue kategoriale Features für Machine Learning zu erstellen.
- **Methode:** `KBinsDiscretizer(n_bins=3, encode='ordinal', strategy='uniform')`
- **Wichtige Parameter:**
  - `n_bins=3`: Anzahl gewünschter Klassen, beispielsweise drei Preiskategorien.
  - `encode='ordinal'`: Klassen als Ganzzahlen `0`, `1`, `2` codieren.
  - `strategy='uniform'`: Wertebereich in gleich breite Intervalle aufteilen.
  - `strategy='quantile'`: Intervalle mit ungefähr gleich vielen Beobachtungen erstellen.
  - `strategy='kmeans'`: Intervallgrenzen durch K-Means-Clustering bestimmen.
- **Methoden:**
  - `.fit_transform()`: Intervallgrenzen aus den Daten bestimmen und die Werte den Klassen zuordnen.
  - `.ravel()`: Das zweidimensionale Ergebnis in ein eindimensionales Array umwandeln.
  - `.bin_edges_`: Ermittelte Klassengrenzen anzeigen.
- **Unterschied zu pandas:**
  - `pd.cut()`: Einteilung in gleich breite oder selbst definierte Intervalle.
  - `pd.qcut()`: Einteilung anhand von Quantilen.
  - `KBinsDiscretizer()`: Scikit-learn-Variante, deren gelernte Intervallgrenzen später auf neue Daten angewendet werden können.
- **Vorteile:** Rauschen reduzieren, Interpretierbarkeit verbessern und zusätzliche kategoriale Features erzeugen.
- **Nachteile:** Informationsverlust durch Zusammenfassung genauer Zahlenwerte; Anzahl und Lage der Klassengrenzen beeinflussen das Ergebnis.
- **Erkenntnis:** Die ursprünglichen Zahlen werden Klassen zugeordnet. Die genaue Information innerhalb eines Intervalls geht dabei verloren.

In [ ]:
# Import KBinsDiscretizer
from sklearn.preprocessing import KBinsDiscretizer              #Methode zur automatischen Diskretisierung numerischer Werte importieren

# Select numerical data
df_bins = df_autoscout[['price']].dropna().copy()               #Numerische Preisspalte auswählen
                                                                #dropna(): Fehlende Preise entfernen, damit die Klasseneinteilung berechnet werden kann
                                                                #copy(): Originalen DataFrame unverändert lassen

# Create the discretizer
discretizer = KBinsDiscretizer(
    n_bins=3,                                                   #Drei Klassen erstellen
    encode='ordinal',                                           #Klassen als Zahlen 0, 1 und 2 codieren
    strategy='uniform')                                         #Gleich breite Preisintervalle verwenden

# Fit and transform the data
# Fit and transform the data
df_bins['price_bin'] = discretizer.fit_transform(
    df_bins[['price']].to_numpy(copy=True)).ravel().astype(int) #Schreibbare NumPy-Kopie übergeben und Werte den Preisklassen zuordnen
                                                                #to_numpy(copy=True): Unabhängige, beschreibbare Array-Kopie erstellen
                                                                #fit_transform(): Klassengrenzen bestimmen und Werte zuordnen
                                                                #ravel(): 2D-Ergebnis in 1D umwandeln
                                                                #astype(int): Klassen als Ganzzahlen speichern

# Show bin boundaries
print('Bin boundaries:', discretizer.bin_edges_[0])             #Berechnete Preisgrenzen der Klassen anzeigen

# Show data
df_bins.head()                                                  #Originalpreis und zugeordnete Preisklasse anzeigen

#ANPASSEN: df_autoscout an den verwendeten DataFrame anpassen
#ANPASSEN: 'price' an die numerische Ausgangsspalte anpassen
#ANPASSEN: 'price_bin' an den gewünschten Namen der neuen Klassenspalte anpassen
#ANPASSEN: n_bins=3 an die gewünschte Klassenanzahl anpassen
#OPTIONAL: strategy='quantile' für ungefähr gleich viele Datensätze je Klasse
#OPTIONAL: strategy='kmeans' für Klassengrenzen mittels K-Means
#NICHTS ANPASSEN: KBinsDiscretizer(), fit_transform(), ravel() und bin_edges_
#VORAUSSETZUNG: Numerische Spalte mit ausreichend unterschiedlichen Werten
#ACHTUNG: Bei zu wenigen unterschiedlichen Werten kann sklearn weniger Klassen als angefordert erzeugen
#ERKENNTNIS: Ordinal codierte Bins sind Zahlenlabels für Klassen, keine unveränderten Originalwerte

## 7. One-Hot Encoding: OneHotEncoder (scikit-learn)

- **Definition:** `OneHotEncoder()` wandelt kategoriale Merkmale in binäre Merkmale um, sodass jede Kategorie durch eine eigene Spalte repräsentiert wird.
- **Zweck:** Kategoriale Variablen für Machine-Learning-Algorithmen nutzbar machen, ohne eine künstliche Rangfolge zwischen nominalen Kategorien einzuführen.
- **Beispiel:** Eine Spalte `fuel_type` mit Diesel, Benzin und Elektro wird in drei Spalten umgewandelt. Pro Fahrzeug erhält die passende Kategorie eine `1`, die anderen eine `0`.
- **Methode:** `OneHotEncoder(sparse_output=False, handle_unknown='ignore')`
- **Wichtige Parameter:**
  - `sparse_output=False`: Ergebnis als normales NumPy-Array statt als Sparse-Matrix ausgeben.
  - `handle_unknown='ignore'`: Neue, beim Training unbekannte Kategorien werden beim Transformieren ohne Fehler als Nullen codiert.
  - `drop='first'`: Optional die erste Kategorie entfernen, beispielsweise um bei bestimmten Regressionsmodellen perfekte Multikollinearität zu vermeiden.
- **Methoden:**
  - `.fit_transform()`: Kategorien erkennen und in binäre Merkmale umwandeln.
  - `.get_feature_names_out()`: Namen der neu erzeugten Dummy-Spalten zurückgeben.
  - `pd.DataFrame()`: Das sklearn-Ergebnis in einen DataFrame umwandeln.
- **Vorteile:**
  - Keine künstliche Rangfolge zwischen Kategorien.
  - Geeignet für viele Machine-Learning-Modelle, beispielsweise lineare Regression und neuronale Netze.
- **Nachteile:**
  - Viele Kategorien erzeugen viele zusätzliche Spalten (Curse of Dimensionality).
  - Die entstehenden Daten enthalten häufig viele Nullen (Sparse Data).
- **Unterschied zu pd.get_dummies():**
  - `pd.get_dummies()` ist die einfache pandas-Variante.
  - `OneHotEncoder()` ist für sklearn-Pipelines geeignet und kann die beim Training gelernten Kategorien später erneut verwenden.
- **Erkenntnis:** One-Hot Encoding macht nominale Kategorien numerisch verwendbar, ohne ihnen eine inhaltlich falsche Reihenfolge zuzuweisen.

In [33]:
# Import OneHotEncoder
from sklearn.preprocessing import OneHotEncoder                                 #Scikit-learn-Methode zur Umwandlung kategorialer Werte importieren

# Select categorical data
df_ohe = df_autoscout[['fuel_type']].dropna().head(10).copy()                   #Treibstoffarten der ersten zehn gültigen Fahrzeuge auswählen
                                                                                #dropna(): Fehlende Kategorien ausschliessen
                                                                                #copy(): Ursprüngliche Daten unverändert lassen

# Create the encoder
encoder = OneHotEncoder(
    sparse_output=False,                                                        #Normales NumPy-Array statt Sparse-Matrix erzeugen
    handle_unknown='ignore')                                                    #Unbekannte Kategorien bei späteren Transformationen ohne Fehler behandeln

# Fit and transform the categorical variable
encoded_values = encoder.fit_transform(df_ohe[['fuel_type']])                   #Vorhandene Treibstoffarten erkennen und in 0/1-Werte umwandeln
                                                                                #fit_transform(): Kategorien lernen und anschliessend codieren
                                                                                #[['fuel_type']]: Spalte als zweidimensionalen DataFrame übergeben

# Convert encoded values into a dataframe
df_encoded = pd.DataFrame(
    encoded_values,                                                             #Die erzeugten binären Werte verwenden
    columns=encoder.get_feature_names_out(['fuel_type']),                       #Automatisch Spaltennamen wie fuel_type_Diesel erzeugen
    index=df_ohe.index).astype(int)                                             #Ursprünglichen Index beibehalten und Werte als 0/1 speichern

# Combine original and encoded data
df_ohe_result = pd.concat([df_ohe, df_encoded], axis=1)                         #Originale Kategoriespalte und neue Dummy-Spalten nebeneinander anzeigen
                                                                                #axis=1: DataFrames spaltenweise verbinden

# Show data
df_ohe_result.head(10)                                                          #Originale Treibstoffart und codierte Kategorien vergleichen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: 'fuel_type' überall durch die gewünschte kategoriale Spalte ersetzen
#ANPASSEN: head(10) an die gewünschte Anzahl angezeigter Datensätze anpassen
#OPTIONAL: drop='first' im OneHotEncoder ergänzen, wenn eine Referenzkategorie weggelassen werden soll
#NICHTS ANPASSEN: OneHotEncoder(), fit_transform(), get_feature_names_out(), pd.DataFrame() und pd.concat()
#VORAUSSETZUNG: Scikit-learn >= 1.2 und eine vorhandene kategoriale Spalte
#ACHTUNG: sparse_output=False kann bei sehr vielen Kategorien hohen Speicherverbrauch verursachen
#ERKENNTNIS: Beim sklearn-Encoder bleiben Kategorien und Codierung gespeichert und können auf neue Daten angewendet werden

NameError: name 'df_autoscout' is not defined

## 8. Combining Data: join()

- **Definition:** `DataFrame.join()` verbindet die Spalten zweier DataFrames anhand ihrer Indizes oder anhand einer Spalte des linken DataFrames und des Index des rechten DataFrames.
- **Zweck:** Zusätzliche Informationen aus einer anderen Tabelle zu bestehenden Datensätzen ergänzen.
- **Methode:** `df_left.join(df_right, on='offer_id', how='left')`
- **Wichtige Parameter:**
  - `on='offer_id'`: Schlüsselspalte im linken DataFrame, die mit dem Index des rechten DataFrames verglichen wird.
  - `how='left'`: Alle Zeilen des linken DataFrames behalten (Standard bei join).
  - `how='inner'`: Nur Datensätze mit passenden Schlüsseln in beiden Tabellen behalten.
  - `how='right'`: Alle Zeilen des rechten DataFrames behalten.
  - `how='outer'`: Alle Schlüssel aus beiden Tabellen berücksichtigen.
  - `.set_index('offer_id')`: Die gemeinsame Schlüsselspalte als Index festlegen.
  - `lsuffix` und `rsuffix`: Suffixe für gleichnamige Spalten aus beiden Tabellen definieren.
- **Beispiel:** Fahrzeugangebote über `offer_id` mit geografischen Informationen wie Breitengrad und Längengrad verbinden.
- **Unterschied zu merge():**
  - `merge()`: Verbindet standardmässig über gemeinsame Spalten; `how='inner'` ist Standard.
  - `join()`: Verbindet standardmässig über Indizes; `how='left'` ist Standard.
  - Bei `join(on='offer_id')` wird die linke Spalte `offer_id` mit dem Index des rechten DataFrames verglichen.
- **Erkenntnis:** `join()` eignet sich besonders für das Ergänzen von Informationen anhand vorhandener Indizes. Gleiche oder mehrfach vorkommende Schlüsselwerte können die Anzahl der Ergebniszeilen beeinflussen.

In [ ]:
# Join geo-information to the car data using the offer_id
df_right = df_geo[['offer_id', 'lat', 'lon']].drop_duplicates(
    subset='offer_id').set_index('offer_id')                                    #Geodaten vorbereiten und Angebotsnummer als Index verwenden
                                                                                #drop_duplicates(): Pro Angebotsnummer nur einen Geodatensatz behalten
                                                                                #set_index(): offer_id vom normalen Spaltenwert zum Index machen

# Join both dataframes
df_join = df_autoscout[['offer_id', 'type', 'price']].join(
    df_right,                                                                   #Rechter DataFrame mit geografischen Informationen
    on='offer_id',                                                              #Linke offer_id mit dem Index des rechten DataFrames vergleichen
    how='left')                                                                 #Alle Fahrzeugangebote behalten; fehlende Geodaten werden NaN
                                                                                #join(): Spalten beider DataFrames anhand passender Schlüsselwerte zusammenführen
                                                                                #Erkenntnis: Fahrzeugdaten werden um lat und lon ergänzt

# Show data
df_join.head()                                                                  #Erste fünf zusammengeführte Datensätze anzeigen

#ANPASSEN: df_autoscout durch den linken DataFrame ersetzen
#ANPASSEN: df_geo durch den rechten DataFrame ersetzen
#ANPASSEN: 'offer_id' an beiden Stellen an die gemeinsame Schlüsselspalte anpassen
#ANPASSEN: ['offer_id', 'lat', 'lon'] und ['offer_id', 'type', 'price'] an die benötigten Spalten anpassen
#OPTIONAL: how='inner', 'right' oder 'outer' statt how='left' verwenden
#OPTIONAL: lsuffix='_left', rsuffix='_right' ergänzen, wenn beide Tabellen gleichnamige Spalten besitzen
#NICHTS ANPASSEN: .join(), .set_index(), on= und .head()
#VORAUSSETZUNG: df_autoscout und df_geo sind bereits eingelesen; Schlüsselspalte muss in beiden vorhanden sein
#ACHTUNG: drop_duplicates() behält hier den ersten Geodatensatz je Angebot; widersprüchliche Duplikate vorher prüfen

## 9. Combining Data: pd.concat()

- **Definition:** `pd.concat()` verbindet mehrere DataFrames entlang der Zeilen- oder Spaltenachse zu einem gemeinsamen DataFrame.
- **Zweck:** Daten aus mehreren Tabellen oder Teilmengen zusammenführen, beispielsweise mehrere Dateien mit identischen Spalten untereinander anhängen.
- **Methode:** `pd.concat([df1, df2], axis=0)`
- **Wichtige Parameter:**
  - `[df1, df2]`: Liste der zusammenzuführenden DataFrames.
  - `axis=0`: DataFrames untereinander anhängen (Standard).
  - `axis=1`: DataFrames nebeneinander anordnen.
  - `ignore_index=True`: Nach dem Zusammenfügen einen neuen fortlaufenden Zeilenindex vergeben.
  - `join='outer'`: Alle Spalten beziehungsweise Indexwerte berücksichtigen (Standard).
  - `join='inner'`: Nur gemeinsame Spalten beziehungsweise Indexwerte berücksichtigen.
  - `keys=['A', 'B']`: Optional einen zusätzlichen Index zur Kennzeichnung der ursprünglichen DataFrames erstellen.
- **Ergebnis:**
  - `axis=0`: Anzahl Zeilen wird erhöht; gleichnamige Spalten werden untereinander angeordnet.
  - `axis=1`: Anzahl Spalten wird erhöht; die Werte werden anhand der Zeilenindizes ausgerichtet.
- **Unterschied zu merge() und join():**
  - `merge()` und `join()` kombinieren Daten anhand von Schlüsseln oder Indizes.
  - `concat()` hängt Daten entlang einer Achse zusammen, ohne eine klassische Schlüssel-JOIN-Operation durchzuführen.
- **Erkenntnis:** `concat()` eignet sich besonders für die Kombination mehrerer Datensätze mit gleicher Struktur. Bei unterschiedlichen Spalten oder Indizes können durch die Ausrichtung fehlende Werte (`NaN`) entstehen.

In [ ]:
# Create two subsets of car data
df_part1 = df_autoscout[['offer_id', 'type', 'price']].iloc[:5].copy()          #Erste fünf Fahrzeugangebote auswählen
df_part2 = df_autoscout[['offer_id', 'type', 'price']].iloc[5:10].copy()        #Nächste fünf Fahrzeugangebote auswählen
                                                                                #iloc: Zeilen über ihre Position auswählen

# Concatenate dataframes vertically
df_concat_rows = pd.concat(
    [df_part1, df_part2],                                                       #Beide DataFrames zur Zusammenführung übergeben
    axis=0,                                                                     #axis=0: Zeilen untereinander anhängen
    ignore_index=True)                                                          #Neuen fortlaufenden Index ab 0 vergeben
                                                                                #Ergebnis: Bei jeweils fünf Zeilen entstehen zehn Zeilen

# Show vertically concatenated data
print('Concatenated rows:')
display(df_concat_rows.head(10))                                                #Alle zehn zusammengeführten Fahrzeugangebote anzeigen

# Create two subsets with different columns
df_cols1 = df_autoscout[['offer_id', 'price']].head(5).copy()                   #Angebotsnummer und Preis auswählen
df_cols2 = df_autoscout[['mileage', 'hp']].head(5).copy()                       #Kilometerstand und Motorleistung auswählen

# Concatenate dataframes horizontally
df_concat_columns = pd.concat(
    [df_cols1, df_cols2],                                                       #Beide Teilmengen verbinden
    axis=1)                                                                     #axis=1: Spalten nebeneinander anordnen
                                                                                #Werte werden über den Zeilenindex zugeordnet

# Show horizontally concatenated data
print('Concatenated columns:')
display(df_concat_columns.head())                                               #Alle vier ausgewählten Spalten gemeinsam anzeigen

#ANPASSEN: df_autoscout an den verwendeten DataFrame anpassen
#ANPASSEN: Spaltenlisten an die vorhandenen Spalten anpassen
#ANPASSEN: iloc[:5] und iloc[5:10] an die gewünschten Zeilenbereiche anpassen
#ANPASSEN: axis=0 für untereinander oder axis=1 für nebeneinander
#OPTIONAL: ignore_index=True für einen neuen fortlaufenden Zeilenindex
#OPTIONAL: join='inner' für die Beschränkung auf gemeinsame Spalten beziehungsweise Indizes
#OPTIONAL: keys=['A', 'B'] beim vertikalen Zusammenfügen, um die Herkunft der Zeilen kenntlich zu machen
#NICHTS ANPASSEN: pd.concat(), .iloc[] und .head()
#VORAUSSETZUNG: Die verwendeten DataFrames müssen existieren
#ACHTUNG: Bei axis=1 müssen die Zeilenindizes korrekt zusammenpassen, sonst können Werte falsch zugeordnet oder NaN erzeugt werden

## 10. Aggregation of Data: groupby() und agg()

- **Definition:** `groupby()` gruppiert Datensätze anhand gemeinsamer Merkmale, wendet auf jede Gruppe eine Funktion an und kombiniert anschliessend die Ergebnisse.
- **Zweck:** Grosse Datenmengen zusammenfassen und Kennzahlen für verschiedene Gruppen berechnen, beispielsweise den durchschnittlichen Fahrzeugpreis je Treibstoffart.
- **Funktionsprinzip – Split, Apply, Combine:**
  1. **Split:** DataFrame anhand einer oder mehrerer Spalten in Gruppen aufteilen.
  2. **Apply:** Berechnungen wie Mittelwert, Summe oder Anzahl auf jede Gruppe anwenden.
  3. **Combine:** Gruppenergebnisse zu einem neuen Ergebnis zusammenfügen.
- **Methode:** `df.groupby('fuel_type')['price'].mean()`
- **Wichtige Methoden:**
  - `.groupby('spalte')`: Datensätze nach den Werten einer Spalte gruppieren.
  - `.mean()`: Mittelwert pro Gruppe berechnen.
  - `.median()`: Median pro Gruppe berechnen.
  - `.sum()`: Summe pro Gruppe berechnen.
  - `.min()` / `.max()`: Kleinsten beziehungsweise grössten Wert pro Gruppe bestimmen.
  - `.count()`: Nicht fehlende Werte pro Gruppe zählen.
  - `.size()`: Anzahl Datensätze pro Gruppe zählen, einschliesslich Zeilen mit fehlenden Werten.
  - `.agg()`: Mehrere Aggregationsfunktionen gleichzeitig anwenden.
  - `.reset_index()`: Gruppierungsindex wieder in eine normale Spalte umwandeln.
- **Beispiel:** Fahrzeuge nach Treibstoffart gruppieren und jeweils den durchschnittlichen Preis sowie den durchschnittlichen Kilometerstand berechnen.
- **Unterschied zu pivot_table():**
  - `groupby()`: Flexible Gruppierung und Aggregation von Daten.
  - `pivot_table()`: Gruppierung und Aggregation mit zusätzlicher Möglichkeit, Gruppierungswerte über `columns=` als Spalten darzustellen.
- **Erkenntnis:** `groupby()` verändert die Datenstruktur durch Aggregation: Mehrere Datensätze einer Gruppe werden zu zusammengefassten Kennzahlen.

In [ ]:
# Group car data by fuel type and calculate mean values
df_groupby = df_autoscout.groupby('fuel_type')[['price', 'mileage', 'hp']].mean().round(2)  #Fahrzeuge nach Treibstoffart gruppieren
                                                                                            #groupby('fuel_type'): Eine Gruppe pro Treibstoffart erstellen
                                                                                            #[['price', 'mileage', 'hp']]: Numerische Spalten auswählen
                                                                                            #mean(): Mittelwerte je Gruppe berechnen
                                                                                            #round(2): Ergebnisse auf zwei Dezimalstellen runden

# Show grouped data
print('Mean values per fuel type:')
display(df_groupby)                                                                         #Durchschnittspreis, Kilometerstand und PS je Treibstoffart anzeigen

# Aggregate different statistics per group
df_groupby_agg = df_autoscout.groupby('fuel_type').agg(
    anzahl_angebote=('offer_id', 'size'),                                                   #Anzahl Datensätze pro Treibstoffart zählen
    durchschnitt_preis=('price', 'mean'),                                                   #Durchschnittlichen Fahrzeugpreis berechnen
    median_kilometer=('mileage', 'median'),                                                 #Median des Kilometerstands berechnen
    maximale_ps=('hp', 'max')                                                               #Höchste Motorleistung pro Gruppe bestimmen
).round(2)                                                                                  #Ergebnisse auf zwei Dezimalstellen runden
                                                                                            #agg(): Mehrere Aggregationsfunktionen gleichzeitig anwenden
                                                                                            #Ergebnis: Pro Treibstoffart eine Zeile mit vier Kennzahlen

# Show aggregated data
print('Aggregated statistics per fuel type:')
display(df_groupby_agg)                                                                     #Kennzahlen aller Treibstoffarten anzeigen

#ANPASSEN: df_autoscout an den verwendeten DataFrame anpassen
#ANPASSEN: 'fuel_type' überall durch die gewünschte Gruppierungsspalte ersetzen
#ANPASSEN: ['price', 'mileage', 'hp'] durch die auszuwertenden numerischen Spalten ersetzen
#ANPASSEN: Spalten und Funktionen innerhalb von agg() an die geforderten Kennzahlen anpassen
#OPTIONAL: .sum(), .min(), .max(), .median() oder .count() statt .mean() verwenden
#OPTIONAL: .reset_index() ergänzen, wenn die Gruppierungsspalte eine normale Spalte sein soll
#OPTIONAL: groupby(['spalte1', 'spalte2']) für eine Gruppierung nach mehreren Merkmalen
#NICHTS ANPASSEN: .groupby(), .agg() und .round() als Methoden
#VORAUSSETZUNG: Die Gruppierungsspalte und die verwendeten numerischen Spalten müssen existieren
#ERKENNTNIS: .agg() ermöglicht unterschiedliche Kennzahlen pro Spalte innerhalb derselben Gruppierung

## 11. Reshaping Data: pivot()

- **Definition:** `pivot()` formt einen DataFrame anhand bestimmter Index- und Spaltenwerte um, sodass aus einer langen Tabelle (Long Format) eine breite Tabelle (Wide Format) entsteht.
- **Zweck:** Werte verschiedener Merkmale in eigene Spalten überführen, um die Daten übersichtlicher darzustellen oder weiterzuverarbeiten.
- **Methode:** `df.pivot(index='offer_id', columns='variable', values='value')`
- **Wichtige Parameter:**
  - `index='offer_id'`: Spalte, deren Werte zum neuen Zeilenindex werden.
  - `columns='variable'`: Spalte, deren Werte zu neuen Spaltennamen werden.
  - `values='value'`: Spalte mit den eigentlichen Werten, die in die neue Tabellenstruktur eingetragen werden.
- **Funktionsweise:**
  - Die Werte aus `index` bestimmen die Zeilen.
  - Die Kategorien aus `columns` bestimmen die neuen Spalten.
  - Die zugehörigen Daten aus `values` werden in die entsprechenden Zellen eingetragen.
- **Beispiel:** Eine lange Tabelle enthält pro Fahrzeug eine Zeile für den Preis und eine weitere für die Motorleistung. Mit `pivot()` entsteht wieder eine Tabelle mit einer Zeile pro Fahrzeug sowie separaten Spalten für Preis und Motorleistung.
- **Unterschied zu melt():**
  - `melt()`: Breites Format in langes Format umwandeln.
  - `pivot()`: Langes Format in breites Format umwandeln.
- **Unterschied zu pivot_table():**
  - `pivot()`: Strukturiert Daten um, führt aber keine Aggregation durch.
  - `pivot_table()`: Kann zusätzlich mehrere Werte pro Gruppe aggregieren, beispielsweise deren Mittelwert berechnen.
- **Wichtige Voraussetzung:** Jede Kombination aus `index` und `columns` muss eindeutig sein. Bei mehrfach vorkommenden Kombinationen erzeugt `pivot()` einen Fehler.
- **Erkenntnis:** `pivot()` verändert die Anordnung der Werte, ohne sie inhaltlich zu verändern oder zusammenzufassen.

In [ ]:
# Create a subset of car data with unique offer IDs
df_pivot_sub = df_autoscout[['offer_id', 'price', 'hp']].drop_duplicates(
    subset='offer_id').head(5).copy()                       #Fünf Fahrzeugangebote mit eindeutiger Angebotsnummer auswählen
                                                            #drop_duplicates(): Doppelte Angebotsnummern entfernen
                                                            #copy(): Originaldaten unverändert lassen

# Reshape the data into long format
df_pivot_long = pd.melt(
    df_pivot_sub,                                           #Ausgangs-DataFrame verwenden
    id_vars=['offer_id'],                                   #Angebotsnummer als Identifikationsvariable beibehalten
    value_vars=['price', 'hp'])                             #Preis und Motorleistung untereinander anordnen
                                                            #Ergebnis: Spalten offer_id, variable und value
                                                            #Bei fünf Angeboten entstehen zehn Zeilen

# Show long format
print('Long format:')
display(df_pivot_long)                                      #Lange Tabelle mit Preis- und PS-Werten anzeigen

# Reshape the data back into wide format
df_pivot_wide = df_pivot_long.pivot(
    index='offer_id',                                       #Jedes Fahrzeug erhält eine eigene Zeile
    columns='variable',                                     #Aus 'price' und 'hp' entstehen separate Spalten
    values='value')                                         #Zu jeder Kombination den entsprechenden Wert eintragen
                                                            #pivot(): Long Format in Wide Format umwandeln
                                                            #Keine Aggregation: Die ursprünglichen Werte bleiben unverändert

# Show wide format
print('Wide format:')
display(df_pivot_wide)                                      #Fahrzeugangebote mit separaten Spalten für Preis und PS anzeigen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: ['offer_id', 'price', 'hp'] durch die benötigten Ausgangsspalten ersetzen
#ANPASSEN: id_vars=['offer_id'] durch die eindeutige Identifikationsspalte ersetzen
#ANPASSEN: value_vars=['price', 'hp'] durch die gewünschten Wertespalten ersetzen
#ANPASSEN: index='offer_id' an die Identifikationsspalte aus dem vorherigen melt()-Block anpassen
#NICHTS ANPASSEN: columns='variable' und values='value', sofern melt() die Standardspaltennamen verwendet
#NICHTS ANPASSEN: .melt(), .pivot() und .head() als Methoden
#VORAUSSETZUNG: Kombinationen aus index und columns müssen eindeutig sein
#ACHTUNG: Bei mehrfach vorhandenen Kombinationen statt pivot() gegebenenfalls pivot_table() mit aggfunc verwenden

## 12. Data Transformation: Inverse / Reciprocal Transformation

- **Definition:** Bei der inversen beziehungsweise reziproken Transformation wird jeder numerische Wert durch seinen Kehrwert ersetzt.
- **Zweck:** Numerische Zusammenhänge und Verteilungen verändern, beispielsweise bestimmte nichtlineare Beziehungen abschwächen oder linearisieren.
- **Formel:** `Y' = 1 / Y`
- **Methode:** `1 / df['spalte']` berechnet den Kehrwert jedes Werts einer numerischen Spalte.
- **Beispiel:** 2 wird zu 0.5, 4 wird zu 0.25 und 10 wird zu 0.1.
- **Voraussetzung:** Die Werte dürfen nicht 0 sein, da eine Division durch 0 nicht definiert ist.
- **Erkenntnis:** Bei positiven Werten werden grosse Werte klein und kleine positive Werte gross. Die Reihenfolge der Werte kehrt sich dadurch um. Anders als bei Scaling verändert sich die Form der Verteilung.
- **Achtung:** Werte nahe 0 können extrem grosse Kehrwerte erzeugen. Die Transformation garantiert keine Normalverteilung.

In [ ]:
# Inverse Transformation of the variable 'area'
df_inverse = df_apartments[['area']].copy()                                     #Wohnungsflächen auswählen und Originaldaten unverändert lassen

# Convert to numeric values
df_inverse['area'] = pd.to_numeric(df_inverse['area'], errors='coerce')         #Numerische Werte sicherstellen
                                                                                #Ungültige Werte als NaN behandeln

# Calculate reciprocal values
df_inverse['area_inverse'] = 1 / df_inverse['area'].where(
    df_inverse['area'] != 0)                                                    #Kehrwert jeder Wohnungsfläche berechnen
                                                                                #where(): Nullwerte durch NaN ersetzen, um Division durch 0 zu vermeiden
                                                                                #Formel: 1 / Wert; beispielsweise 1 / 100 = 0.01

# Show results
df_inverse.head()                                                               #Ursprüngliche und invers transformierte Flächen vergleichen

#ANPASSEN: df_apartments durch den verwendeten DataFrame ersetzen
#ANPASSEN: 'area' durch die zu transformierende numerische Spalte ersetzen
#ANPASSEN: 'area_inverse' an den gewünschten neuen Spaltennamen anpassen
#NICHTS ANPASSEN: pd.to_numeric(), .where() und .head()
#VORAUSSETZUNG: Numerische Ausgangswerte; 0 ist für die Kehrwertbildung ausgeschlossen
#ERKENNTNIS: Grosse positive Werte werden zu kleinen Kehrwerten und umgekehrt

## 13. Data Transformation: Exponential Transformation

- **Definition:** Bei der Exponentialtransformation wird jeder numerische Wert als Exponent der Eulerschen Zahl e verwendet.
- **Zweck:** Numerische Zusammenhänge und Verteilungen verändern, insbesondere bei exponentiellen Beziehungen zwischen Variablen.
- **Formel:** `Y' = e^Y`
- **Methode:** `np.exp()` berechnet die Exponentialfunktion für jeden Wert.
- **Beispiele:** `exp(0) = 1`, `exp(1) ≈ 2.718`, `exp(2) ≈ 7.389`.
- **Funktionsweise:** Grössere Werte wachsen nach der Transformation überproportional stark. Die Abstände zwischen grossen positiven Werten werden stärker vergrössert.
- **Unterschied zur Logarithmustransformation:** `np.log()` komprimiert grosse positive Werte, während `np.exp()` grössere Werte exponentiell verstärkt. Beide Funktionen sind Umkehrfunktionen.
- **Erkenntnis:** Die Exponentialtransformation verändert die Verteilungsform und kann Unterschiede zwischen grossen Werten verstärken. Sie ist nicht zur generellen Reduktion von Rechtsschiefe geeignet.
- **Achtung:** Sehr grosse Ausgangswerte können einen numerischen Überlauf (`inf`) verursachen.

#### Bsp. Veloshop, Gewicht aus Text extrahieren (nicht ausführbar)

In [ ]:
# Exponential Transformation of the variable 'mileage'
df_exp = df_autoscout[['mileage']].copy()                                       #Kilometerstände auswählen und in separaten DataFrame kopieren

# Convert to numeric values
df_exp['mileage'] = pd.to_numeric(df_exp['mileage'], errors='coerce')           #Numerische Werte sicherstellen

# Scale values before exponential transformation
df_exp['mileage_ratio'] = df_exp['mileage'] / df_exp['mileage'].max()           #Kilometerstand durch den grössten Wert teilen
                                                                                #Ergebnis bei nichtnegativen Werten: Bereich 0 bis 1
                                                                                #Verhindert sehr grosse Exponenten und numerischen Überlauf

# Apply exponential transformation
df_exp['mileage_exp'] = np.exp(df_exp['mileage_ratio'])                         #Exponentialfunktion auf die normierten Kilometerstände anwenden
                                                                                #np.exp(): Eulersche Zahl e hoch dem jeweiligen Wert berechnen
                                                                                #Beispiel: exp(0)=1 und exp(1)≈2.718
                                                                                #Erkenntnis: Grössere Werte werden zunehmend stärker vergrössert

# Show results
df_exp.head()                                                                   #Originalwerte, normierte Werte und transformierte Werte vergleichen

#ANPASSEN: df_autoscout durch den verwendeten DataFrame ersetzen
#ANPASSEN: 'mileage' durch die zu transformierende numerische Spalte ersetzen
#ANPASSEN: 'mileage_ratio' und 'mileage_exp' an die gewünschten neuen Spaltennamen anpassen
#OPTIONAL: Bei bereits kleinen Ausgangswerten direkt np.exp(df['spalte']) verwenden
#NICHTS ANPASSEN: np.exp(), pd.to_numeric(), .max() und .head()
#VORAUSSETZUNG: Numerische Werte; für die Normierung muss das Maximum positiv sein
#ACHTUNG: Das Beispiel transformiert den normierten Kilometerstand, nicht den rohen Kilometerstand
#ACHTUNG: np.exp() wächst sehr schnell und kann bei grossen Exponenten inf erzeugen

In [ ]:
import re                                                               #Regex-Funktionen laden

weight = []                                                             #Leere Liste für die extrahierten Zahlen
for i in df['weight_text']:                                             #Jeden Text der Ausgangsspalte durchlaufen
    d1 = re.findall(r"(\d+(?:[.,]\d+)?)\s*kg", i)                       #Zahl vor kg finden: "12,8 kg" ergibt ["12,8"]
    try:                                                                #Ersten Treffer verarbeiten
        d2 = d1[0].strip().replace(',', '.')                            #Ersten Treffer nehmen, Leerraum entfernen und Dezimalkomma ersetzen
    except IndexError:                                                  #Falls kein passender Treffer existiert
        d2 = None                                                       #Fehlenden Wert verwenden
    weight.append(d2)                                                   #Ergebnis an die Liste anhängen

df['weight_kg'] = pd.Series(weight, index=df.index, dtype="float64")    #Als neue Dezimalzahlspalte speichern
df[['weight_text', 'weight_kg']].head()                                 #Ausgangstext und Ergebnis anzeigen

#ANPASSEN: weight_text an die vorhandene Textspalte – an beiden Stellen
#ANPASSEN: kg im Regex an die gesuchte Bezeichnung, z. B. Zimmer, m² oder PS
#ANPASSEN: weight_kg an den gewünschten Zielspaltennamen – an beiden Stellen
#NICHTS ANPASSEN: Listenname weight; er muss überall gleich bleiben
#ZAHLENFORMAT: Nichtnegative ganze Zahlen oder Dezimalzahlen mit Komma/Punkt, ohne Tausendertrennzeichen